# Traducoes (ver o guia em core/idioma.py). Chave = texto ORIGINAL em portugues.
# cenas/*.py e cenas/casa_extras/* (titulo, pausa e idioma ficam em comum.py).
# Cada linha: (português, inglês, espanhol).

_T = [
    # --- Amigos ---
    ("COPIAR (C)", "COPY (C)", "COPIAR (C)"),
    ("CÓDIGO DO SEU OVO:", "YOUR EGG'S CODE:", "CÓDIGO DE TU HUEVO:"),
    ("COLE O CÓDIGO DE UM AMIGO (CTRL+V) E APERTE ENTER", "PASTE A FRIEND'S CODE (CTRL+V) AND PRESS ENTER",
     "PEGA EL CÓDIGO DE UN AMIGO (CTRL+V) Y PULSA ENTER"),
    ("CÓDIGO COPIADO! MANDE PARA UM AMIGO.", "CODE COPIED! SEND IT TO A FRIEND.", "¡CÓDIGO COPIADO! MÁNDALO A UN AMIGO."),
    ("NÃO DEU PARA COPIAR: VEJA meu_codigo_oval.txt", "COULDN'T COPY: SEE meu_codigo_oval.txt",
     "NO SE PUDO COPIAR: MIRA meu_codigo_oval.txt"),
    ("NENHUM AMIGO AINDA. TROQUE CÓDIGOS E DESAFIE RECORDES!", "NO FRIENDS YET. SWAP CODES AND CHASE RECORDS!",
     "AÚN NO HAY AMIGOS. ¡CAMBIA CÓDIGOS Y RETA RÉCORDS!"),
    ("{nome}  •  NV {nv}", "{nome}  •  LV {nv}", "{nome}  •  NV {nv}"),
    ("DUVIDO: {valor} NO {jogo}", "BEAT {valor} IN {jogo}", "SUPERA {valor} EN {jogo}"),
    ("AMIGO", "FRIEND", "AMIGO"),
    ("AMIGO ADICIONADO!", "FRIEND ADDED!", "¡AMIGO AGREGADO!"),
    ("CÓDIGO INVÁLIDO :(", "INVALID CODE :(", "CÓDIGO INVÁLIDO :("),
    ("ESSE AMIGO JÁ ESTÁ NA LISTA", "THAT FRIEND IS ALREADY ON THE LIST", "ESE AMIGO YA ESTÁ EN LA LISTA"),
    ("ESSE É O SEU PRÓPRIO CÓDIGO!", "THAT'S YOUR OWN CODE!", "¡ESE ES TU PROPIO CÓDIGO!"),
    ("MÁXIMO DE {n} AMIGOS", "{n} FRIENDS MAX", "MÁXIMO {n} AMIGOS"),

    # --- Casa ---
    ("▶ JOGAR", "▶ PLAY", "▶ JUGAR"),
    ("NÍVEL {n}!", "LEVEL {n}!", "¡NIVEL {n}!"),
    ("NÃO! TÔ CHEIO!", "NO! I'M FULL!", "¡NO! ¡ESTOY LLENO!"),
    ("ENQUANTO VOCÊ ESTAVA FORA...", "WHILE YOU WERE AWAY...", "MIENTRAS NO ESTABAS..."),
    ("Clique na bola para jogar!", "Click the ball to play!", "¡Haz clic en la bola!"),
    ("NV {n}", "LV {n}", "NV {n}"),
    ("RUA", "STREET", "CALLE"),
    ("BOM DIA!", "GOOD MORNING!", "¡BUEN DÍA!"),
    ("clique para continuar", "click to continue", "clic para continuar"),
    ("BRRR!", "BRRR!", "¡BRRR!"),
    ("RONC!", "GRUMBLE!", "¡GRRR!"),
    ("← → troca de cômodo  •  vá ao BRINCAR para jogar!", "← → change room  •  go to PLAY to play games!",
     "← → cambia de cuarto  •  ¡ve a JUGAR para jugar!"),
    ("NOVO! VEJA SUA RUA", "NEW! SEE YOUR STREET", "¡NUEVO! MIRA TU CALLE"),
    ("FELIZ x{m:.2f}", "HAPPY x{m:.2f}", "FELIZ x{m:.2f}"),
    ("COMIDA", "FOOD", "COMIDA"),
    ("SABÃO", "SOAP", "JABÓN"),
    ("LUZ", "LIGHT", "LUZ"),
    ("ÁLBUM", "ALBUM", "ÁLBUM"),
    ("POTE DE OURO! +15 OVOEDAS", "POT OF GOLD! +15 EGGCOINS", "¡OLLA DE ORO! +15 HUEVEDAS"),
    ("PIU achou uma SEMENTE DE LIMÃO!", "PEEP found a LEMON SEED!", "¡PÍO encontró una SEMILLA DE LIMÓN!"),
    ("FLOCO achou uma CENOURA!", "FLAKE found a CARROT!", "¡COPO encontró una ZANAHORIA!"),
    ("FAÍSCA assou um MARSHMALLOW!", "SPARK toasted a MARSHMALLOW!", "¡CHISPA tostó un MALVAVISCO!"),

    # --- Casa: cuidados, jardim, quintal, eventos ---
    ("GELADEIRA VAZIA! COMPRE COMIDA NA LOJA", "FRIDGE IS EMPTY! BUY FOOD AT THE SHOP",
     "¡NEVERA VACÍA! COMPRA COMIDA EN LA TIENDA"),
    ("ARRASTE ATÉ A BOCA DO OVO", "DRAG IT TO THE EGG'S MOUTH", "ARRÁSTRALO A LA BOCA DEL HUEVO"),
    ("CHUVEIRO!", "SHOWER!", "¡DUCHA!"),
    ("ESFREGUE NO OVO! (botão direito sai)", "SCRUB THE EGG! (right click to stop)",
     "¡FROTA EL HUEVO! (clic derecho sale)"),
    ("OVINHO DE PÁSCOA! Faltam {n} hoje.", "EASTER EGG! {n} left today.", "¡HUEVITO DE PASCUA! Faltan {n} hoy."),
    ("ACHOU TODOS OS OVINHOS DE HOJE!", "FOUND ALL OF TODAY'S EGGS!", "¡ENCONTRASTE TODOS LOS HUEVITOS!"),
    ("COMPRE SEMENTES NO MERCADO DA LOJA!", "BUY SEEDS AT THE SHOP MARKET!", "¡COMPRA SEMILLAS EN EL MERCADO!"),
    ("PRONTO EM {tempo}", "READY IN {tempo}", "LISTO EN {tempo}"),
    ("PLANTAR", "PLANT", "PLANTAR"),
    ("REGAR!", "WATER!", "¡REGAR!"),
    ("ESCOLHA A SEMENTE", "PICK A SEED", "ELIGE LA SEMILLA"),
    ("♪ JUKEBOX ♪", "♪ JUKEBOX ♪", "♪ ROCOLA ♪"),
    ("DICA: EXPLORE O JOGO", "HINT: EXPLORE THE GAME", "PISTA: EXPLORA EL JUEGO"),
    ("{n} trilhas liberadas • jogue e explore para liberar mais!",
     "{n} tracks unlocked • play and explore to unlock more!",
     "{n} pistas desbloqueadas • ¡juega y explora para más!"),
    ("ÁLBUM DE BORBOLETAS", "BUTTERFLY ALBUM", "ÁLBUM DE MARIPOSAS"),
    ("{n}/{total} — complete e ganhe ASAS!", "{n}/{total} — complete it to earn WINGS!",
     "{n}/{total} — ¡complétalo y gana ALAS!"),
    ("NOVA NO ÁLBUM: {nome}!", "NEW IN THE ALBUM: {nome}!", "¡NUEVA EN EL ÁLBUM: {nome}!"),
    ("ÁLBUM COMPLETO! GANHOU ASAS DE BORBOLETA!", "ALBUM COMPLETE! YOU GOT BUTTERFLY WINGS!",
     "¡ÁLBUM COMPLETO! ¡GANASTE ALAS DE MARIPOSA!"),
    ("ARRASTE E SOLTE A BOLA PARA JOGAR!", "DRAG AND DROP THE BALL TO PLAY!", "¡ARRASTRA Y SUELTA LA BOLA!"),
    ("MONARCA", "MONARCH", "MONARCA"),
    ("AZULÃO", "BLUEY", "AZULITA"),
    ("LIMÃOZINHA", "LEMONY", "LIMONCITA"),
    ("ROSINHA", "PINKY", "ROSITA"),
    ("FOLHINHA", "LEAFY", "HOJITA"),
    ("VIOLETA", "VIOLET", "VIOLETA"),
    ("NUVEM", "CLOUD", "NUBE"),
    ("DOURADA RARA", "RARE GOLDEN", "DORADA RARA"),

    # --- Casa: rotina (dicas, missões, baú) ---
    ("Dica: com as 4 barrinhas acima de 70 você ganha +10% de OVOEDAS!",
     "Tip: keep all 4 bars above 70 to earn +10% EGGCOINS!",
     "Tip: con las 4 barras sobre 70 ganas +10% de HUEVEDAS!"),
    ("Dica: a chuva rega o jardim sozinha.", "Tip: rain waters the garden for you.",
     "Tip: la lluvia riega el jardín sola."),
    ("Dica: pegue todas as borboletas e ganhe asas!", "Tip: catch every butterfly to earn wings!",
     "Tip: ¡atrapa todas las mariposas y gana alas!"),
    ("Dica: a 1ª partida do dia em cada jogo vale +5 OVOEDAS.",
     "Tip: the 1st round of each game every day gives +5 EGGCOINS.",
     "Tip: la 1ª partida del día en cada juego da +5 HUEVEDAS."),
    ("Dica: apague a luz para o ovo dormir e recuperar a energia.",
     "Tip: turn off the light so the egg can sleep and recharge.",
     "Tip: apaga la luz para que el huevo duerma y recargue."),
    ("Dica: jogos para 2 ficam na aba 2 JOGADORES.", "Tip: 2-player games are in the 2 PLAYERS tab.",
     "Tip: los juegos para 2 están en la pestaña 2 JUGADORES."),
    ("Dica: depois da chuva procure o pote de ouro do arco-íris!",
     "Tip: after the rain, look for the rainbow's pot of gold!",
     "Tip: ¡tras la lluvia busca la olla de oro del arcoíris!"),
    ("Dica: aperte L para abrir a loja.", "Tip: press L to open the shop.", "Tip: pulsa L para abrir la tienda."),
    ("JOGUE {n} PARTIDAS", "PLAY {n} ROUNDS", "JUEGA {n} PARTIDAS"),
    ("VENÇA {n} PARTIDA(S)", "WIN {n} ROUND(S)", "GANA {n} PARTIDA(S)"),
    ("DÊ {n} BANHO(S) NO OVO", "GIVE THE EGG {n} BATH(S)", "DA {n} BAÑO(S) AL HUEVO"),
    ("COMA {n} VEZES", "EAT {n} TIMES", "COME {n} VECES"),
    ("FAÇA {n} CARINHOS", "GIVE {n} PETS", "HAZ {n} MIMOS"),
    ("GANHE {n} OVOEDAS EM JOGOS", "EARN {n} EGGCOINS IN GAMES", "GANA {n} HUEVEDAS EN JUEGOS"),
    ("SEQUÊNCIA DE {n} DIAS PERDIDA :(  +{premio} e 1 {nome}", "{n}-DAY STREAK LOST :(  +{premio} and 1 {nome}",
     "RACHA DE {n} DÍAS PERDIDA :(  +{premio} y 1 {nome}"),
    ("{n} DIAS SEGUIDOS! (SEMANA {semana}) +{premio} e 1 {nome}!",
     "{n} DAYS IN A ROW! (WEEK {semana}) +{premio} and 1 {nome}!",
     "¡{n} DÍAS SEGUIDOS! (SEMANA {semana}) +{premio} y 1 {nome}!"),
    ("BAÚ DO DIA {n}/7: +{premio} OVOEDAS e 1 {nome}!", "DAILY CHEST {n}/7: +{premio} EGGCOINS and 1 {nome}!",
     "¡COFRE DEL DÍA {n}/7: +{premio} HUEVEDAS y 1 {nome}!"),
    ("+{n} OVOEDAS", "+{n} EGGCOINS", "+{n} HUEVEDAS"),
    ("3 MISSÕES COMPLETAS!", "3 MISSIONS DONE!", "¡3 MISIONES HECHAS!"),
    ("CAIXA SURPRESA: ", "MYSTERY BOX: ", "CAJA SORPRESA: "),
    ("PARABÉNS! Desafio cumprido: +{n} OVOEDAS!", "CONGRATS! Challenge done: +{n} EGGCOINS!",
     "¡BRAVO! Reto cumplido: +{n} HUEVEDAS!"),
    ("MISSÕES DO DIA", "DAILY MISSIONS", "MISIONES DEL DÍA"),
    ("DESAFIO: ", "CHALLENGE: ", "RETO: "),
    ("BÔNUS JÁ RECEBIDO!", "BONUS CLAIMED!", "¡BONO RECIBIDO!"),
    ("COMPLETE AS 3: +{n} E UMA CAIXA SURPRESA!", "DO ALL 3: +{n} AND A MYSTERY BOX!",
     "HAZ LAS 3: ¡+{n} Y UNA CAJA SORPRESA!"),
    ("BAÚ DIÁRIO", "DAILY CHEST", "COFRE DIARIO"),
    ("BAÚ DIÁRIO  •  SEMANA {n}", "DAILY CHEST  •  WEEK {n}", "COFRE DIARIO  •  SEMANA {n}"),
    ("DIA {n}", "DAY {n}", "DÍA {n}"),

    # --- Casa: tutorial ---
    ("Estou com FOME! Clique em COMIDA e arraste algo até a minha boca.",
     "I'm HUNGRY! Click FOOD and drag something to my mouth.",
     "¡Tengo HAMBRE! Haz clic en COMIDA y arrastra algo a mi boca."),
    ("Tô sujinho... Clique no SABÃO, esfregue e depois clique no CHUVEIRO.",
     "I'm all dirty... Click SOAP, scrub, then click the SHOWER.",
     "Estoy sucio... Haz clic en JABÓN, frota y luego en la DUCHA."),
    ("Vamos brincar? Vá para o cômodo BRINCAR (seta > ou tecla 3).",
     "Wanna play? Go to the PLAY room (arrow > or key 3).",
     "¿Jugamos? Ve al cuarto JUGAR (flecha > o tecla 3)."),
    ("Clique na bola (ou em JOGAR) e jogue uma partida!", "Click the ball (or PLAY) and play a round!",
     "¡Haz clic en la bola (o en JUGAR) y juega una partida!"),
    ("Ganhou OVOEDAS! Que tal comprar algo na LOJA?", "You earned EGGCOINS! How about buying something at the SHOP?",
     "¡Ganaste HUEVEDAS! ¿Qué tal comprar algo en la TIENDA?"),
    ("TUTORIAL {n}/{total}", "TUTORIAL {n}/{total}", "TUTORIAL {n}/{total}"),
    ("PULAR TUTORIAL", "SKIP TUTORIAL", "SALTAR TUTORIAL"),
    ("TUTORIAL COMPLETO! Agora a rua é sua!", "TUTORIAL DONE! The street is all yours!",
     "¡TUTORIAL COMPLETO! ¡La calle es tuya!"),

    # --- Rua (status dos ovos) ---
    ("PRECISA DE BANHO!", "NEEDS A BATH!", "¡NECESITA UN BAÑO!"),
    ("ESTÁ COM FOME!", "IS HUNGRY!", "¡TIENE HAMBRE!"),
    ("ESTÁ COM SONO!", "IS SLEEPY!", "¡TIENE SUEÑO!"),
    ("QUER BRINCAR!", "WANTS TO PLAY!", "¡QUIERE JUGAR!"),
    ("PLANTAS PRONTAS!", "PLANTS READY!", "¡PLANTAS LISTAS!"),
    ("BAÚ DO DIA ESPERANDO!", "DAILY CHEST WAITING!", "¡COFRE DEL DÍA ESPERA!"),
    ("CHEGOU CARTA!", "YOU'VE GOT MAIL!", "¡LLEGÓ UNA CARTA!"),
    ("OVO FELIZ! ★", "HAPPY EGG! ★", "¡HUEVO FELIZ! ★"),
    ("TUDO BEM POR AQUI.", "ALL GOOD HERE.", "TODO BIEN POR AQUÍ."),

    # --- Conquistas ---
    ("COLEÇÕES", "COLLECTIONS", "COLECCIONES"),
    ("ESTATÍSTICAS", "STATS", "ESTADÍSTICAS"),
    ("PARTIDAS JOGADAS", "ROUNDS PLAYED", "PARTIDAS JUGADAS"),
    ("VITÓRIAS", "WINS", "VICTORIAS"),
    ("RECORDES BATIDOS", "RECORDS BROKEN", "RÉCORDS SUPERADOS"),
    ("MEDALHAS DE OURO", "GOLD MEDALS", "MEDALLAS DE ORO"),
    ("OVOEDAS GANHAS EM JOGOS", "EGGCOINS EARNED IN GAMES", "HUEVEDAS GANADAS EN JUEGOS"),
    ("OVOEDAS GASTAS", "EGGCOINS SPENT", "HUEVEDAS GASTADAS"),
    ("COMPRAS", "PURCHASES", "COMPRAS"),
    ("REFEIÇÕES", "MEALS", "COMIDAS"),
    ("BANHOS", "BATHS", "BAÑOS"),
    ("CARINHOS", "PETS GIVEN", "MIMOS"),
    ("POÇÕES BEBIDAS", "POTIONS DRUNK", "POCIONES BEBIDAS"),
    ("MISSÕES CUMPRIDAS", "MISSIONS DONE", "MISIONES CUMPLIDAS"),
    ("DESAFIOS DO ROBERT", "ROBERT'S CHALLENGES", "RETOS DE ROBERT"),
    ("CAIXAS SURPRESA", "MYSTERY BOXES", "CAJAS SORPRESA"),
    ("MAIOR SEQUÊNCIA DO BAÚ", "LONGEST CHEST STREAK", "MAYOR RACHA DEL COFRE"),
    ("DIAS FELIZES SEGUIDOS", "HAPPY DAYS IN A ROW", "DÍAS FELICES SEGUIDOS"),
    ("FOTOS", "PHOTOS", "FOTOS"),
    ("{nome}  •  NÍVEL {n}", "{nome}  •  LEVEL {n}", "{nome}  •  NIVEL {n}"),
    ("NÍVEL MÁXIMO!", "MAX LEVEL!", "¡NIVEL MÁXIMO!"),
    ("DIA {n} DE VIDA", "DAY {n} OF LIFE", "DÍA {n} DE VIDA"),
    ("CONQUISTAS {n}/{total}", "ACHIEVEMENTS {n}/{total}", "LOGROS {n}/{total}"),
    ("COMPLETE E GANHE {n} OVOEDAS", "COMPLETE IT TO EARN {n} EGGCOINS", "COMPLÉTALA Y GANA {n} HUEVEDAS"),
    ("OVOEDAS GANHAS NA VIDA: {n}", "LIFETIME EGGCOINS: {n}", "HUEVEDAS DE TODA LA VIDA: {n}"),
    ("CORAÇÃO DOS PETS (carinho e vitórias enchem)", "PET HEARTS (pets and wins fill them up)",
     "CORAZÓN DE LAS MASCOTAS (mimos y victorias lo llenan)"),

    # --- Criador / nome ---
    ("OVO", "EGG", "HUEVO"),
    ("CABELO", "HAIR", "PELO"),
    ("OLHOS", "EYES", "OJOS"),
    ("BOCA", "MOUTH", "BOCA"),
    ("SORTEAR", "RANDOM", "AL AZAR"),
    ("PRONTO!", "DONE!", "¡LISTO!"),
    ("SALVAR", "SAVE", "GUARDAR"),
    ("{n} de {total}", "{n} of {total}", "{n} de {total}"),
    ("CRIE SEU OVO!", "MAKE YOUR EGG!", "¡CREA TU HUEVO!"),
    ("↑ ↓ escolhe   ← → troca   ENTER avança", "↑ ↓ select   ← → change   ENTER next",
     "↑ ↓ elige   ← → cambia   ENTER sigue"),
    ("   ESC volta", "   ESC back", "   ESC vuelve"),
    ("CONFIRMAR", "CONFIRM", "CONFIRMAR"),
    ("CANCELAR", "CANCEL", "CANCELAR"),
    ("JÁ TEM UM {nome} NA RUA!", "THERE'S ALREADY A {nome} ON THE STREET!", "¡YA HAY UN {nome} EN LA CALLE!"),
    ("BEM-VINDO AO", "WELCOME TO", "BIENVENIDO A"),
    ("Como vai se chamar o seu ovo?", "What will your egg be called?", "¿Cómo se llamará tu huevo?"),
    ("NOME DO NOVO OVO", "NEW EGG'S NAME", "NOMBRE DEL HUEVO"),
    ("ELE VAI MORAR NA CASA {n}", "IT WILL LIVE IN HOUSE {n}", "VIVIRÁ EN LA CASA {n}"),
    ("Como vai se chamar o novo ovo?", "What will the new egg be called?", "¿Cómo se llamará el huevo nuevo?"),
    ("Digite o novo nome:", "Type the new name:", "Escribe el nuevo nombre:"),
    ("ENTER confirma  •  ESC cancela", "ENTER confirms  •  ESC cancels", "ENTER confirma  •  ESC cancela"),
    ("Aperte ENTER para continuar", "Press ENTER to continue", "Pulsa ENTER para continuar"),

    # --- Loja ---
    ("< VOLTAR", "< BACK", "< VOLVER"),
    ("COMPRAR", "BUY", "COMPRAR"),
    ("COMPRAR  {n}", "BUY  {n}", "COMPRAR  {n}"),
    ("CHAPÉUS", "HATS", "SOMBREROS"),
    ("ROSTO", "FACE", "CARA"),
    ("CORPO", "BODY", "CUERPO"),
    ("VISUAL", "LOOK", "ESTILO"),
    ("EFEITOS", "EFFECTS", "EFECTOS"),
    ("PETS", "PETS", "MASCOTAS"),
    ("CASA", "HOME", "CASA"),
    ("QUINTAL", "YARD", "PATIO"),
    ("MERCADO", "MARKET", "MERCADO"),
    ("COR", "COLOR", "COLOR"),
    ("ROUPA", "OUTFIT", "ROPA"),
    ("COMUM", "COMMON", "COMÚN"),
    ("INCOMUM", "UNCOMMON", "POCO COMÚN"),
    ("RARO", "RARE", "RARO"),
    ("ÉPICO", "EPIC", "ÉPICO"),
    ("EPICO", "EPIC", "ÉPICO"),
    ("LENDÁRIO", "LEGENDARY", "LEGENDARIO"),
    ("LENDARIO", "LEGENDARY", "LEGENDARIO"),
    ("Aparece no seu ovo em TODOS os mini jogos!", "Shows up on your egg in ALL the mini games!",
     "¡Aparece en tu huevo en TODOS los minijuegos!"),
    ("Segue o seu ovo pela casa e comemora com você no fim dos jogos.",
     "Follows your egg around the house and cheers with you after games.",
     "Sigue a tu huevo por la casa y celebra contigo al final de los juegos."),
    ("Enfeita a casa. Clique nele para ver o que faz!", "Decorates the house. Click it to see what it does!",
     "Decora la casa. ¡Haz clic para ver qué hace!"),
    ("ENERGIA", "ENERGY", "ENERGÍA"),
    ("DIVERSÃO", "FUN", "DIVERSIÓN"),
    ("HIGIENE", "HYGIENE", "HIGIENE"),
    ("Plante no jardim do SOL. Fica pronta em {tempo}.", "Plant it in the SUN garden. Ready in {tempo}.",
     "Plántala en el jardín del SOL. Lista en {tempo}."),
    ("CAIXA SURPRESA", "MYSTERY BOX", "CAJA SORPRESA"),
    ("Um cosmético sorteado! Repetido vira OVOEDAS. Pode vir até exclusivo!",
     "A random cosmetic! Duplicates turn into EGGCOINS. Could even be exclusive!",
     "¡Un cosmético al azar! Los repetidos dan HUEVEDAS. ¡Puede salir uno exclusivo!"),
    ("OVOEDAS INSUFICIENTES!", "NOT ENOUGH EGGCOINS!", "¡FALTAN HUEVEDAS!"),
    ("{nome} COMPRADO!", "{nome} BOUGHT!", "¡{nome} COMPRADO!"),
    ("{nome} (REPETIDO): +{n} OVOEDAS", "{nome} (DUPLICATE): +{n} EGGCOINS", "{nome} (REPETIDO): +{n} HUEVEDAS"),
    ("CAIXA: {nome} ({raridade})!", "BOX: {nome} ({raridade})!", "¡CAJA: {nome} ({raridade})!"),
    ("CAIXA SURPRESA! (", "MYSTERY BOX! (", "¡CAJA SORPRESA! ("),
    ("QUER MUDAR A FACHADA? USE REFORMAR NA RUA DOS OVOS!", "NEW HOUSE LOOK? USE RENOVATE ON EGG STREET!",
     "¿CAMBIAR LA FACHADA? ¡USA REFORMAR EN LA CALLE!"),
    ("EM BREVE!", "COMING SOON!", "¡PRONTO!"),
    ("VOCÊ TEM: {n}", "YOU HAVE: {n}", "TIENES: {n}"),
    ("NADA AQUI AINDA", "NOTHING HERE YET", "NADA AQUÍ AÚN"),
    ("EM USO", "IN USE", "EN USO"),
    ("É SEU", "OWNED", "ES TUYO"),
    ("COMPRADO", "BOUGHT", "COMPRADO"),
    ("TIRAR", "REMOVE", "QUITAR"),
    ("EQUIPAR", "EQUIP", "EQUIPAR"),
    ("GUARDAR", "PUT AWAY", "GUARDAR"),
    ("USAR ESTE PET", "USE THIS PET", "USAR ESTA MASCOTA"),
    ("ESCONDER", "HIDE", "OCULTAR"),
    ("MOSTRAR", "SHOW", "MOSTRAR"),

    # --- Menu de jogos ---
    ("< CASA", "< HOME", "< CASA"),
    ("SOLO", "SOLO", "SOLO"),
    ("MINI JOGOS", "MINI GAMES", "MINIJUEGOS"),
    ("TAB troca de aba  •  ENTER joga  •  ESC volta", "TAB switch tab  •  ENTER play  •  ESC back",
     "TAB cambia pestaña  •  ENTER juega  •  ESC vuelve"),
    ("LIBERA NO NÍVEL {n} (VOCÊ ESTÁ NO {atual})", "UNLOCKS AT LEVEL {n} (YOU ARE LEVEL {atual})",
     "SE ABRE EN EL NIVEL {n} (ESTÁS EN EL {atual})"),
    ("OU COMPRE O INGRESSO AGORA:", "OR BUY A TICKET NOW:", "O COMPRA LA ENTRADA AHORA:"),
    ("{n}  LIBERAR", "{n}  UNLOCK", "{n}  ABRIR"),
    ("ENTER compra  •  ESC cancela", "ENTER buys  •  ESC cancels", "ENTER compra  •  ESC cancela"),
    ("NÍVEL {n}", "LEVEL {n}", "NIVEL {n}"),
    ("OU {n} OVOEDAS", "OR {n} EGGCOINS", "O {n} HUEVEDAS"),
    ("! DESAFIO", "! CHALLENGE", "! RETO"),
    ("★ J1 {a} × {b} J2", "★ P1 {a} × {b} P2", "★ J1 {a} × {b} J2"),
    ("NOVO!", "NEW!", "¡NUEVO!"),
    ("★ RECORDE: {valor}", "★ RECORD: {valor}", "★ RÉCORD: {valor}"),
    ("JOGO LIBERADO!", "GAME UNLOCKED!", "¡JUEGO DESBLOQUEADO!"),

    # --- Mudança ---
    ("TCHAU, CASA!", "BYE, HOUSE!", "¡ADIÓS, CASA!"),
    ("BI-BI!", "BEEP-BEEP!", "¡BIP-BIP!"),
    ("ENTER para pular", "ENTER to skip", "ENTER para saltar"),
    ("MUDANÇAS", "MOVERS", "MUDANZAS"),
    ("ATÉ LOGO, RUA DOS OVOS!", "SO LONG, EGG STREET!", "¡HASTA LUEGO, CALLE DE LOS HUEVOS!"),
    ("Todos os saves foram apagados.", "All saves were deleted.", "Se borraron todas las partidas."),
    ("Hora de chocar um ovo novinho!", "Time to hatch a brand-new egg!", "¡Hora de empollar un huevo nuevito!"),
    ("Alguns arquivos não puderam ser apagados.", "Some files couldn't be deleted.",
     "Algunos archivos no se pudieron borrar."),
    ("Feche o jogo e confira a pasta saves/.", "Close the game and check the saves/ folder.",
     "Cierra el juego y revisa la carpeta saves/."),
    ("APERTE ENTER PARA RECOMEÇAR", "PRESS ENTER TO START OVER", "PULSA ENTER PARA EMPEZAR"),

    # --- Reforma ---
    ("PAREDE", "WALLS", "PARED"),
    ("TELHADO", "ROOF", "TECHO"),
    ("PORTA", "DOOR", "PUERTA"),
    ("JANELAS", "WINDOWS", "VENTANAS"),
    ("CERCA", "FENCE", "CERCA"),
    ("CAMINHO", "PATH", "CAMINO"),
    ("CORREIO", "MAILBOX", "BUZÓN"),
    ("JARDIM", "GARDEN", "JARDÍN"),
    ("ENFEITE", "DECOR", "ADORNO"),
    ("FALTAM {n} OVOEDAS", "NEED {n} MORE EGGCOINS", "FALTAN {n} HUEVEDAS"),
    ("PEÇAS NÃO COMPRADAS FORAM TIRADAS", "UNBOUGHT PIECES WERE REMOVED", "SE QUITARON PIEZAS NO COMPRADAS"),
    ("ESTE TELHADO NÃO TEM CHAMINÉ", "THIS ROOF HAS NO CHIMNEY", "ESTE TECHO NO TIENE CHIMENEA"),
    ("← VOLTAR", "← BACK", "← VOLVER"),
    ("REFORMA", "RENOVATION", "REFORMA"),
    ("CASA DE ", "HOME OF ", "CASA DE "),
    ("PROVANDO", "TRYING ON", "PROBANDO"),
    ("VER DE DIA", "DAY VIEW", "VER DE DÍA"),
    ("VER DE NOITE", "NIGHT VIEW", "VER DE NOCHE"),
    ("ESQUERDA", "LEFT", "IZQUIERDA"),
    ("DIREITA", "RIGHT", "DERECHA"),
    ("NADA", "NONE", "NADA"),
    ("USANDO", "IN USE", "EN USO"),
    ("GRÁTIS", "FREE", "GRATIS"),
    ("TENHO", "OWNED", "LO TENGO"),
    ("CHAMINÉ: ", "CHIMNEY: ", "CHIMENEA: "),
    ("COR: ", "COLOR: ", "COLOR: "),
    ("As cores são grátis!", "Colors are free!", "¡Los colores son gratis!"),
    ("Deixar este lugar vazio.", "Leave this spot empty.", "Dejar este lugar vacío."),
    ("COMPRAR POR {n}", "BUY FOR {n}", "COMPRAR POR {n}"),
    ("FALTAM {n}", "NEED {n}", "FALTAN {n}"),
    ("USAR", "USE", "USAR"),
    ("COMPRAR {nome} POR {n}?", "BUY {nome} FOR {n}?", "¿COMPRAR {nome} POR {n}?"),

    # --- Vizinhança ---
    ("← → ESCOLHER • ENTER ENTRAR • R REFORMAR • ESC INÍCIO", "← → CHOOSE • ENTER GO IN • R RENOVATE • ESC TITLE",
     "← → ELEGIR • ENTER ENTRAR • R REFORMAR • ESC INICIO"),
    ("BEM-VINDO, {nome}!", "WELCOME, {nome}!", "¡BIENVENIDO, {nome}!"),
    ("OI! AQUI É {nome} DA CASA {casa}. FIZ {valor} NA {jogo}! DUVIDO VOCÊ PASSAR!",
     "HI! IT'S {nome} FROM HOUSE {casa}. I GOT {valor} IN {jogo}! BET YOU CAN'T BEAT IT!",
     "¡HOLA! SOY {nome} DE LA CASA {casa}. ¡HICE {valor} EN {jogo}! ¡A QUE NO ME GANAS!"),
    ("OI! AQUI É {nome}. ADOTEI UM PET: {pet}! VEM VER!", "HI! IT'S {nome}. I ADOPTED A PET: {pet}! COME SEE!",
     "¡HOLA! SOY {nome}. ¡ADOPTÉ UNA MASCOTA: {pet}! ¡VEN A VERLA!"),
    ("OI! {nome} PINTOU A CASA DE {cor}. FICOU LINDA!", "HI! {nome} PAINTED THE HOUSE {cor}. IT LOOKS GREAT!",
     "¡HOLA! {nome} PINTÓ LA CASA DE {cor}. ¡QUEDÓ PRECIOSA!"),
    ("OI, VIZINHO! AQUI É {nome} DA CASA {casa}. VAMOS JOGAR JUNTOS NO MODO 2 JOGADORES?",
     "HEY, NEIGHBOR! IT'S {nome} FROM HOUSE {casa}. WANNA PLAY TOGETHER IN 2-PLAYER MODE?",
     "¡HOLA, VECINO! SOY {nome} DE LA CASA {casa}. ¿JUGAMOS JUNTOS EN MODO 2 JUGADORES?"),
    ("ESTA CASA ESTÁ EM OBRAS", "THIS HOUSE IS UNDER REPAIR", "ESTA CASA ESTÁ EN OBRAS"),
    ("TCHAU!", "BYE!", "¡ADIÓS!"),
    ("NÃO DEU PARA APAGAR", "COULDN'T DELETE IT", "NO SE PUDO BORRAR"),
    ("BANDEIRINHAS", "BUNTING", "BANDERITAS"),
    ("LAMPIÕES", "LANTERNS", "FAROLES"),
    ("ESTÁTUA DO OVO DOURADO", "GOLDEN EGG STATUE", "ESTATUA DEL HUEVO DORADO"),
    ("ARCO DE FLORES", "FLOWER ARCH", "ARCO DE FLORES"),
    ("FOGOS TODA NOITE", "NIGHTLY FIREWORKS", "FUEGOS CADA NOCHE"),
    ("VILA NÍVEL {n}", "VILLAGE LV {n}", "VILLA NIVEL {n}"),
    ("NÍVEL {n}: {marco}", "LEVEL {n}: {marco}", "NIVEL {n}: {marco}"),
    ("CASA {n} • LIVRE", "HOUSE {n} • EMPTY", "CASA {n} • LIBRE"),
    ("EM OBRAS", "UNDER REPAIR", "EN OBRAS"),
    ("ENTRAR", "GO IN", "ENTRAR"),
    ("REFORMAR", "RENOVATE", "REFORMAR"),
    ("+NOVO", "+NEW", "+NUEVO"),
    ("CASA LIVRE! CLIQUE EM +NOVO PARA TER UM OVO AQUI.", "EMPTY HOUSE! CLICK +NEW TO GET AN EGG HERE.",
     "¡CASA LIBRE! HAZ CLIC EN +NUEVO PARA TENER UN HUEVO AQUÍ."),
    ("ESTA CASA ESTÁ EM OBRAS (O ARQUIVO DO OVO ESTÁ ESTRAGADO).",
     "THIS HOUSE IS UNDER REPAIR (THE EGG'S FILE IS BROKEN).",
     "ESTA CASA ESTÁ EN OBRAS (EL ARCHIVO DEL HUEVO ESTÁ DAÑADO)."),
    ("PET: ", "PET: ", "MASCOTA: "),
    ("← INÍCIO", "← TITLE", "← INICIO"),
    ("RUA DOS OVOS", "EGG STREET", "CALLE HUEVOS"),
    ("BEM-VINDO À RUA DOS OVOS! SUA CASA É A 1. CLIQUE EM +NOVO PARA TER MAIS OVOS.",
     "WELCOME TO EGG STREET! YOUR HOUSE IS #1. CLICK +NEW TO GET MORE EGGS.",
     "¡BIENVENIDO A LA CALLE DE LOS HUEVOS! TU CASA ES LA 1. HAZ CLIC EN +NUEVO PARA TENER MÁS."),
    ("ESTE OVO", "THIS EGG", "ESTE HUEVO"),
    ("APAGAR ESTE OVO?", "DELETE THIS EGG?", "¿BORRAR ESTE HUEVO?"),
    ("{nome} VAI SE MUDAR PARA SEMPRE. AS OVOEDAS, ROUPAS, PETS, PLANTAS E RECORDES DELE VÃO JUNTO.",
     "{nome} WILL MOVE AWAY FOREVER. ITS EGGCOINS, CLOTHES, PETS, PLANTS AND RECORDS GO TOO.",
     "{nome} SE MUDARÁ PARA SIEMPRE. SUS HUEVEDAS, ROPA, MASCOTAS, PLANTAS Y RÉCORDS SE VAN CON ÉL."),
    ("NÃO, FICA!", "NO, STAY!", "¡NO, QUÉDATE!"),
    ("SIM, APAGAR", "YES, DELETE", "SÍ, BORRAR"),
    ("ESC = NÃO", "ESC = NO", "ESC = NO"),
    ("TEM CERTEZA MESMO?", "ARE YOU REALLY SURE?", "¿DE VERDAD ESTÁS SEGURO?"),
    ("SE VOCÊ NÃO É O DONO DESTE OVO, PEÇA PARA UM ADULTO. SEGURE O BOTÃO VERMELHO POR 3 SEGUNDOS.",
     "IF THIS ISN'T YOUR EGG, ASK A GROWN-UP. HOLD THE RED BUTTON FOR 3 SECONDS.",
     "SI ESTE HUEVO NO ES TUYO, PIDE AYUDA A UN ADULTO. MANTÉN EL BOTÓN ROJO 3 SEGUNDOS."),
    ("SEGURE PARA APAGAR", "HOLD TO DELETE", "MANTÉN PARA BORRAR"),
    ("CARTA DE ", "LETTER FROM ", "CARTA DE "),
    ("CLIQUE PARA FECHAR", "CLICK TO CLOSE", "CLIC PARA CERRAR"),
]

EN = {pt: en for pt, en, _ in _T}
ES = {pt: es for pt, _, es in _T}
