# Traduções gerais: main.py, tela inicial (cenas/titulo.py), pausa,
# opções e tela de idioma. Chave = texto ORIGINAL em português.
# (Guia completo no topo de core/idioma.py.)

EN = {
    # --- Tela inicial ---
    "JOGAR": "PLAY",
    "OPÇÕES": "OPTIONS",
    "SAIR": "QUIT",
    "ENTER = JOGAR": "ENTER = PLAY",
    "A VIZINHANÇA DOS OVOS": "THE EGG NEIGHBORHOOD",

    # --- main.py ---
    "Você ficou fora {n} DIA(S)!": "You were away {n} DAY(S)!",
    "Você ficou fora {n}h!": "You were away {n}h!",
    "{n} PLANTA(S) PRONTA(S) NO JARDIM": "{n} PLANT(S) READY IN THE GARDEN",
    "O BAÚ DO DIA ESTÁ ESPERANDO": "THE DAILY CHEST IS WAITING",
    "{n} CARTA(S) NOVA(S) NA CAIXA DO CORREIO": "{n} NEW LETTER(S) IN THE MAILBOX",
    "MISSÕES NOVAS COM O ROBERT": "NEW MISSIONS WITH ROBERT",
    "O OVO ESTÁ COM {lista}!": "THE EGG FEELS {lista}!",
    "FOME": "HUNGRY",
    "SONO": "SLEEPY",
    "TÉDIO": "BORED",
    "SUJEIRA": "DIRTY",
    "OPS!": "OOPS!",
    "NÃO DEU PARA SALVAR A FOTO": "COULDN'T SAVE THE PHOTO",
    "FOTO SALVA!": "PHOTO SAVED!",

    # --- Pausa ---
    "PAUSADO": "PAUSED",
    "CONTINUAR": "CONTINUE",
    "CONQUISTAS": "ACHIEVEMENTS",
    "AMIGOS": "FRIENDS",
    "VIZINHANÇA": "NEIGHBORHOOD",
    "LOJA": "SHOP",
    "TROCAR APARÊNCIA": "CHANGE LOOK",
    "TROCAR NOME": "CHANGE NAME",
    "SAIR DO JOGO": "QUIT GAME",
    "ESC para voltar": "ESC to go back",

    # --- Opções ---
    "MÚSICA: {v}%": "MUSIC: {v}%",
    "MÚSICA: DESLIGADA": "MUSIC: OFF",
    "EFEITOS: {v}%": "SOUND FX: {v}%",
    "EFEITOS: DESLIGADOS": "SOUND FX: OFF",
    "TELA: {w}x{h}": "SCREEN: {w}x{h}",
    "SEMPRE DIA: SIM": "ALWAYS DAY: YES",
    "SEMPRE DIA: NÃO (RELÓGIO)": "ALWAYS DAY: NO (CLOCK)",
    "TELA CHEIA (F11)": "FULLSCREEN (F11)",
    "TREMOR DA TELA: {v}": "SCREEN SHAKE: {v}",
    "REDUZIDO": "REDUCED",
    "NORMAL": "NORMAL",
    "MOSTRAR FPS: {v}": "SHOW FPS: {v}",
    "SIM": "YES",
    "NÃO": "NO",
    "CORES DAS BARRAS: {v}": "BAR COLORS: {v}",
    "DALTÔNICO": "COLORBLIND",
    "PADRÃO": "DEFAULT",
    "IDIOMA: {v}": "LANGUAGE: {v}",
    "RECOMEÇAR DO ZERO": "START OVER",
    "VOLTAR": "BACK",
    "Dica: arraste a borda da janela para redimensionar": "Tip: drag the window edge to resize",
    "RECOMEÇAR DO ZERO?": "START OVER?",
    "TODOS os ovos, casas, moedas, recordes,": "ALL eggs, houses, coins, records,",
    "conquistas e preferências serão APAGADOS.": "achievements and settings will be ERASED.",
    "Os ovos vão se mudar da rua. Não dá para desfazer!": "The eggs will move away. This can't be undone!",
    "NÃO, VOLTAR": "NO, GO BACK",
    "SIM, APAGAR TUDO": "YES, ERASE ALL",

    # --- Tela de idioma ---
    "SETAS + ENTER  •  ESC para voltar": "ARROWS + ENTER  •  ESC to go back",
    "SETAS + ENTER": "ARROWS + ENTER",
}

ES = {
    # --- Tela inicial ---
    "JOGAR": "JUGAR",
    "OPÇÕES": "OPCIONES",
    "SAIR": "SALIR",
    "ENTER = JOGAR": "ENTER = JUGAR",
    "A VIZINHANÇA DOS OVOS": "EL BARRIO DE LOS HUEVOS",

    # --- main.py ---
    "Você ficou fora {n} DIA(S)!": "¡Estuviste fuera {n} DÍA(S)!",
    "Você ficou fora {n}h!": "¡Estuviste fuera {n}h!",
    "{n} PLANTA(S) PRONTA(S) NO JARDIM": "{n} PLANTA(S) LISTA(S) EN EL JARDÍN",
    "O BAÚ DO DIA ESTÁ ESPERANDO": "EL COFRE DEL DÍA TE ESPERA",
    "{n} CARTA(S) NOVA(S) NA CAIXA DO CORREIO": "{n} CARTA(S) NUEVA(S) EN EL BUZÓN",
    "MISSÕES NOVAS COM O ROBERT": "NUEVAS MISIONES CON ROBERT",
    "O OVO ESTÁ COM {lista}!": "¡EL HUEVO TIENE {lista}!",
    "FOME": "HAMBRE",
    "SONO": "SUEÑO",
    "TÉDIO": "ABURRIMIENTO",
    "SUJEIRA": "SUCIEDAD",
    "OPS!": "¡UPS!",
    "NÃO DEU PARA SALVAR A FOTO": "NO SE PUDO GUARDAR LA FOTO",
    "FOTO SALVA!": "¡FOTO GUARDADA!",

    # --- Pausa ---
    "PAUSADO": "PAUSA",
    "CONTINUAR": "CONTINUAR",
    "CONQUISTAS": "LOGROS",
    "AMIGOS": "AMIGOS",
    "VIZINHANÇA": "BARRIO",
    "LOJA": "TIENDA",
    "TROCAR APARÊNCIA": "CAMBIAR ASPECTO",
    "TROCAR NOME": "CAMBIAR NOMBRE",
    "SAIR DO JOGO": "SALIR DEL JUEGO",
    "ESC para voltar": "ESC para volver",

    # --- Opções ---
    "MÚSICA: {v}%": "MÚSICA: {v}%",
    "MÚSICA: DESLIGADA": "MÚSICA: APAGADA",
    "EFEITOS: {v}%": "EFECTOS: {v}%",
    "EFEITOS: DESLIGADOS": "EFECTOS: APAGADOS",
    "TELA: {w}x{h}": "PANTALLA: {w}x{h}",
    "SEMPRE DIA: SIM": "SIEMPRE DÍA: SÍ",
    "SEMPRE DIA: NÃO (RELÓGIO)": "SIEMPRE DÍA: NO (RELOJ)",
    "TELA CHEIA (F11)": "PANTALLA COMPLETA (F11)",
    "TREMOR DA TELA: {v}": "TEMBLOR: {v}",
    "REDUZIDO": "REDUCIDO",
    "NORMAL": "NORMAL",
    "MOSTRAR FPS: {v}": "MOSTRAR FPS: {v}",
    "SIM": "SÍ",
    "NÃO": "NO",
    "CORES DAS BARRAS: {v}": "COLORES BARRAS: {v}",
    "DALTÔNICO": "DALTÓNICO",
    "PADRÃO": "NORMAL",
    "IDIOMA: {v}": "IDIOMA: {v}",
    "RECOMEÇAR DO ZERO": "EMPEZAR DE CERO",
    "VOLTAR": "VOLVER",
    "Dica: arraste a borda da janela para redimensionar": "Consejo: arrastra el borde de la ventana",
    "RECOMEÇAR DO ZERO?": "¿EMPEZAR DE CERO?",
    "TODOS os ovos, casas, moedas, recordes,": "TODOS los huevos, casas, monedas, récords,",
    "conquistas e preferências serão APAGADOS.": "logros y ajustes serán BORRADOS.",
    "Os ovos vão se mudar da rua. Não dá para desfazer!": "Los huevos se mudarán. ¡No se puede deshacer!",
    "NÃO, VOLTAR": "NO, VOLVER",
    "SIM, APAGAR TUDO": "SÍ, BORRAR TODO",

    # --- Tela de idioma ---
    "SETAS + ENTER  •  ESC para voltar": "FLECHAS + ENTER  •  ESC para volver",
    "SETAS + ENTER": "FLECHAS + ENTER",
}
