# Traducoes (ver o guia em core/idioma.py). Chave = texto ORIGINAL em portugues.
# Dados de core/*.py: itens, cosmeticos, moveis, pets, conquistas,
# fachada, eventos, trilhas, necessidades + textos desenhados pelo core.

EN = {
    # --- Raridades / cômodos / necessidades ---
    "COMUM": "COMMON", "INCOMUM": "UNCOMMON", "RARO": "RARE",
    "EPICO": "EPIC", "ÉPICO": "EPIC", "LENDARIO": "LEGENDARY", "LENDÁRIO": "LEGENDARY",
    "CASA": "HOUSE", "SOL": "YARD",
    "FOME": "HUNGER", "ENERGIA": "ENERGY", "DIVERSÃO": "FUN", "HIGIENE": "HYGIENE",
    "60 OVOEDAS": "60 EGGCOINS", "100 OVOEDAS": "100 EGGCOINS", "+15 OVOEDAS": "+15 EGGCOINS",

    # --- Comidas / sementes / plantas / poções ---
    "LIMÃO": "LEMON", "MAÇÃ": "APPLE", "BANANA": "BANANA", "LEITE": "MILK",
    "PÃO DE QUEIJO": "CHEESE BREAD", "SUCO DE LIMÃO": "LEMONADE",
    "SANDUÍCHE": "SANDWICH", "SORVETE": "ICE CREAM", "PIZZA": "PIZZA",
    "BOLO": "CAKE", "PIMENTA": "CHILI PEPPER", "MORANGO": "STRAWBERRY",
    "MARSHMALLOW": "MARSHMALLOW", "ABÓBORA GIGANTE": "GIANT PUMPKIN",
    "CENOURA": "CARROT", "PIPOCA": "POPCORN", "BRIGADEIRO": "FUDGE BALL",
    "MELANCIA": "WATERMELON",
    "SEMENTE DE LIMÃO": "LEMON SEED", "LIMOEIRO": "LEMON TREE",
    "SEMENTE DE MORANGO": "STRAWBERRY SEED", "MORANGUEIRO": "STRAWBERRY PLANT",
    "SEMENTE DE GIRASSOL": "SUNFLOWER SEED", "GIRASSOL": "SUNFLOWER",
    "SEMENTE DE ABÓBORA": "PUMPKIN SEED", "SEMENTE DE OVOEDAS": "EGGCOIN SEED",
    "ÁRVORE DE OVOEDAS": "EGGCOIN TREE", "SEMENTE DE MELANCIA": "WATERMELON SEED",
    "BROTO": "SPROUT", "MUDA": "SEEDLING", "PLANTA": "PLANT", "PRONTA": "READY",
    "POÇÃO DO SONO": "SLEEP POTION", "POÇÃO DA ALEGRIA": "JOY POTION",
    "POÇÃO DE ESPUMA": "BUBBLE POTION", "ELIXIR TOTAL": "TOTAL ELIXIR",
    "POÇÃO DA SORTE": "LUCK POTION", "POÇÃO DE XP": "XP POTION",
    "OVOEDAS x1,5 nas próximas 3 partidas.": "EGGCOINS x1.5 for the next 3 games.",
    "XP em DOBRO por 15 minutos.": "DOUBLE XP for 15 minutes.",

    # --- Cosméticos ---
    "BONÉ VERMELHO": "RED CAP", "GORRO DE LÃ": "WOOL BEANIE", "LAÇO DE FITA": "RIBBON BOW",
    "FLOR NO CABELO": "HAIR FLOWER", "ORELHAS DE GATO": "CAT EARS",
    "CHAPÉU DE CHEF": "CHEF HAT", "CARTOLA": "TOP HAT", "CHAPÉU PIRATA": "PIRATE HAT",
    "CHAPÉU DE MAGO": "WIZARD HAT", "CHIFRE DE UNICÓRNIO": "UNICORN HORN",
    "AURÉOLA": "HALO", "COROA REAL": "ROYAL CROWN", "CAPACETE ESPACIAL": "SPACE HELMET",
    "BOCHECHAS ROSADAS": "ROSY CHEEKS", "TAPA-OLHO": "EYE PATCH",
    "ÓCULOS DE NERD": "NERD GLASSES", "BIGODÃO": "BIG MUSTACHE",
    "ÓCULOS DO SOL": "SUNGLASSES", "ÓCULOS DE CORAÇÃO": "HEART GLASSES",
    "MÁSCARA DE HERÓI": "HERO MASK", "GRAVATA-BORBOLETA": "BOW TIE",
    "CACHECOL LISTRADO": "STRIPED SCARF", "COLAR HAVAIANO": "HAWAIIAN LEI",
    "MEDALHA DE OURO": "GOLD MEDAL", "BOIA DE PATINHO": "DUCKY FLOAT",
    "CAPA DE HERÓI": "HERO CAPE", "ASAS DE ANJO": "ANGEL WINGS",
    "NUVENZINHA DE CHUVA": "LITTLE RAIN CLOUD", "NOTAS MUSICAIS": "MUSIC NOTES",
    "ESTRELINHAS": "TWINKLES", "CORAÇÕES": "HEARTS", "AURA DOURADA": "GOLDEN AURA",
    "ASAS DE BORBOLETA": "BUTTERFLY WINGS",
    "CHAPÉU DE PALHA": "STRAW HAT", "CAPACETE DE OBRA": "HARD HAT",
    "FONES DE OUVIDO": "HEADPHONES", "TOUCA DE DINOSSAURO": "DINO HOOD",
    "NINHO COM PASSARINHO": "BIRD NEST", "SARDAS": "FRECKLES", "ÓCULOS 3D": "3D GLASSES",
    "MONÓCULO": "MONOCLE", "AVENTAL DE JARDIM": "GARDEN APRON", "MOCHILA": "BACKPACK",
    "CAPA DE CHUVA": "RAINCOAT", "MOCHILA-FOGUETE": "JETPACK",
    "BOLHAS DE SABÃO": "SOAP BUBBLES", "VAGALUMES": "FIREFLIES", "ARCO-ÍRIS": "RAINBOW",

    # --- Visual extra (cabelo, olhos, boca, cor, roupa) ---
    "CABELO": "HAIR", "OLHOS": "EYES", "BOCA": "MOUTH", "COR": "COLOR", "ROUPA": "OUTFIT",
    "Troca o cabelo do seu ovo em todos os jogos!": "Changes your egg's hair in every game!",
    "Troca os olhos do seu ovo em todos os jogos!": "Changes your egg's eyes in every game!",
    "Troca a boca do seu ovo em todos os jogos!": "Changes your egg's mouth in every game!",
    "Pinta o seu ovo de uma cor nova em todos os jogos!": "Paints your egg a new color in every game!",
    "Uma roupa nova para o seu ovo usar em todos os jogos!": "A new outfit for your egg in every game!",
    "TOPETE": "QUIFF", "FRANJINHA": "BANGS", "COQUE": "BUN", "RABO DE CAVALO": "PONYTAIL",
    "MARIA-CHIQUINHA": "PIGTAILS", "BLACK POWER": "AFRO", "MOICANO PUNK": "PUNK MOHAWK",
    "CACHINHOS DOURADOS": "GOLDEN CURLS", "CABELO DE FOGO": "FIRE HAIR",
    "CABELO ARCO-ÍRIS": "RAINBOW HAIR",
    "OLHINHOS DE BOLINHA": "DOT EYES", "OLHOS SONOLENTOS": "SLEEPY EYES",
    "CÍLIOS LONGOS": "LONG LASHES", "OLHOS BRILHANTES": "SPARKLY EYES",
    "OLHOS DE GATO": "CAT EYES", "OLHOS APAIXONADOS": "LOVESTRUCK EYES",
    "OLHOS HIPNÓTICOS": "HYPNO EYES", "OLHOS DE ROBÔ": "ROBOT EYES",
    "OLHOS DE GALÁXIA": "GALAXY EYES", "OLHOS DE ESTRELA": "STAR EYES",
    "SORRISÃO": "BIG SMILE", "BOQUINHA DE GATO": "CAT MOUTH", "ASSOBIANDO": "WHISTLING",
    "BATOM VERMELHO": "RED LIPSTICK", "PRESINHAS DE VAMPIRO": "VAMPIRE FANGS",
    "APARELHO NOS DENTES": "BRACES", "PIRULITO": "LOLLIPOP", "DENTE DE OURO": "GOLD TOOTH",
    "BOLA DE CHICLETE": "BUBBLEGUM", "SORRISO DE DIAMANTE": "DIAMOND SMILE",
    "ROSA CHICLETE": "BUBBLEGUM PINK", "LARANJA": "ORANGE", "AMARELO GEMA": "YOLK YELLOW",
    "VERDE MENTA": "MINT GREEN", "OVO DE CODORNA": "QUAIL EGG", "CHOCOLATE": "CHOCOLATE",
    "PRETO NOITE": "NIGHT BLACK", "DOURADO": "GOLDEN", "GALÁXIA": "GALAXY",
    "ABÓBORA DE HALLOWEEN": "JACK-O'-LANTERN",
    "CAMISETA LISTRADA": "STRIPED TEE", "MACACÃO JEANS": "DENIM OVERALLS",
    "CAMISA DE FUTEBOL": "SOCCER JERSEY", "VESTIDO DE BOLINHAS": "POLKA DOT DRESS",
    "MOLETOM COM CAPUZ": "HOODIE", "QUIMONO DE KARATÊ": "KARATE GI",
    "TERNO ELEGANTE": "FANCY SUIT", "TRAJE DE ASTRONAUTA": "ASTRONAUT SUIT",
    "ARMADURA DE CAVALEIRO": "KNIGHT ARMOR", "MANTO REAL": "ROYAL CLOAK",
    "SUÉTER DE NATAL": "HOLIDAY SWEATER", "GORRO DE NATAL": "SANTA HAT",
    "CHAPÉU DE BRUXA": "WITCH HAT", "ORELHAS DE COELHO DE PÁSCOA": "EASTER BUNNY EARS",

    # --- Cores (fachada / assets) ---
    "AZUL": "BLUE", "BRANCO": "WHITE", "VERDE": "GREEN", "VERMELHO": "RED",
    "AMARELO": "YELLOW", "CREME": "CREAM", "PÊSSEGO": "PEACH", "LILÁS": "LILAC",
    "ROSA": "PINK", "CINZA": "GRAY", "MENTA": "MINT", "COR DO OVO": "EGG COLOR",
    "TELHA": "TERRACOTTA", "MARROM": "BROWN", "PRETO": "BLACK", "ROXO": "PURPLE",
    "MADEIRA": "WOOD", "VERMELHA": "RED", "AMARELA": "YELLOW", "BRANCA": "WHITE",
    "PRETA": "BLACK", "ROXA": "PURPLE",

    # --- Fachada ---
    "LISO": "PLAIN", "Parede lisinha, do jeito que veio.": "A plain wall, just as it came.",
    "Tábuas de madeira com preguinhos.": "Wooden planks with little nails.",
    "LISTRAS": "STRIPES", "Listras verticais animadas.": "Cheerful vertical stripes.",
    "BOLINHAS": "POLKA DOTS", "Bolinhas por toda a parede.": "Polka dots all over the wall.",
    "TIJOLINHO": "BRICK", "Tijolinho à vista, charmoso.": "Charming exposed brick.",
    "PEDRA DE CASTELO": "CASTLE STONE", "Pedras grandes de castelo.": "Big castle stones.",
    "TRIÂNGULO": "TRIANGLE", "O telhado clássico.": "The classic roof.",
    "TELHAS DE ESCAMA": "SCALE SHINGLES", "Telhas redondinhas como escamas.": "Round shingles like fish scales.",
    "TELHADO DE PALHA": "THATCHED ROOF", "Palha fofinha de casa de campo.": "Fluffy country-house thatch.",
    "TELHADO COGUMELO": "MUSHROOM ROOF", "Um cogumelo gigante de bolinhas.": "A giant polka-dot mushroom.",
    "RETA": "STRAIGHT", "Porta simples de madeira.": "A simple wooden door.",
    "PORTA EM ARCO": "ARCHED DOOR", "Porta com o topo arredondado.": "A door with a rounded top.",
    "PORTA REDONDA": "ROUND DOOR", "Porta redonda de toca.": "A round burrow door.",
    "PORTA DE OVO": "EGG DOOR", "Porta em forma de ovo, com moldura dourada.": "Egg-shaped door with a gold frame.",
    "QUADRADA": "SQUARE", "Janelas quadradas com cruz.": "Square windows with a cross.",
    "JANELAS REDONDAS": "ROUND WINDOWS", "Janelas redondas de navio.": "Round ship windows.",
    "JANELAS EM ARCO": "ARCHED WINDOWS", "Janelas com o topo em arco.": "Windows with an arched top.",
    "JANELAS COM FLOREIRA": "FLOWER BOX WINDOWS", "Uma floreira embaixo de cada janela.": "A flower box under each window.",
    "JANELAS DE CORAÇÃO": "HEART WINDOWS", "Janelas de coração que brilham à noite.": "Heart windows that glow at night.",
    "SEM CERCA": "NO FENCE", "Nada de cerca.": "No fence at all.",
    "CERCA RÚSTICA": "RUSTIC FENCE", "Estacas de madeira com arame.": "Wooden stakes with wire.",
    "CERCA BRANCA": "WHITE PICKET", "A cerquinha branca dos sonhos.": "The white picket fence of your dreams.",
    "CERCA-VIVA": "HEDGE", "Arbustos com florzinhas.": "Bushes with tiny flowers.",
    "GRADE DE FERRO": "IRON FENCE", "Grade elegante com pontas de lança.": "Elegant fence with spear tips.",
    "CAIXA PADRÃO": "STANDARD BOX", "Caixa de correio azul.": "A blue mailbox.",
    "CAIXA DE CORREIO OVO": "EGG MAILBOX", "Uma caixa de correio em forma de ovo.": "An egg-shaped mailbox.",
    "TERRA": "DIRT", "Caminho de terra batida.": "A packed dirt path.",
    "PEDRINHAS": "PEBBLES", "Pedrinhas no meio da grama.": "Pebbles in the grass.",
    "TIJOLOS": "BRICKS", "Caminho de tijolos.": "A brick path.",
    "TAPETE VERMELHO": "RED CARPET", "Para entrar como uma estrela.": "Walk in like a star.",
    "CAMINHO ARCO-ÍRIS": "RAINBOW PATH", "Um caminho com todas as cores.": "A path with every color.",
    "VASO DE FLOR": "FLOWER POT", "Presente de mudança. Flores que dançam no vento.": "Housewarming gift. Flowers that dance in the wind.",
    "CACTO": "CACTUS", "Espinhento, mas fofo.": "Prickly, but cute.",
    "FLAMINGO DE JARDIM": "LAWN FLAMINGO", "Um flamingo cor-de-rosa numa perna só.": "A pink flamingo on one leg.",
    "ANÃO DE JARDIM": "GARDEN GNOME", "Ele pisca quando ninguém está olhando.": "He winks when no one is looking.",
    "JARDIM DE FLORES": "FLOWER BED", "Uma caixa cheia de flores.": "A box full of flowers.",
    "CASINHA DE PASSARINHO": "BIRDHOUSE", "Um passarinho azul mora aqui.": "A little bluebird lives here.",
    "ABÓBORA-LANTERNA": "JACK-O'-LANTERN", "O rosto brilha à noite.": "Its face glows at night.",
    "POSTE DE LUZ": "LAMPPOST", "Ilumina a calçada à noite.": "Lights the sidewalk at night.",
    "BANCO DE JARDIM": "GARDEN BENCH", "O ovo senta nele para ver a rua.": "The egg sits here to watch the street.",
    "ÁRVORE FRONDOSA": "LEAFY TREE", "Uma árvore com frutinhas vermelhas.": "A tree with little red berries.",
    "BICICLETA": "BICYCLE", "Na cor do seu ovo. TRIM!": "In your egg's color. RING RING!",
    "ARBUSTO EM FORMA DE OVO": "EGG-SHAPED BUSH", "Podado com muito carinho.": "Trimmed with lots of love.",
    "ESPANTALHO": "SCARECROW", "Espanta os corvos (quase sempre).": "Scares off crows (mostly).",
    "FONTE DE JARDIM": "GARDEN FOUNTAIN", "Uma fontezinha que não para de jorrar.": "A little fountain that never stops.",
    "ANTENA DE TV": "TV ANTENNA", "Pega todos os canais de desenho.": "Gets every cartoon channel.",
    "BANDEIRA": "FLAG", "Uma bandeira na cor do seu ovo.": "A flag in your egg's color.",
    "BALÕES": "BALLOONS", "Três balões presos na chaminé.": "Three balloons tied to the chimney.",
    "GALO CATA-VENTO": "ROOSTER VANE", "Gira mais rápido quando venta.": "Spins faster when it's windy.",
    "PISCA-PISCA": "TWINKLE LIGHTS", "Luzinhas que piscam à noite.": "Little lights that blink at night.",
    "PAINEL SOLAR": "SOLAR PANEL", "Energia limpa do sol.": "Clean energy from the sun.",
    "GATO NO TELHADO": "ROOF CAT", "Um gato laranja dorminhoco. MIAU!": "A sleepy orange cat. MEOW!",
    "+NOVO": "+NEW",

    # --- Móveis ---
    "GELADEIRA": "FRIDGE", "Guarda as comidas do ovo.": "Keeps the egg's food.",
    "INTERRUPTOR": "LIGHT SWITCH", "Apaga a luz para o ovo dormir.": "Turns off the light so the egg can sleep.",
    "TAPETE REDONDO": "ROUND RUG", "Um tapete fofinho para a sala.": "A fluffy rug for the living room.",
    "PLANTA NO VASO": "POTTED PLANT", "Balança as folhas quando você mexe nela.": "Wiggles its leaves when you touch it.",
    "LÂMPADA DE LAVA": "LAVA LAMP", "Bolhas coloridas que brilham no escuro.": "Colorful blobs that glow in the dark.",
    "RETRATO DO OVO": "EGG PORTRAIT", "Uma foto sua! Clique para trocar o fundo.": "A photo of you! Click to change the background.",
    "RELÓGIO CUCO": "CUCKOO CLOCK", "Mostra a hora de verdade. CUCO!": "Shows the real time. CUCKOO!",
    "VITROLA": "JUKEBOX", "Toca as músicas dos jogos que você já jogou.": "Plays songs from games you've played.",
    "ESTANTE DE TROFÉUS": "TROPHY SHELF", "Mostra os troféus que você ganhou nos jogos.": "Shows the trophies you won in games.",
    "TELEVISÃO": "TV", "4 canais! Assistir deixa o ovo feliz.": "4 channels! Watching makes the egg happy.",
    "AQUÁRIO": "AQUARIUM", "Três peixinhos. Dê ração para eles!": "Three little fish. Feed them!",
    "CAMA": "BED", "Dormir na cama recupera energia 2x mais rápido.": "Sleeping in bed restores energy 2x faster.",
    "CANTEIRO EXTRA": "EXTRA GARDEN BED", "Mais um canteiro para plantar.": "One more bed to plant in.",
    "CATA-VENTO": "PINWHEEL", "Gira com o vento. Clique para soprar!": "Spins in the wind. Click to blow!",
    "CASINHA DO PET": "PET HOUSE", "O seu pet dorme nela à noite.": "Your pet sleeps in it at night.",
    "PISCINA INFLÁVEL": "KIDDIE POOL", "Banho divertido: limpa e diverte.": "Fun bath: cleans and entertains.",
    "VARAL DE LUZES": "STRING LIGHTS", "Luzinhas coloridas que acendem à noite.": "Colorful lights that turn on at night.",
    "TELESCÓPIO": "TELESCOPE", "À noite, pegue uma estrela cadente!": "At night, catch a shooting star!",
    "ÁRVORE COM BALANÇO": "TREE SWING", "O ovo senta e balança. Uhuuu!": "The egg sits and swings. Wheee!",
    "CORTINAS": "CURTAINS", "Fecham sozinhas quando o ovo dorme.": "They close by themselves when the egg sleeps.",
    "QUADRO DA VIZINHANÇA": "NEIGHBORHOOD MAP", "A sua rua em miniatura, com as casas dos vizinhos.": "Your street in miniature, with the neighbors' houses.",
    "PIPA": "KITE", "Voa no céu do quintal. Clique para dar um looping!": "Flies over the yard. Click to do a loop!",
    "FOGUEIRA": "CAMPFIRE", "Acende no fim do dia. Ficar pertinho diverte o ovo.": "Lights up at dusk. Staying close is fun for the egg.",
    # textos desenhados pelos móveis
    "GELADEIRA: COMIDA": "FRIDGE: FOOD", "ACENDER A LUZ": "TURN ON LIGHT",
    "APAGAR A LUZ": "TURN OFF LIGHT", "CUCO!": "CUCKOO!", "JUKEBOX": "JUKEBOX",
    "TROFÉUS": "TROPHIES", "GANHE TROFÉUS NOS MINI JOGOS!": "WIN TROPHIES IN MINIGAMES!",
    "DESLIGADA": "OFF", "ROBERT SHOW": "ROBERT SHOW", "DESENHO": "CARTOONS",
    "CHUVISCO": "STATIC", "RECORDES": "RECORDS",
    "JOGUE OS MINI JOGOS!": "PLAY THE MINIGAMES!", "TV DESLIGADA": "TV OFF",
    "CANAL {n}: {nome}": "CHANNEL {n}: {nome}", "CH {n}": "CH {n}",
    "OI OVO!   OI OVO!": "HI EGG!   HI EGG!", "DAR RAÇÃO AOS PEIXES": "FEED THE FISH",
    "DORMIR NA CAMA": "SLEEP IN BED", "CASINHA DO {nome}": "{nome}'S HOUSE",
    "SÓ À NOITE!": "NIGHT ONLY!", "CONSTELAÇÃO DO OVO": "EGG CONSTELLATION",
    "Espere uma estrela cadente...": "Wait for a shooting star...",
    "DESEJO REALIZADO!": "WISH GRANTED!", "VOLTAR": "BACK",
    "OLHAR AS ESTRELAS": "STARGAZE", "TELESCÓPIO: SÓ À NOITE": "TELESCOPE: NIGHT ONLY",
    "BALANÇAR": "SWING",
    "CORTINAS: clique para abrir/fechar": "CURTAINS: click to open/close",
    "VIZINHOS: {lista}": "NEIGHBORS: {lista}", "NENHUM VIZINHO AINDA": "NO NEIGHBORS YET",
    "PIPA: guardada por causa da chuva": "KITE: put away because of the rain",
    "PIPA: clique para dar um looping!": "KITE: click to do a loop!",
    "A CHUVA APAGOU A FOGUEIRA!": "THE RAIN PUT OUT THE CAMPFIRE!",
    "FOGUEIRA: fique pertinho para se divertir": "CAMPFIRE: stay close to have fun",

    # --- Pets ---
    "PIU": "PEEP", "PINTINHO": "CHICK", "MIMI": "MIMI", "GATINHO": "KITTEN",
    "CACHORRINHO": "PUPPY", "GELINHO": "FROSTY", "PINGUIM": "PENGUIN",
    "ZUZU": "BUZZY", "ABELHA": "BEE", "GELECA": "GOOPY", "SLIME": "SLIME",
    "BUH": "BOO", "FANTASMINHA": "LITTLE GHOST", "BIP": "BEEP", "ROBOZINHO": "LITTLE ROBOT",
    "FAÍSCA": "SPARKY", "DRAGÃOZINHO": "BABY DRAGON", "UNICÓRNIO": "UNICORN",
    "TUCA": "TUCK", "TARTARUGA": "TURTLE", "FLOCO": "FLAKE", "COELHINHO": "BUNNY",
    "CAPI": "CAPI", "CAPIVARA": "CAPYBARA",
    "Acha 1 semente de limão por dia": "Finds 1 lemon seed a day",
    "Ronrona no carinho: diversão em dobro": "Purrs when petted: double fun",
    "Busca a bola no SOL: diversão +5": "Fetches the ball in the YARD: fun +5",
    "Piscina e chuva limpam 50% mais": "Pool and rain clean 50% more",
    "Plantas crescem 20% mais rápido": "Plants grow 20% faster",
    "Higiene cai 30% mais devagar": "Hygiene drops 30% slower",
    "Brilha à noite; dormir rende 20% mais": "Glows at night; sleep gives 20% more",
    "Avisa e colhe as plantas prontas": "Alerts you and harvests ready plants",
    "1 marshmallow assado por dia": "1 toasted marshmallow a day",
    "+5% OVOEDAS em todos os jogos": "+5% EGGCOINS in every game",
    "Fome cai 15% mais devagar": "Hunger drops 15% slower",
    "Acha 1 cenoura por dia no SOL": "Finds 1 carrot a day in the YARD",
    "Diversão cai 25% mais devagar": "Fun drops 25% slower",
    "PIU!": "PEEP!", "RRRR...": "PRRR...", "AU AU!": "WOOF WOOF!", "ZZZUM!": "BZZZ!",
    "BUH!": "BOO!", "BIP BIP!": "BEEP BEEP!", "TOC!": "TOK!", "BOING!": "BOING!",
    "RELAXA...": "CHILL...",

    # --- Conquistas / progresso ---
    "PRIMEIRA PARTIDA": "FIRST GAME", "Jogue um mini jogo": "Play a minigame",
    "JOGADOR": "PLAYER", "Jogue 10 partidas": "Play 10 games",
    "VICIADO EM OVOS": "EGG ADDICT", "Jogue 50 partidas": "Play 50 games",
    "LENDA DO FLIPERAMA": "ARCADE LEGEND", "Jogue 200 partidas": "Play 200 games",
    "EXPLORADOR": "EXPLORER", "Jogue 10 jogos diferentes": "Play 10 different games",
    "JÁ JOGUEI DE TUDO": "PLAYED IT ALL", "Jogue todos os 31 jogos solo": "Play all 31 solo games",
    "PRIMEIRO OURO": "FIRST GOLD", "Ganhe uma medalha de ouro": "Win a gold medal",
    "OVO DOURADO": "GOLDEN EGG", "Ganhe 5 medalhas de ouro": "Win 5 gold medals",
    "CAMPEÃO DA RUA": "STREET CHAMP", "Ganhe 15 medalhas de ouro": "Win 15 gold medals",
    "QUEBRA-RECORDES": "RECORD BREAKER", "Bata 10 recordes": "Beat 10 records",
    "BOM DE DUPLA": "GREAT TEAMMATE", "Vença o J2 cinco vezes": "Beat P2 five times",
    "CHEIRINHO BOM": "SMELLS NICE", "Dê o primeiro banho": "Give the first bath",
    "OVO BRILHANTE": "SHINY EGG", "Dê 20 banhos": "Give 20 baths",
    "COMILÃO": "BIG EATER", "Coma 25 vezes": "Eat 25 times",
    "MUITO AMOR": "SO MUCH LOVE", "Faça 50 carinhos": "Pet 50 times",
    "PRIMEIRA COMPRA": "FIRST PURCHASE", "Compre algo na loja": "Buy something at the shop",
    "GASTADOR": "BIG SPENDER", "Gaste 1.000 OVOEDAS": "Spend 1,000 EGGCOINS",
    "VOLTEI!": "I'M BACK!", "Abra o baú 3 dias seguidos": "Open the chest 3 days in a row",
    "UMA SEMANA!": "ONE WEEK!", "Abra o baú 7 dias seguidos": "Open the chest 7 days in a row",
    "OVO FIEL": "LOYAL EGG", "Abra o baú 30 dias seguidos": "Open the chest 30 days in a row",
    "AMIGO DO ROBERT": "ROBERT'S PAL", "Cumpra 5 desafios do dia": "Complete 5 daily challenges",
    "CRESCENDO": "GROWING UP", "Chegue ao nível 5": "Reach level 5",
    "OVO FORMADO": "GROWN EGG", "Chegue ao nível 10": "Reach level 10",
    "OVO VETERANO": "VETERAN EGG", "Chegue ao nível 20": "Reach level 20",
    "OVO LENDÁRIO": "LEGENDARY EGG", "Chegue ao nível 30": "Reach level 30",
    "SORRIA!": "SAY CHEESE!", "Tire uma foto com F12": "Take a photo with F12",
    "OVO RADIANTE": "RADIANT EGG", "3 dias seguidos de OVO FELIZ": "3 days in a row of HAPPY EGG",
    "MISSÃO CUMPRIDA": "MISSION DONE", "Complete 10 missões diárias": "Complete 10 daily missions",
    "CAÇADOR DE SURPRESAS": "SURPRISE HUNTER", "Abra 5 caixas surpresa": "Open 5 surprise boxes",
    "TEM AMIGO NA ÁREA": "FRIEND NEARBY", "Adicione o código de um amigo": "Add a friend's code",
    "MELHORES AMIGOS": "BEST FRIENDS", "Encha o coração de um pet": "Fill a pet's heart",
    "ALQUIMISTA": "ALCHEMIST", "Beba 10 poções": "Drink 10 potions",
    "CAÇADOR DE OVOS": "EGG HUNTER", "Ache todos os ovinhos da Páscoa num dia": "Find all Easter eggs in one day",
    "CONQUISTA!": "ACHIEVEMENT!", "ITEM EXCLUSIVO!": "EXCLUSIVE ITEM!",
    "VEJA NA LOJA (JÁ É SEU)": "SEE THE SHOP (IT'S YOURS)",
    "NÍVEL {n}!": "LEVEL {n}!", "{nome} CRESCEU!": "{nome} GREW UP!", "SEU OVO": "YOUR EGG",
    "SORTE {n}": "LUCK {n}",
    "BORBOLETAS": "BUTTERFLIES", "PEIXES DA PESCARIA": "FISHING CATCHES",
    "RECEITAS DO COZINHEIRO": "CHEF'S RECIPES", "RECEITAS": "RECIPES",
    "PEIXE NOVO!": "NEW FISH!", "RECEITA NOVA!": "NEW RECIPE!", "ITEM NOVO!": "NEW ITEM!",
    "COLEÇÃO {n}/{total}": "COLLECTION {n}/{total}", "COLEÇÃO COMPLETA!": "COLLECTION COMPLETE!",
    "JOGO NOVO LIBERADO!": "NEW GAME UNLOCKED!", "DIA FELIZ!": "HAPPY DAY!",
    "{n} DIA(S) SEGUIDOS DE OVO FELIZ": "{n} DAY(S) IN A ROW OF HAPPY EGG",
    "MELHORES AMIGOS!": "BEST FRIENDS!", "O CORAÇÃO DO PET ENCHEU!": "THE PET'S HEART IS FULL!",

    # --- Eventos / código de amigo ---
    "SEMANA DA PÁSCOA": "EASTER WEEK", "ACHE OS OVINHOS ESCONDIDOS NO SOL!": "FIND THE EGGS HIDDEN IN THE YARD!",
    "HALLOWEEN": "HALLOWEEN", "GOSTOSURAS OU TRAVESSURAS!": "TRICK OR TREAT!",
    "NATAL NA RUA DOS OVOS": "CHRISTMAS ON EGG STREET", "FELIZ NATAL!": "MERRY CHRISTMAS!",
    "FIM DE SEMANA: OVOEDAS x1,2": "WEEKEND: EGGCOINS x1.2", "PRESENTE: {nome}": "GIFT: {nome}",
    "DESAFIO DE AMIGO!": "FRIEND CHALLENGE!", "VOCÊ SUPEROU {nome}!": "YOU BEAT {nome}!",
    "AMIGO": "FRIEND",

    # --- Trilhas ---
    "TEMA DA CASA": "HOME THEME", "OVEIN (CLÁSSICO)": "OVEIN (CLASSIC)",
    "ABERTURA": "OPENING", "RUA DOS OVOS": "EGG STREET", "RUA DOS OVOS (NOITE)": "EGG STREET (NIGHT)",
    "DIA DE CHUVA": "RAINY DAY", "MÃOS À OBRA": "LET'S BUILD", "VITRINE": "SHOWCASE",
    "NASCE UM OVO": "AN EGG IS BORN", "CANÇÃO DE NINAR": "LULLABY", "QUINTAL FELIZ": "HAPPY YARD",
    "DICA: APAGUE A LUZ PARA DORMIR": "HINT: TURN OFF THE LIGHT TO SLEEP",
    "DICA: ESPERE UM DIA DE CHUVA": "HINT: WAIT FOR A RAINY DAY",
    "DICA: VISITE A RUA DE NOITE": "HINT: VISIT THE STREET AT NIGHT",
    "DICA: VÁ AO QUINTAL DE DIA": "HINT: GO TO THE YARD BY DAY",
    "DICA: VISITE A LOJA": "HINT: VISIT THE SHOP",
    "DICA: REFORME SUA CASA": "HINT: REMODEL YOUR HOUSE",
}

ES = {
    "COMUM": "COMÚN", "INCOMUM": "POCO COMÚN", "RARO": "RARO",
    "EPICO": "ÉPICO", "ÉPICO": "ÉPICO", "LENDARIO": "LEGENDARIO", "LENDÁRIO": "LEGENDARIO",
    "CASA": "CASA", "SOL": "PATIO",
    "FOME": "HAMBRE", "ENERGIA": "ENERGÍA", "DIVERSÃO": "DIVERSIÓN", "HIGIENE": "HIGIENE",
    "60 OVOEDAS": "60 HUEVEDAS", "100 OVOEDAS": "100 HUEVEDAS", "+15 OVOEDAS": "+15 HUEVEDAS",

    "LIMÃO": "LIMÓN", "MAÇÃ": "MANZANA", "BANANA": "BANANA", "LEITE": "LECHE",
    "PÃO DE QUEIJO": "PAN DE QUESO", "SUCO DE LIMÃO": "LIMONADA",
    "SANDUÍCHE": "SÁNDWICH", "SORVETE": "HELADO", "PIZZA": "PIZZA",
    "BOLO": "PASTEL", "PIMENTA": "CHILE", "MORANGO": "FRESA",
    "MARSHMALLOW": "MALVAVISCO", "ABÓBORA GIGANTE": "CALABAZA GIGANTE",
    "CENOURA": "ZANAHORIA", "PIPOCA": "PALOMITAS", "BRIGADEIRO": "TRUFA",
    "MELANCIA": "SANDÍA",
    "SEMENTE DE LIMÃO": "SEMILLA DE LIMÓN", "LIMOEIRO": "LIMONERO",
    "SEMENTE DE MORANGO": "SEMILLA DE FRESA", "MORANGUEIRO": "PLANTA DE FRESA",
    "SEMENTE DE GIRASSOL": "SEMILLA DE GIRASOL", "GIRASSOL": "GIRASOL",
    "SEMENTE DE ABÓBORA": "SEMILLA DE CALABAZA", "SEMENTE DE OVOEDAS": "SEMILLA DE HUEVEDAS",
    "ÁRVORE DE OVOEDAS": "ÁRBOL DE HUEVEDAS", "SEMENTE DE MELANCIA": "SEMILLA DE SANDÍA",
    "BROTO": "BROTE", "MUDA": "PLANTÍN", "PLANTA": "PLANTA", "PRONTA": "LISTA",
    "POÇÃO DO SONO": "POCIÓN DE SUEÑO", "POÇÃO DA ALEGRIA": "POCIÓN DE ALEGRÍA",
    "POÇÃO DE ESPUMA": "POCIÓN DE ESPUMA", "ELIXIR TOTAL": "ELIXIR TOTAL",
    "POÇÃO DA SORTE": "POCIÓN DE SUERTE", "POÇÃO DE XP": "POCIÓN DE XP",
    "OVOEDAS x1,5 nas próximas 3 partidas.": "HUEVEDAS x1,5 en las próximas 3 partidas.",
    "XP em DOBRO por 15 minutos.": "XP DOBLE por 15 minutos.",

    "BONÉ VERMELHO": "GORRA ROJA", "GORRO DE LÃ": "GORRO DE LANA", "LAÇO DE FITA": "MOÑO DE CINTA",
    "FLOR NO CABELO": "FLOR EN EL PELO", "ORELHAS DE GATO": "OREJAS DE GATO",
    "CHAPÉU DE CHEF": "GORRO DE CHEF", "CARTOLA": "SOMBRERO DE COPA", "CHAPÉU PIRATA": "SOMBRERO PIRATA",
    "CHAPÉU DE MAGO": "SOMBRERO DE MAGO", "CHIFRE DE UNICÓRNIO": "CUERNO DE UNICORNIO",
    "AURÉOLA": "AUREOLA", "COROA REAL": "CORONA REAL", "CAPACETE ESPACIAL": "CASCO ESPACIAL",
    "BOCHECHAS ROSADAS": "MEJILLAS ROSADAS", "TAPA-OLHO": "PARCHE",
    "ÓCULOS DE NERD": "LENTES DE NERD", "BIGODÃO": "BIGOTAZO",
    "ÓCULOS DO SOL": "LENTES DE SOL", "ÓCULOS DE CORAÇÃO": "LENTES DE CORAZÓN",
    "MÁSCARA DE HERÓI": "MÁSCARA DE HÉROE", "GRAVATA-BORBOLETA": "CORBATÍN",
    "CACHECOL LISTRADO": "BUFANDA A RAYAS", "COLAR HAVAIANO": "COLLAR HAWAIANO",
    "MEDALHA DE OURO": "MEDALLA DE ORO", "BOIA DE PATINHO": "FLOTADOR DE PATITO",
    "CAPA DE HERÓI": "CAPA DE HÉROE", "ASAS DE ANJO": "ALAS DE ÁNGEL",
    "NUVENZINHA DE CHUVA": "NUBECITA DE LLUVIA", "NOTAS MUSICAIS": "NOTAS MUSICALES",
    "ESTRELINHAS": "ESTRELLITAS", "CORAÇÕES": "CORAZONES", "AURA DOURADA": "AURA DORADA",
    "ASAS DE BORBOLETA": "ALAS DE MARIPOSA",
    "CHAPÉU DE PALHA": "SOMBRERO DE PAJA", "CAPACETE DE OBRA": "CASCO DE OBRA",
    "FONES DE OUVIDO": "AUDÍFONOS", "TOUCA DE DINOSSAURO": "GORRO DE DINOSAURIO",
    "NINHO COM PASSARINHO": "NIDO CON PAJARITO", "SARDAS": "PECAS", "ÓCULOS 3D": "LENTES 3D",
    "MONÓCULO": "MONÓCULO", "AVENTAL DE JARDIM": "DELANTAL DE JARDÍN", "MOCHILA": "MOCHILA",
    "CAPA DE CHUVA": "IMPERMEABLE", "MOCHILA-FOGUETE": "MOCHILA COHETE",
    "BOLHAS DE SABÃO": "POMPAS DE JABÓN", "VAGALUMES": "LUCIÉRNAGAS", "ARCO-ÍRIS": "ARCOÍRIS",

    "CABELO": "PELO", "OLHOS": "OJOS", "BOCA": "BOCA", "COR": "COLOR", "ROUPA": "ROPA",
    "Troca o cabelo do seu ovo em todos os jogos!": "¡Cambia el pelo de tu huevo en todos los juegos!",
    "Troca os olhos do seu ovo em todos os jogos!": "¡Cambia los ojos de tu huevo en todos los juegos!",
    "Troca a boca do seu ovo em todos os jogos!": "¡Cambia la boca de tu huevo en todos los juegos!",
    "Pinta o seu ovo de uma cor nova em todos os jogos!": "¡Pinta tu huevo de un color nuevo en todos los juegos!",
    "Uma roupa nova para o seu ovo usar em todos os jogos!": "¡Ropa nueva para tu huevo en todos los juegos!",
    "TOPETE": "COPETE", "FRANJINHA": "FLEQUILLO", "COQUE": "MOÑO", "RABO DE CAVALO": "COLA DE CABALLO",
    "MARIA-CHIQUINHA": "COLETAS", "BLACK POWER": "AFRO", "MOICANO PUNK": "CRESTA PUNK",
    "CACHINHOS DOURADOS": "RIZOS DORADOS", "CABELO DE FOGO": "PELO DE FUEGO",
    "CABELO ARCO-ÍRIS": "PELO ARCOÍRIS",
    "OLHINHOS DE BOLINHA": "OJITOS DE BOLITA", "OLHOS SONOLENTOS": "OJOS SOÑOLIENTOS",
    "CÍLIOS LONGOS": "PESTAÑAS LARGAS", "OLHOS BRILHANTES": "OJOS BRILLANTES",
    "OLHOS DE GATO": "OJOS DE GATO", "OLHOS APAIXONADOS": "OJOS ENAMORADOS",
    "OLHOS HIPNÓTICOS": "OJOS HIPNÓTICOS", "OLHOS DE ROBÔ": "OJOS DE ROBOT",
    "OLHOS DE GALÁXIA": "OJOS DE GALAXIA", "OLHOS DE ESTRELA": "OJOS DE ESTRELLA",
    "SORRISÃO": "SONRISOTA", "BOQUINHA DE GATO": "BOQUITA DE GATO", "ASSOBIANDO": "SILBANDO",
    "BATOM VERMELHO": "LABIAL ROJO", "PRESINHAS DE VAMPIRO": "COLMILLOS DE VAMPIRO",
    "APARELHO NOS DENTES": "FRENILLOS", "PIRULITO": "PALETA", "DENTE DE OURO": "DIENTE DE ORO",
    "BOLA DE CHICLETE": "GLOBO DE CHICLE", "SORRISO DE DIAMANTE": "SONRISA DE DIAMANTE",
    "ROSA CHICLETE": "ROSA CHICLE", "LARANJA": "NARANJA", "AMARELO GEMA": "AMARILLO YEMA",
    "VERDE MENTA": "VERDE MENTA", "OVO DE CODORNA": "HUEVO DE CODORNIZ", "CHOCOLATE": "CHOCOLATE",
    "PRETO NOITE": "NEGRO NOCHE", "DOURADO": "DORADO", "GALÁXIA": "GALAXIA",
    "ABÓBORA DE HALLOWEEN": "CALABAZA DE HALLOWEEN",
    "CAMISETA LISTRADA": "CAMISETA A RAYAS", "MACACÃO JEANS": "OVEROL DE MEZCLILLA",
    "CAMISA DE FUTEBOL": "CAMISETA DE FÚTBOL", "VESTIDO DE BOLINHAS": "VESTIDO DE LUNARES",
    "MOLETOM COM CAPUZ": "SUDADERA", "QUIMONO DE KARATÊ": "KIMONO DE KARATE",
    "TERNO ELEGANTE": "TRAJE ELEGANTE", "TRAJE DE ASTRONAUTA": "TRAJE DE ASTRONAUTA",
    "ARMADURA DE CAVALEIRO": "ARMADURA DE CABALLERO", "MANTO REAL": "MANTO REAL",
    "SUÉTER DE NATAL": "SUÉTER NAVIDEÑO", "GORRO DE NATAL": "GORRO NAVIDEÑO",
    "CHAPÉU DE BRUXA": "SOMBRERO DE BRUJA", "ORELHAS DE COELHO DE PÁSCOA": "OREJAS DE CONEJO DE PASCUA",

    "AZUL": "AZUL", "BRANCO": "BLANCO", "VERDE": "VERDE", "VERMELHO": "ROJO",
    "AMARELO": "AMARILLO", "CREME": "CREMA", "PÊSSEGO": "DURAZNO", "LILÁS": "LILA",
    "ROSA": "ROSA", "CINZA": "GRIS", "MENTA": "MENTA", "COR DO OVO": "COLOR DEL HUEVO",
    "TELHA": "TEJA", "MARROM": "MARRÓN", "PRETO": "NEGRO", "ROXO": "MORADO",
    "MADEIRA": "MADERA", "VERMELHA": "ROJA", "AMARELA": "AMARILLA", "BRANCA": "BLANCA",
    "PRETA": "NEGRA", "ROXA": "MORADA",

    "LISO": "LISO", "Parede lisinha, do jeito que veio.": "Pared lisita, tal como vino.",
    "Tábuas de madeira com preguinhos.": "Tablas de madera con clavitos.",
    "LISTRAS": "RAYAS", "Listras verticais animadas.": "Rayas verticales alegres.",
    "BOLINHAS": "LUNARES", "Bolinhas por toda a parede.": "Lunares por toda la pared.",
    "TIJOLINHO": "LADRILLO", "Tijolinho à vista, charmoso.": "Ladrillo a la vista, encantador.",
    "PEDRA DE CASTELO": "PIEDRA DE CASTILLO", "Pedras grandes de castelo.": "Grandes piedras de castillo.",
    "TRIÂNGULO": "TRIÁNGULO", "O telhado clássico.": "El techo clásico.",
    "TELHAS DE ESCAMA": "TEJAS DE ESCAMA", "Telhas redondinhas como escamas.": "Tejas redonditas como escamas.",
    "TELHADO DE PALHA": "TECHO DE PAJA", "Palha fofinha de casa de campo.": "Paja suavecita de casa de campo.",
    "TELHADO COGUMELO": "TECHO HONGO", "Um cogumelo gigante de bolinhas.": "Un hongo gigante de lunares.",
    "RETA": "RECTA", "Porta simples de madeira.": "Puerta sencilla de madera.",
    "PORTA EM ARCO": "PUERTA EN ARCO", "Porta com o topo arredondado.": "Puerta con la parte de arriba redonda.",
    "PORTA REDONDA": "PUERTA REDONDA", "Porta redonda de toca.": "Puerta redonda de madriguera.",
    "PORTA DE OVO": "PUERTA DE HUEVO", "Porta em forma de ovo, com moldura dourada.": "Puerta con forma de huevo y marco dorado.",
    "QUADRADA": "CUADRADA", "Janelas quadradas com cruz.": "Ventanas cuadradas con cruz.",
    "JANELAS REDONDAS": "VENTANAS REDONDAS", "Janelas redondas de navio.": "Ventanas redondas de barco.",
    "JANELAS EM ARCO": "VENTANAS EN ARCO", "Janelas com o topo em arco.": "Ventanas con la parte de arriba en arco.",
    "JANELAS COM FLOREIRA": "VENTANAS CON MACETA", "Uma floreira embaixo de cada janela.": "Una jardinera bajo cada ventana.",
    "JANELAS DE CORAÇÃO": "VENTANAS DE CORAZÓN", "Janelas de coração que brilham à noite.": "Ventanas de corazón que brillan de noche.",
    "SEM CERCA": "SIN CERCA", "Nada de cerca.": "Nada de cerca.",
    "CERCA RÚSTICA": "CERCA RÚSTICA", "Estacas de madeira com arame.": "Estacas de madera con alambre.",
    "CERCA BRANCA": "CERCA BLANCA", "A cerquinha branca dos sonhos.": "La cerquita blanca de tus sueños.",
    "CERCA-VIVA": "SETO", "Arbustos com florzinhas.": "Arbustos con florecitas.",
    "GRADE DE FERRO": "REJA DE HIERRO", "Grade elegante com pontas de lança.": "Reja elegante con puntas de lanza.",
    "CAIXA PADRÃO": "BUZÓN NORMAL", "Caixa de correio azul.": "Buzón azul.",
    "CAIXA DE CORREIO OVO": "BUZÓN DE HUEVO", "Uma caixa de correio em forma de ovo.": "Un buzón con forma de huevo.",
    "TERRA": "TIERRA", "Caminho de terra batida.": "Camino de tierra apisonada.",
    "PEDRINHAS": "PIEDRITAS", "Pedrinhas no meio da grama.": "Piedritas entre el pasto.",
    "TIJOLOS": "LADRILLOS", "Caminho de tijolos.": "Camino de ladrillos.",
    "TAPETE VERMELHO": "ALFOMBRA ROJA", "Para entrar como uma estrela.": "Para entrar como una estrella.",
    "CAMINHO ARCO-ÍRIS": "CAMINO ARCOÍRIS", "Um caminho com todas as cores.": "Un camino con todos los colores.",
    "VASO DE FLOR": "MACETA", "Presente de mudança. Flores que dançam no vento.": "Regalo de mudanza. Flores que bailan con el viento.",
    "CACTO": "CACTUS", "Espinhento, mas fofo.": "Espinoso, pero tierno.",
    "FLAMINGO DE JARDIM": "FLAMENCO DE JARDÍN", "Um flamingo cor-de-rosa numa perna só.": "Un flamenco rosa en una sola pata.",
    "ANÃO DE JARDIM": "ENANO DE JARDÍN", "Ele pisca quando ninguém está olhando.": "Guiña el ojo cuando nadie lo mira.",
    "JARDIM DE FLORES": "JARDÍN DE FLORES", "Uma caixa cheia de flores.": "Una caja llena de flores.",
    "CASINHA DE PASSARINHO": "CASITA DE PÁJAROS", "Um passarinho azul mora aqui.": "Aquí vive un pajarito azul.",
    "ABÓBORA-LANTERNA": "CALABAZA LINTERNA", "O rosto brilha à noite.": "Su cara brilla de noche.",
    "POSTE DE LUZ": "FAROL", "Ilumina a calçada à noite.": "Ilumina la acera de noche.",
    "BANCO DE JARDIM": "BANCA DE JARDÍN", "O ovo senta nele para ver a rua.": "El huevo se sienta a ver la calle.",
    "ÁRVORE FRONDOSA": "ÁRBOL FRONDOSO", "Uma árvore com frutinhas vermelhas.": "Un árbol con frutitas rojas.",
    "BICICLETA": "BICICLETA", "Na cor do seu ovo. TRIM!": "Del color de tu huevo. ¡RIN RIN!",
    "ARBUSTO EM FORMA DE OVO": "ARBUSTO CON FORMA DE HUEVO", "Podado com muito carinho.": "Podado con mucho cariño.",
    "ESPANTALHO": "ESPANTAPÁJAROS", "Espanta os corvos (quase sempre).": "Espanta a los cuervos (casi siempre).",
    "FONTE DE JARDIM": "FUENTE DE JARDÍN", "Uma fontezinha que não para de jorrar.": "Una fuentecita que nunca para.",
    "ANTENA DE TV": "ANTENA DE TV", "Pega todos os canais de desenho.": "Capta todos los canales de caricaturas.",
    "BANDEIRA": "BANDERA", "Uma bandeira na cor do seu ovo.": "Una bandera del color de tu huevo.",
    "BALÕES": "GLOBOS", "Três balões presos na chaminé.": "Tres globos atados a la chimenea.",
    "GALO CATA-VENTO": "GALLO VELETA", "Gira mais rápido quando venta.": "Gira más rápido cuando hay viento.",
    "PISCA-PISCA": "LUCECITAS", "Luzinhas que piscam à noite.": "Lucecitas que parpadean de noche.",
    "PAINEL SOLAR": "PANEL SOLAR", "Energia limpa do sol.": "Energía limpia del sol.",
    "GATO NO TELHADO": "GATO EN EL TECHO", "Um gato laranja dorminhoco. MIAU!": "Un gato naranja dormilón. ¡MIAU!",
    "+NOVO": "+NUEVO",

    "GELADEIRA": "REFRI", "Guarda as comidas do ovo.": "Guarda la comida del huevo.",
    "INTERRUPTOR": "INTERRUPTOR", "Apaga a luz para o ovo dormir.": "Apaga la luz para que el huevo duerma.",
    "TAPETE REDONDO": "TAPETE REDONDO", "Um tapete fofinho para a sala.": "Un tapete suavecito para la sala.",
    "PLANTA NO VASO": "PLANTA EN MACETA", "Balança as folhas quando você mexe nela.": "Mueve sus hojas cuando la tocas.",
    "LÂMPADA DE LAVA": "LÁMPARA DE LAVA", "Bolhas coloridas que brilham no escuro.": "Burbujas de colores que brillan en la oscuridad.",
    "RETRATO DO OVO": "RETRATO DEL HUEVO", "Uma foto sua! Clique para trocar o fundo.": "¡Una foto tuya! Haz clic para cambiar el fondo.",
    "RELÓGIO CUCO": "RELOJ CUCÚ", "Mostra a hora de verdade. CUCO!": "Muestra la hora real. ¡CUCÚ!",
    "VITROLA": "ROCOLA", "Toca as músicas dos jogos que você já jogou.": "Toca la música de los juegos que ya jugaste.",
    "ESTANTE DE TROFÉUS": "REPISA DE TROFEOS", "Mostra os troféus que você ganhou nos jogos.": "Muestra los trofeos que ganaste en los juegos.",
    "TELEVISÃO": "TELE", "4 canais! Assistir deixa o ovo feliz.": "¡4 canales! Ver tele alegra al huevo.",
    "AQUÁRIO": "ACUARIO", "Três peixinhos. Dê ração para eles!": "Tres pececitos. ¡Dales de comer!",
    "CAMA": "CAMA", "Dormir na cama recupera energia 2x mais rápido.": "Dormir en la cama recupera energía 2x más rápido.",
    "CANTEIRO EXTRA": "HUERTO EXTRA", "Mais um canteiro para plantar.": "Un huerto más para sembrar.",
    "CATA-VENTO": "REHILETE", "Gira com o vento. Clique para soprar!": "Gira con el viento. ¡Haz clic para soplar!",
    "CASINHA DO PET": "CASITA DE LA MASCOTA", "O seu pet dorme nela à noite.": "Tu mascota duerme ahí de noche.",
    "PISCINA INFLÁVEL": "PISCINA INFLABLE", "Banho divertido: limpa e diverte.": "Baño divertido: limpia y divierte.",
    "VARAL DE LUZES": "GUIRNALDA DE LUCES", "Luzinhas coloridas que acendem à noite.": "Lucecitas de colores que se encienden de noche.",
    "TELESCÓPIO": "TELESCOPIO", "À noite, pegue uma estrela cadente!": "¡De noche, atrapa una estrella fugaz!",
    "ÁRVORE COM BALANÇO": "ÁRBOL CON COLUMPIO", "O ovo senta e balança. Uhuuu!": "El huevo se sienta y se columpia. ¡Yujuuu!",
    "CORTINAS": "CORTINAS", "Fecham sozinhas quando o ovo dorme.": "Se cierran solas cuando el huevo duerme.",
    "QUADRO DA VIZINHANÇA": "MAPA DEL BARRIO", "A sua rua em miniatura, com as casas dos vizinhos.": "Tu calle en miniatura, con las casas de los vecinos.",
    "PIPA": "PAPALOTE", "Voa no céu do quintal. Clique para dar um looping!": "Vuela sobre el patio. ¡Haz clic para dar una vuelta!",
    "FOGUEIRA": "FOGATA", "Acende no fim do dia. Ficar pertinho diverte o ovo.": "Se enciende al atardecer. Estar cerquita divierte al huevo.",
    "GELADEIRA: COMIDA": "REFRI: COMIDA", "ACENDER A LUZ": "ENCENDER LUZ",
    "APAGAR A LUZ": "APAGAR LUZ", "CUCO!": "¡CUCÚ!", "JUKEBOX": "ROCOLA",
    "TROFÉUS": "TROFEOS", "GANHE TROFÉUS NOS MINI JOGOS!": "¡GANA TROFEOS EN LOS MINIJUEGOS!",
    "DESLIGADA": "APAGADA", "ROBERT SHOW": "ROBERT SHOW", "DESENHO": "CARICATURAS",
    "CHUVISCO": "ESTÁTICA", "RECORDES": "RÉCORDS",
    "JOGUE OS MINI JOGOS!": "¡JUEGA LOS MINIJUEGOS!", "TV DESLIGADA": "TV APAGADA",
    "CANAL {n}: {nome}": "CANAL {n}: {nome}", "CH {n}": "CH {n}",
    "OI OVO!   OI OVO!": "¡HOLA HUEVO!   ¡HOLA HUEVO!", "DAR RAÇÃO AOS PEIXES": "ALIMENTAR A LOS PECES",
    "DORMIR NA CAMA": "DORMIR EN LA CAMA", "CASINHA DO {nome}": "CASITA DE {nome}",
    "SÓ À NOITE!": "¡SOLO DE NOCHE!", "CONSTELAÇÃO DO OVO": "CONSTELACIÓN DEL HUEVO",
    "Espere uma estrela cadente...": "Espera una estrella fugaz...",
    "DESEJO REALIZADO!": "¡DESEO CUMPLIDO!", "VOLTAR": "VOLVER",
    "OLHAR AS ESTRELAS": "VER LAS ESTRELLAS", "TELESCÓPIO: SÓ À NOITE": "TELESCOPIO: SOLO DE NOCHE",
    "BALANÇAR": "COLUMPIARSE",
    "CORTINAS: clique para abrir/fechar": "CORTINAS: clic para abrir/cerrar",
    "VIZINHOS: {lista}": "VECINOS: {lista}", "NENHUM VIZINHO AINDA": "AÚN NO HAY VECINOS",
    "PIPA: guardada por causa da chuva": "PAPALOTE: guardado por la lluvia",
    "PIPA: clique para dar um looping!": "PAPALOTE: ¡clic para dar una vuelta!",
    "A CHUVA APAGOU A FOGUEIRA!": "¡LA LLUVIA APAGÓ LA FOGATA!",
    "FOGUEIRA: fique pertinho para se divertir": "FOGATA: quédate cerquita para divertirte",

    "PIU": "PÍO", "PINTINHO": "POLLITO", "MIMI": "MIMI", "GATINHO": "GATITO",
    "CACHORRINHO": "PERRITO", "GELINHO": "HIELITO", "PINGUIM": "PINGÜINO",
    "ZUZU": "ZUZÚ", "ABELHA": "ABEJA", "GELECA": "GELATINA", "SLIME": "SLIME",
    "BUH": "BU", "FANTASMINHA": "FANTASMITA", "BIP": "BIP", "ROBOZINHO": "ROBOTITO",
    "FAÍSCA": "CHISPA", "DRAGÃOZINHO": "DRAGONCITO", "UNICÓRNIO": "UNICORNIO",
    "TUCA": "TUCA", "TARTARUGA": "TORTUGA", "FLOCO": "COPO", "COELHINHO": "CONEJITO",
    "CAPI": "CAPI", "CAPIVARA": "CAPIBARA",
    "Acha 1 semente de limão por dia": "Encuentra 1 semilla de limón al día",
    "Ronrona no carinho: diversão em dobro": "Ronronea con mimos: diversión doble",
    "Busca a bola no SOL: diversão +5": "Trae la pelota en el PATIO: diversión +5",
    "Piscina e chuva limpam 50% mais": "Piscina y lluvia limpian 50% más",
    "Plantas crescem 20% mais rápido": "Las plantas crecen 20% más rápido",
    "Higiene cai 30% mais devagar": "La higiene baja 30% más lento",
    "Brilha à noite; dormir rende 20% mais": "Brilla de noche; dormir rinde 20% más",
    "Avisa e colhe as plantas prontas": "Avisa y cosecha las plantas listas",
    "1 marshmallow assado por dia": "1 malvavisco asado al día",
    "+5% OVOEDAS em todos os jogos": "+5% HUEVEDAS en todos los juegos",
    "Fome cai 15% mais devagar": "El hambre baja 15% más lento",
    "Acha 1 cenoura por dia no SOL": "Encuentra 1 zanahoria al día en el PATIO",
    "Diversão cai 25% mais devagar": "La diversión baja 25% más lento",
    "PIU!": "¡PÍO!", "RRRR...": "RRRR...", "AU AU!": "¡GUAU GUAU!", "ZZZUM!": "¡BZZZ!",
    "BUH!": "¡BU!", "BIP BIP!": "¡BIP BIP!", "TOC!": "¡TOC!", "BOING!": "¡BOING!",
    "RELAXA...": "TRANQUI...",

    "PRIMEIRA PARTIDA": "PRIMERA PARTIDA", "Jogue um mini jogo": "Juega un minijuego",
    "JOGADOR": "JUGADOR", "Jogue 10 partidas": "Juega 10 partidas",
    "VICIADO EM OVOS": "ADICTO A LOS HUEVOS", "Jogue 50 partidas": "Juega 50 partidas",
    "LENDA DO FLIPERAMA": "LEYENDA ARCADE", "Jogue 200 partidas": "Juega 200 partidas",
    "EXPLORADOR": "EXPLORADOR", "Jogue 10 jogos diferentes": "Juega 10 juegos distintos",
    "JÁ JOGUEI DE TUDO": "YA JUGUÉ DE TODO", "Jogue todos os 31 jogos solo": "Juega los 31 juegos individuales",
    "PRIMEIRO OURO": "PRIMER ORO", "Ganhe uma medalha de ouro": "Gana una medalla de oro",
    "OVO DOURADO": "HUEVO DORADO", "Ganhe 5 medalhas de ouro": "Gana 5 medallas de oro",
    "CAMPEÃO DA RUA": "CAMPEÓN DE LA CALLE", "Ganhe 15 medalhas de ouro": "Gana 15 medallas de oro",
    "QUEBRA-RECORDES": "ROMPE RÉCORDS", "Bata 10 recordes": "Rompe 10 récords",
    "BOM DE DUPLA": "BUEN COMPAÑERO", "Vença o J2 cinco vezes": "Vence al J2 cinco veces",
    "CHEIRINHO BOM": "OLORCITO RICO", "Dê o primeiro banho": "Da el primer baño",
    "OVO BRILHANTE": "HUEVO RELUCIENTE", "Dê 20 banhos": "Da 20 baños",
    "COMILÃO": "GLOTÓN", "Coma 25 vezes": "Come 25 veces",
    "MUITO AMOR": "MUCHO AMOR", "Faça 50 carinhos": "Haz 50 mimos",
    "PRIMEIRA COMPRA": "PRIMERA COMPRA", "Compre algo na loja": "Compra algo en la tienda",
    "GASTADOR": "DERROCHADOR", "Gaste 1.000 OVOEDAS": "Gasta 1.000 HUEVEDAS",
    "VOLTEI!": "¡VOLVÍ!", "Abra o baú 3 dias seguidos": "Abre el cofre 3 días seguidos",
    "UMA SEMANA!": "¡UNA SEMANA!", "Abra o baú 7 dias seguidos": "Abre el cofre 7 días seguidos",
    "OVO FIEL": "HUEVO FIEL", "Abra o baú 30 dias seguidos": "Abre el cofre 30 días seguidos",
    "AMIGO DO ROBERT": "AMIGO DE ROBERT", "Cumpra 5 desafios do dia": "Cumple 5 desafíos del día",
    "CRESCENDO": "CRECIENDO", "Chegue ao nível 5": "Llega al nivel 5",
    "OVO FORMADO": "HUEVO GRANDE", "Chegue ao nível 10": "Llega al nivel 10",
    "OVO VETERANO": "HUEVO VETERANO", "Chegue ao nível 20": "Llega al nivel 20",
    "OVO LENDÁRIO": "HUEVO LEGENDARIO", "Chegue ao nível 30": "Llega al nivel 30",
    "SORRIA!": "¡SONRÍE!", "Tire uma foto com F12": "Toma una foto con F12",
    "OVO RADIANTE": "HUEVO RADIANTE", "3 dias seguidos de OVO FELIZ": "3 días seguidos de HUEVO FELIZ",
    "MISSÃO CUMPRIDA": "MISIÓN CUMPLIDA", "Complete 10 missões diárias": "Completa 10 misiones diarias",
    "CAÇADOR DE SURPRESAS": "CAZASORPRESAS", "Abra 5 caixas surpresa": "Abre 5 cajas sorpresa",
    "TEM AMIGO NA ÁREA": "HAY AMIGOS CERCA", "Adicione o código de um amigo": "Agrega el código de un amigo",
    "MELHORES AMIGOS": "MEJORES AMIGOS", "Encha o coração de um pet": "Llena el corazón de una mascota",
    "ALQUIMISTA": "ALQUIMISTA", "Beba 10 poções": "Bebe 10 pociones",
    "CAÇADOR DE OVOS": "CAZAHUEVOS", "Ache todos os ovinhos da Páscoa num dia": "Encuentra todos los huevitos de Pascua en un día",
    "CONQUISTA!": "¡LOGRO!", "ITEM EXCLUSIVO!": "¡OBJETO EXCLUSIVO!",
    "VEJA NA LOJA (JÁ É SEU)": "MIRA LA TIENDA (YA ES TUYO)",
    "NÍVEL {n}!": "¡NIVEL {n}!", "{nome} CRESCEU!": "¡{nome} CRECIÓ!", "SEU OVO": "TU HUEVO",
    "SORTE {n}": "SUERTE {n}",
    "BORBOLETAS": "MARIPOSAS", "PEIXES DA PESCARIA": "PECES DE LA PESCA",
    "RECEITAS DO COZINHEIRO": "RECETAS DEL COCINERO", "RECEITAS": "RECETAS",
    "PEIXE NOVO!": "¡PEZ NUEVO!", "RECEITA NOVA!": "¡RECETA NUEVA!", "ITEM NOVO!": "¡OBJETO NUEVO!",
    "COLEÇÃO {n}/{total}": "COLECCIÓN {n}/{total}", "COLEÇÃO COMPLETA!": "¡COLECCIÓN COMPLETA!",
    "JOGO NOVO LIBERADO!": "¡JUEGO NUEVO DESBLOQUEADO!", "DIA FELIZ!": "¡DÍA FELIZ!",
    "{n} DIA(S) SEGUIDOS DE OVO FELIZ": "{n} DÍA(S) SEGUIDOS DE HUEVO FELIZ",
    "MELHORES AMIGOS!": "¡MEJORES AMIGOS!", "O CORAÇÃO DO PET ENCHEU!": "¡EL CORAZÓN DE LA MASCOTA SE LLENÓ!",

    "SEMANA DA PÁSCOA": "SEMANA DE PASCUA", "ACHE OS OVINHOS ESCONDIDOS NO SOL!": "¡ENCUENTRA LOS HUEVITOS EN EL PATIO!",
    "HALLOWEEN": "HALLOWEEN", "GOSTOSURAS OU TRAVESSURAS!": "¡DULCE O TRUCO!",
    "NATAL NA RUA DOS OVOS": "NAVIDAD EN LA CALLE HUEVOS", "FELIZ NATAL!": "¡FELIZ NAVIDAD!",
    "FIM DE SEMANA: OVOEDAS x1,2": "FIN DE SEMANA: HUEVEDAS x1,2", "PRESENTE: {nome}": "REGALO: {nome}",
    "DESAFIO DE AMIGO!": "¡DESAFÍO DE AMIGO!", "VOCÊ SUPEROU {nome}!": "¡SUPERASTE A {nome}!",
    "AMIGO": "AMIGO",

    "TEMA DA CASA": "TEMA DE LA CASA", "OVEIN (CLÁSSICO)": "OVEIN (CLÁSICO)",
    "ABERTURA": "APERTURA", "RUA DOS OVOS": "CALLE HUEVOS", "RUA DOS OVOS (NOITE)": "CALLE HUEVO (NOCHE)",
    "DIA DE CHUVA": "DÍA DE LLUVIA", "MÃOS À OBRA": "MANOS A LA OBRA", "VITRINE": "VITRINA",
    "NASCE UM OVO": "NACE UN HUEVO", "CANÇÃO DE NINAR": "CANCIÓN DE CUNA", "QUINTAL FELIZ": "PATIO FELIZ",
    "DICA: APAGUE A LUZ PARA DORMIR": "PISTA: APAGA LA LUZ PARA DORMIR",
    "DICA: ESPERE UM DIA DE CHUVA": "PISTA: ESPERA UN DÍA DE LLUVIA",
    "DICA: VISITE A RUA DE NOITE": "PISTA: VISITA LA CALLE DE NOCHE",
    "DICA: VÁ AO QUINTAL DE DIA": "PISTA: VE AL PATIO DE DÍA",
    "DICA: VISITE A LOJA": "PISTA: VISITA LA TIENDA",
    "DICA: REFORME SUA CASA": "PISTA: REMODELA TU CASA",
}
