# Traducoes (ver o guia em core/idioma.py). Chave = texto ORIGINAL em portugues.
# Jogos: micro_ovo, mini_golfe, ovo_kombat, sumo_ovo, estoura_bolha, ovo_estrada,
# salto_lago, liga_ovos, chuva, rei_quintal, thumb_fighter, base_multi, trofeus.

EN = {
    # --- Comuns (HUD / fim) ---
    "PONTOS": "POINTS",
    "PONTOS: {n}": "POINTS: {n}",
    "RECORDE: {v}": "BEST: {v}",
    "MAIOR COMBO: {n}": "BEST COMBO: {n}",
    "MAIOR COMBO: ×{n}": "BEST COMBO: ×{n}",
    "O TEMPO ACABOU!": "TIME'S UP!",
    "ROUND {n}": "ROUND {n}",
    "ROUNDS  {a} × {b}": "ROUNDS  {a} × {b}",
    "GLUB!": "GLUB!",
    "BUM!": "BOOM!",
    "BOING!": "BOING!",

    # --- base_multi (2 jogadores) ---
    "WASD + ESPAÇO": "WASD + SPACE",
    "SETAS + ENTER": "ARROWS + ENTER",
    "VIZINHO": "NEIGHBOR",
    "J2: {nome} (CASA {n})": "P2: {nome} (HOUSE {n})",
    "J2: SORTEADO": "P2: RANDOM",
    "JOGADOR 1": "PLAYER 1",
    "JOGADOR 2": "PLAYER 2",
    "EMPATE!": "TIE!",
    "{nome} VENCEU!": "{nome} WINS!",
    "VITÓRIAS  J1 {a} × {b} J2": "WINS  P1 {a} × {b} P2",
    "COR DO J2 TROCADA NESTA PARTIDA": "P2 COLOR SWAPPED THIS MATCH",
    "PARA {nome}": "FOR {nome}",
    "2 JOGADORES": "2 PLAYERS",
    "ESCOLHA O MODO:": "PICK A MODE:",
    "ESCOLHA O MODO": "PICK A MODE",
    "VS BOT OU 2 JOGADORES": "VS BOT OR 2 PLAYERS",
    "J1": "P1",
    "J2": "P2",
    "J{n}": "P{n}",

    # --- trofeus ---
    "{n} partidas": "{n} matches",
    "venceu {modo}": "beat {modo}",
    "recorde {v}": "best {v}",
    "Jogue {nome} com um amigo e VENÇA!": "Play {nome} with a friend and WIN!",
    "Vença uma partida de {nome}!": "Win a round of {nome}!",
    "Faça {v} ou menos em {nome}!": "Get {v} or less in {nome}!",
    "Faça {v} em {nome}!": "Get {v} in {nome}!",

    # --- MICRO-OVO ---
    "MICRO-OVO": "MICRO-EGG",
    "Microjogos de 4 segundos em sequência! Leia a ordem gigante e faça rápido.":
        "4-second microgames back to back! Read the giant order and be quick.",
    "Microjogos de 4 segundos, um atrás do outro!": "4-second microgames, one after another!",
    "Leia a ORDEM gigante e faça rápido.": "Read the giant ORDER and be quick.",
    "Errou? Perde um ovo. São 4 ovos de vida.": "Missed? You lose an egg. You have 4 eggs.",
    "A cada 5 rodadas fica MAIS RÁPIDO!": "Every 5 rounds it gets FASTER!",
    "SETAS/WASD, ESPAÇO e MOUSE": "ARROWS/WASD, SPACE and MOUSE",
    "NORMAL": "NORMAL",
    "TURBO": "TURBO",
    "RODADAS": "ROUNDS",
    "JÁ!": "GO!",
    "PEGUE!": "CATCH!",
    "← →  OU  MOUSE": "← →  OR  MOUSE",
    "DESVIE!": "DODGE!",
    "ESTOURE!": "POP!",
    "CLIQUE NAS BOLHAS": "CLICK THE BUBBLES",
    "PULE!": "JUMP!",
    "ESPAÇO, ↑ OU CLIQUE": "SPACE, ↑ OR CLICK",
    "LIMPE!": "CLEAN!",
    "ESFREGUE COM O MOUSE": "SCRUB WITH THE MOUSE",
    "APERTE!": "PRESS!",
    "AS SETAS NA ORDEM": "THE ARROWS IN ORDER",
    "PARE!": "STOP!",
    "NO VERDE! ESPAÇO OU CLIQUE": "ON GREEN! SPACE OR CLICK",
    "ACHE!": "FIND!",
    "O OVO DIFERENTE": "THE ODD EGG OUT",
    "SOPRE!": "BLOW!",
    "APERTE ESPAÇO RÁPIDO!": "MASH SPACE FAST!",
    "GUIE!": "GUIDE!",
    "LEVE A ABELHA ATÉ A FLOR": "LEAD THE BEE TO THE FLOWER",
    "ACORDE!": "WAKE UP!",
    "← → ← →  OU CHACOALHE O MOUSE": "← → ← →  OR SHAKE THE MOUSE",
    "CONTE!": "COUNT!",
    "QUANTOS PINTINHOS?": "HOW MANY CHICKS?",
    "ENCHA!": "FILL!",
    "SEGURE ESPAÇO E SOLTE NA LINHA": "HOLD SPACE, LET GO AT THE LINE",
    "LINHA": "LINE",
    "LENDA DOS MICROS!": "MICRO LEGEND!",
    "MANDOU BEM!": "NICE JOB!",
    "ACABARAM OS OVOS!": "OUT OF EGGS!",
    "RODADAS VENCIDAS: {n}": "ROUNDS WON: {n}",
    "RODADAS JOGADAS: {n}": "ROUNDS PLAYED: {n}",
    "VELOCIDADE MÁXIMA: {v}": "TOP SPEED: {v}",
    "PONTOS: {n}    VELOCIDADE {v}": "POINTS: {n}    SPEED {v}",
    "VELOCIDADE {v}": "SPEED {v}",
    "RODADA {n}": "ROUND {n}",
    "FALTAM {n}": "{n} LEFT",
    "NA MOSCA!": "BULLSEYE!",
    "PARABÉNS!": "HOORAY!",
    "MEL!": "HONEY!",
    "BOM DIA!": "GOOD MORNING!",
    "NA MEDIDA!": "JUST RIGHT!",
    "PASSOU!": "TOO MUCH!",
    "POP!": "POP!",
    "TOING!": "BOING!",
    "AI!": "OUCH!",
    "ERAM {n}!": "IT WAS {n}!",
    "CLANG!": "CLANG!",
    "BOA!": "NICE!",
    "FIM!": "THE END!",
    "ACABOU...": "GAME OVER...",
    "PREPARE-SE!": "GET READY!",
    "MAIS RÁPIDO!": "FASTER!",

    # --- MINI GOLFE ---
    "MINI GOLFE DO OVO": "EGG MINI GOLF",
    "MINI GOLFE": "MINI GOLF",
    "O seu ovo é a bolinha! 9 buracos malucos com moinho, água, areia e portais.":
        "Your egg is the ball! 9 wacky holes with a windmill, water, sand and portals.",
    "O seu ovo é a bolinha: acerte os 9 buracos!": "Your egg is the ball: sink all 9 holes!",
    "Use poucas tacadas. Água custa +1 tacada.": "Use few strokes. Water costs +1 stroke.",
    "Setas dão velocidade e os portais teletransportam.": "Arrows speed you up and portals teleport.",
    "← → (ou A D) mira, SHIFT = mira fina": "← → (or A D) aim, SHIFT = fine aim",
    "ESPAÇO: segure e solte • MOUSE: puxe e solte": "SPACE: hold and release • MOUSE: pull and release",
    "TACADAS": "STROKES",
    "BURACO": "HOLE",
    "PAR": "PAR",
    "BURACO {n}": "HOLE {n}",
    "PAR {n}": "PAR {n}",
    "BURACO {n}/{total}": "HOLE {n}/{total}",
    "TACADAS: {n}": "STROKES: {n}",
    "TOTAL: {n}": "TOTAL: {n}",
    "CURSO COMPLETO!": "COURSE COMPLETE!",
    "{n} TACADAS": "{n} STROKES",
    "{n} TACADA": "{n} STROKE",
    "+1 TACADA": "+1 STROKE",
    "TOTAL: {n}   (PAR {par})": "TOTAL: {n}   (PAR {par})",
    "RÁPIDO DEMAIS!": "TOO FAST!",
    "BURACO EM UM!": "HOLE IN ONE!",
    "ÁGUIA!": "EAGLE!",
    "PASSARINHO!": "BIRDIE!",
    "NO PAR!": "PAR!",
    "QUASE!": "BOGEY!",
    "CONSEGUIU!": "IN THE HOLE!",
    "LIMITE DE TACADAS": "STROKE LIMIT",

    # --- OVO KOMBAT ---
    "OVO KOMBAT": "EGG KOMBAT",
    "Luta de fliperama com os ovos da sua rua! Socos, chutes, especiais e um FATALOVO fofo.":
        "Arcade fighting with your street's eggs! Punches, kicks, specials and a cute EGGALITY.",
    "ESCOLHA SEU LUTADOR! MELHOR DE 3 ROUNDS, 60 S CADA.": "CHOOSE YOUR FIGHTER! BEST OF 3 ROUNDS, 60 S EACH.",
    "J1: WASD, ESPAÇO SOCO, F CHUTE, G BLOQUEIA": "P1: WASD, SPACE PUNCH, F KICK, G BLOCK",
    "J2: SETAS, ENTER SOCO, SHIFT DIR. CHUTE, CTRL DIR. BLOQUEIA": "P2: ARROWS, ENTER PUNCH, R.SHIFT KICK, R.CTRL BLOCK",
    "ESPECIAL: BAIXO, FRENTE + SOCO": "SPECIAL: DOWN, FORWARD + PUNCH",
    "FINALIZE-O: FRENTE, FRENTE, BAIXO + CHUTE = FATALOVO!": "FINISH HIM: FWD, FWD, DOWN + KICK = EGGALITY!",
    "WASD + ESPAÇO/F/G": "WASD + SPACE/F/G",
    "SETAS + ENTER/SHIFT/CTRL": "ARROWS + ENTER/SHIFT/CTRL",
    "OVO": "EGG",
    "OVO {n}": "EGG {n}",
    "VOCÊ": "YOU",
    "{nome} VENCE!": "{nome} WINS!",
    "ESCOLHA SEU LUTADOR": "CHOOSE YOUR FIGHTER",
    "A/D + ESPAÇO": "A/D + SPACE",
    "ROUND DE {nome}": "{nome}'S ROUND",
    "FATALOVO! OMELETE FOFINHO!": "EGGALITY! FLUFFY OMELET!",
    "FRENTE, FRENTE, BAIXO + CHUTE": "FWD, FWD, DOWN + KICK",
    "ESPECIAL:": "SPECIAL:",
    "{n} GOLPES!": "{n} HITS!",
    "VEL": "SPD",
    "FOR": "STR",
    "PULO": "JMP",
    "LIMÃO DE FOGO": "FIRE LEMON",
    "INVESTIDA CASCUDA": "SHELL CHARGE",
    "GANCHO DE GEMA": "YOLK UPPERCUT",
    "TELEPORTE DE CLARA": "EGG WHITE WARP",
    "RASTEIRA ESCORREGADIA": "SLIPPERY SWEEP",
    "TEMPO!": "TIME!",
    "K.O.!": "K.O.!",
    "FINALIZE-O!": "FINISH HIM!",
    "FATALOVO!": "EGGALITY!",
    "OMELETE FOFINHO!": "FLUFFY OMELET!",
    "LUTE!": "FIGHT!",

    # --- SUMÔ ---
    "SUMÔ DE OVOS": "EGG SUMO",
    "SUMÔ": "SUMO",
    "Empurre o outro ovo para fora do tatame! Investida, finque o pé e não caia do ringue.":
        "Push the other egg off the mat! Charge, dig in and don't fall out of the ring.",
    "Empurre o outro ovo para fora do ringue! Quem cair perde o round.":
        "Push the other egg out of the ring! Whoever falls loses the round.",
    "Cada round perdido racha o ovo: 3 rachaduras e acabou!": "Each lost round cracks the egg: 3 cracks and it's over!",
    "INVESTIDA = empurrão forte • FINCAR O PÉ (segure) = fica pesadão":
        "CHARGE = big shove • DIG IN (hold) = get super heavy",
    "J1: ESPAÇO/F investe, G finca • J2: ENTER/. investe, SHIFT finca":
        "P1: SPACE/F charge, G dig in • P2: ENTER/. charge, SHIFT dig in",
    "TATAME": "MAT",
    "GELO": "ICE",
    "ENCOLHE": "SHRINK",
    "WASD + ESPAÇO + G": "WASD + SPACE + G",
    "SETAS + ENTER + SHIFT": "ARROWS + ENTER + SHIFT",
    "HAI!": "HAI!",
    "HAKKEYOI!": "HAKKEYOI!",
    "MORTE SÚBITA!": "SUDDEN DEATH!",
    "EMPATE! DE NOVO!": "TIE! AGAIN!",
    "{nome} VENCE A LUTA!": "{nome} WINS THE BOUT!",
    "{nome} VENCE O ROUND!": "{nome} WINS THE ROUND!",
    "PIMENTA!": "PEPPER!",
    "BIGORNA!": "ANVIL!",
    "POF!": "POF!",
    "O RINGUE ESTÁ ENCOLHENDO!": "THE RING IS SHRINKING!",

    # --- ESTOURA-BOLHAS ---
    "ESTOURA-BOLHAS": "BUBBLE POP",
    "BOLHAS": "BUBBLES",
    "Seu ovo sopra bolhas de chiclete! Junte 3 da mesma cor para estourar e solte os pintinhos.":
        "Your egg blows bubblegum bubbles! Match 3 of a color to pop them and free the chicks.",
    "Sopre bolhas: junte 3 da mesma cor para estourar!": "Blow bubbles: match 3 of a color to pop!",
    "Bolhas soltas do teto caem e valem o dobro.": "Bubbles cut loose from the top fall for double.",
    "Solte todos os PINTINHOS para passar de fase.": "Free all the CHICKS to clear the stage.",
    "Errou 6 vezes seguidas? O teto desce!": "Miss 6 times in a row? The ceiling drops!",
    "←→/A D ou MOUSE mira • ESPAÇO sopra • ↓/S troca": "←→/A D or MOUSE aim • SPACE blow • ↓/S swap",
    "FÁCIL (4 CORES)": "EASY (4 COLORS)",
    "MÉDIO (5)": "MEDIUM (5)",
    "DIFÍCIL (6)": "HARD (6)",
    "piu!": "cheep!",
    "O TETO DESCEU!": "THE CEILING DROPPED!",
    "FASE LIMPA!": "STAGE CLEAR!",
    "AS BOLHAS CHEGARAM!": "THE BUBBLES MADE IT!",
    "PRÓXIMA": "NEXT",
    "TETO": "CEILING",
    "FASE {n}": "STAGE {n}",
    "FASE: {n}": "STAGE: {n}",
    "PINTINHOS SALVOS: {n}": "CHICKS SAVED: {n}",

    # --- OVO NA ESTRADA ---
    "OVO NA ESTRADA": "EGG ON THE ROAD",
    "ESTRADA": "ROAD",
    "Pilote o buggy-casca pelos morros, cuide da gasolina e dê cambalhotas. Não capote!":
        "Drive the shell buggy over the hills, watch your gas and do flips. Don't crash!",
    "Pilote o buggy-casca pelos morros!": "Drive the shell buggy over the hills!",
    "Pegue os GALÕES antes da gasolina acabar.": "Grab GAS CANS before you run out.",
    "Cada moeda da pista vale 1 OVOEDA de verdade!": "Each coin on the track is worth 1 real EGGCOIN!",
    "No ar ← e → giram: cambalhota vale +50. Não capote!": "In the air ← and → spin: a flip is +50. Don't crash!",
    "→/D acelera • ←/A freia e dá ré (mouse: dir./esq.)": "→/D gas • ←/A brake and reverse (mouse: R/L)",
    "CAMBALHOTA!": "FLIP!",
    "{n}× CAMBALHOTA!": "{n}× FLIP!",
    "CRACK!": "CRACK!",
    "DISTÂNCIA: {n} m": "DISTANCE: {n} m",
    "CAMBALHOTAS: {n}": "FLIPS: {n}",
    "MOEDAS DA PISTA: {n}": "TRACK COINS: {n}",
    "GASOLINA!": "GAS!",
    "SEGURE → PARA ACELERAR!": "HOLD → TO SPEED UP!",
    "SEM GASOLINA!": "OUT OF GAS!",

    # --- SALTO NO LAGO ---
    "SALTO NO LAGO": "POND HOP",
    "LAGO": "POND",
    "Segure para carregar e solte para pular de vitória-régia em vitória-régia. Acerte o centro!":
        "Hold to charge and release to hop from lily pad to lily pad. Aim for the center!",
    "SEGURE para carregar o pulo e SOLTE para saltar!": "HOLD to charge the jump and RELEASE to hop!",
    "Cair no meio da folha é PERFEITO (+2 e combo).": "Landing mid-pad is PERFECT (+2 and combo).",
    "Cuidado: folha seca afunda e a tartaruga mergulha.": "Careful: dry pads sink and the turtle dives.",
    "A BOIA salva você de uma queda na água.": "The FLOATIE saves you from one splash.",
    "ESPAÇO, ↑, W ou CLIQUE: segurar e soltar": "SPACE, ↑, W or CLICK: hold and release",
    "SALTOS {n}": "HOPS {n}",
    "BOIA!": "FLOATIE!",
    "SALVO PELA BOIA!": "SAVED BY THE FLOATIE!",
    "SEGURE E SOLTE!": "HOLD AND RELEASE!",
    "BOIA": "FLOAT",
    "PERFEITO!": "PERFECT!",
    "PERFEITO x{n}!": "PERFECT x{n}!",
    "MOLA! +3": "SPRING! +3",
    "SALTOS: {n}  PERFEITOS: {p}": "HOPS: {n}  PERFECT: {p}",

    # --- LIGA-OVOS ---
    "LIGA-OVOS": "EGG LINK",
    "Ache dois parentes iguais do seu ovo e ligue-os com até 2 curvas antes do tempo acabar!":
        "Find two matching egg relatives and link them with up to 2 turns before time runs out!",
    "Clique em dois ovos IGUAIS da família.": "Click two MATCHING family eggs.",
    "Se uma linha com até 2 curvas ligar os dois, eles somem!": "If a line with up to 2 turns links them, they vanish!",
    "O SEU ovo vale o dobro. Pares rápidos fazem COMBO!": "YOUR egg is worth double. Quick pairs make COMBOS!",
    "Limpe tudo antes do tempo acabar. H = DICA.": "Clear it all before time runs out. H = HINT.",
    "MOUSE ou SETAS/WASD + ESPAÇO • H dica": "MOUSE or ARROWS/WASD + SPACE • H hint",
    "NÍVEL {n} COMPLETO!": "LEVEL {n} COMPLETE!",
    "BÔNUS DE TEMPO: +{n}": "TIME BONUS: +{n}",
    "NÍVEL {n}: {modo}": "LEVEL {n}: {modo}",
    "TEMPO: {v}": "TIME: {v}",
    "NÍVEL": "LEVEL",
    "DICA (H)": "HINT (H)",
    "EMBARALHANDO!": "SHUFFLING!",
    "SEM CAMINHO!": "NO PATH!",
    "VOCÊ! +{n}": "YOU! +{n}",
    "NÍVEL: {n}  •  PARES: {p}": "LEVEL: {n}  •  PAIRS: {p}",
    "AS PEÇAS FICAM PARADAS": "TILES STAY PUT",
    "AS PEÇAS CAEM!": "TILES FALL!",
    "AS PEÇAS VÃO PARA A ESQUERDA!": "TILES SLIDE LEFT!",
    "AS PEÇAS VÃO PARA O CENTRO!": "TILES SLIDE TO THE CENTER!",

    # --- CHUVA DE COMIDA ---
    "CHUVA DE COMIDA": "FOOD RAIN",
    "CHUVA": "RAIN",
    "Está chovendo comida na cozinha! Pegue tudo de boca aberta e fuja da pimenta e da bomba.":
        "It's raining food in the kitchen! Catch it all mouth-first and dodge the pepper and bomb.",
    "Pegue as comidas com a boca do seu ovo!": "Catch the food with your egg's mouth!",
    "Pegar várias seguidas faz COMBO (x2 e x3).": "Catching several in a row makes a COMBO (x2 and x3).",
    "A ESTRELA vale 5! PIMENTA e BOMBA tiram vida.": "The STAR is worth 5! PEPPER and BOMB hurt.",
    "SETAS, A D ou o MOUSE para mover": "ARROWS, A D or the MOUSE to move",
    "ARDEU!": "SPICY!",
    "COMBO PERDIDO": "COMBO LOST",

    # --- REI DO QUINTAL ---
    "REI DO QUINTAL": "KING OF THE YARD",
    "REI QUINTAL": "YARD KING",
    "Fique sozinho na zona da coroa para somar pontos! Empurre, escorregue e arremesse o rival.":
        "Stand alone in the crown zone to score! Shove, slip and fling your rival.",
    "Fique SOZINHO na zona da COROA para somar pontos. Ela muda a cada 20 s!":
        "Stay ALONE in the CROWN zone to score. It moves every 20 s!",
    "INVESTIDA empurra e atordoa. Pegue itens: BANANA (escorrega) e MOLA (arremessa).":
        "CHARGE shoves and stuns. Grab items: BANANA (slip) and SPRING (fling).",
    "J1: WASD, ESPAÇO investida, F item • J2: SETAS, ENTER investida, SHIFT DIR. item":
        "P1: WASD, SPACE charge, F item • P2: ARROWS, ENTER charge, R.SHIFT item",
    "Primeiro a 30 pontos ou mais pontos em 90 s.": "First to 30 points, or most points in 90 s.",
    "WASD + ESPAÇO/F": "WASD + SPACE/F",
    "SETAS + ENTER/SHIFT": "ARROWS + ENTER/SHIFT",
    "PONTOS  {a} × {b}": "POINTS  {a} × {b}",
    "EMPURRÕES  {a} × {b}": "SHOVES  {a} × {b}",
    "META {n}": "GOAL {n}",
    "COROA COM {n} PONTOS!": "CROWNED WITH {n} POINTS!",
    "A COROA MUDOU!": "THE CROWN MOVED!",
    "POW!": "POW!",
    "DISPUTA!": "CONTESTED!",
    "ESCORREGOU!": "SLIPPED!",

    # --- EGG FIGHTER ---
    "EGG FIGHTER": "EGG FIGHTER",
    "Luta de dedão com ovos! Prenda o ovo do outro por 3 segundos para vencer.":
        "Thumb wrestling with eggs! Pin the other egg for 3 seconds to win.",
    "INCLINE (ESQ/DIR), ESTIQUE (CIMA) E ESQUIVE (BAIXO).": "LEAN (LEFT/RIGHT), STRETCH (UP) AND DODGE (DOWN).",
    "ATAQUE (J1 ESPAÇO / J2 ENTER) E CAIA POR CIMA DO OUTRO OVO!": "ATTACK (P1 SPACE / P2 ENTER) AND LAND ON THE OTHER EGG!",
    "SEGURE A TECLA 3 S PARA VENCER O ROUND. PRESO? APERTE TUDO PARA FUGIR!":
        "HOLD THE KEY 3 S TO WIN THE ROUND. PINNED? MASH EVERYTHING TO ESCAPE!",
    "MELHOR DE 3.": "BEST OF 3.",
    "UM,": "ONE,",
    "DOIS,": "TWO,",
    "TRÊS,": "THREE,",
    "QUATRO...": "FOUR...",
    "GUERRA DE DEDÃO!": "THUMB WAR!",
    "SOLTOU!": "LET GO!",
    "PRESO!": "PINNED!",
    "ESCAPOU!": "ESCAPED!",
    "PEGOU!": "GOTCHA!",
    "PONTO DE {nome}": "POINT FOR {nome}",
    "ESQUIVOU!": "DODGED!",
    "NINGUÉM PONTUA": "NO ONE SCORES",
    "BATEU!": "BONK!",
    "APERTE TUDO!": "MASH IT ALL!",
}

ES = {
    # --- Comuns (HUD / fim) ---
    "PONTOS": "PUNTOS",
    "PONTOS: {n}": "PUNTOS: {n}",
    "RECORDE: {v}": "RÉCORD: {v}",
    "MAIOR COMBO: {n}": "MEJOR COMBO: {n}",
    "MAIOR COMBO: ×{n}": "MEJOR COMBO: ×{n}",
    "O TEMPO ACABOU!": "¡SE ACABÓ EL TIEMPO!",
    "ROUND {n}": "RONDA {n}",
    "ROUNDS  {a} × {b}": "RONDAS  {a} × {b}",
    "GLUB!": "¡GLUB!",
    "BUM!": "¡BUM!",
    "BOING!": "¡BOING!",

    # --- base_multi (2 jugadores) ---
    "WASD + ESPAÇO": "WASD + ESPACIO",
    "SETAS + ENTER": "FLECHAS + ENTER",
    "VIZINHO": "VECINO",
    "J2: {nome} (CASA {n})": "J2: {nome} (CASA {n})",
    "J2: SORTEADO": "J2: AL AZAR",
    "JOGADOR 1": "JUGADOR 1",
    "JOGADOR 2": "JUGADOR 2",
    "EMPATE!": "¡EMPATE!",
    "{nome} VENCEU!": "¡{nome} GANÓ!",
    "VITÓRIAS  J1 {a} × {b} J2": "VICTORIAS  J1 {a} × {b} J2",
    "COR DO J2 TROCADA NESTA PARTIDA": "COLOR DEL J2 CAMBIADO EN ESTA PARTIDA",
    "PARA {nome}": "PARA {nome}",
    "2 JOGADORES": "2 JUGADORES",
    "ESCOLHA O MODO:": "ELIGE EL MODO:",
    "ESCOLHA O MODO": "ELIGE EL MODO",
    "VS BOT OU 2 JOGADORES": "VS BOT O 2 JUGADORES",
    "J1": "J1",
    "J2": "J2",
    "J{n}": "J{n}",

    # --- trofeus ---
    "{n} partidas": "{n} partidas",
    "venceu {modo}": "ganó en {modo}",
    "recorde {v}": "récord {v}",
    "Jogue {nome} com um amigo e VENÇA!": "¡Juega {nome} con un amigo y GANA!",
    "Vença uma partida de {nome}!": "¡Gana una partida de {nome}!",
    "Faça {v} ou menos em {nome}!": "¡Haz {v} o menos en {nome}!",
    "Faça {v} em {nome}!": "¡Haz {v} en {nome}!",

    # --- MICRO-OVO ---
    "MICRO-OVO": "MICRO-HUEVO",
    "Microjogos de 4 segundos em sequência! Leia a ordem gigante e faça rápido.":
        "¡Microjuegos de 4 segundos seguidos! Lee la orden gigante y hazla rápido.",
    "Microjogos de 4 segundos, um atrás do outro!": "¡Microjuegos de 4 segundos, uno tras otro!",
    "Leia a ORDEM gigante e faça rápido.": "Lee la ORDEN gigante y hazla rápido.",
    "Errou? Perde um ovo. São 4 ovos de vida.": "¿Fallaste? Pierdes un huevo. Tienes 4.",
    "A cada 5 rodadas fica MAIS RÁPIDO!": "¡Cada 5 rondas va MÁS RÁPIDO!",
    "SETAS/WASD, ESPAÇO e MOUSE": "FLECHAS/WASD, ESPACIO y MOUSE",
    "NORMAL": "NORMAL",
    "TURBO": "TURBO",
    "RODADAS": "RONDAS",
    "JÁ!": "¡YA!",
    "PEGUE!": "¡ATRAPA!",
    "← →  OU  MOUSE": "← →  O  MOUSE",
    "DESVIE!": "¡ESQUIVA!",
    "ESTOURE!": "¡REVIENTA!",
    "CLIQUE NAS BOLHAS": "HAZ CLIC EN LAS BURBUJAS",
    "PULE!": "¡SALTA!",
    "ESPAÇO, ↑ OU CLIQUE": "ESPACIO, ↑ O CLIC",
    "LIMPE!": "¡LIMPIA!",
    "ESFREGUE COM O MOUSE": "FROTA CON EL MOUSE",
    "APERTE!": "¡PULSA!",
    "AS SETAS NA ORDEM": "LAS FLECHAS EN ORDEN",
    "PARE!": "¡PARA!",
    "NO VERDE! ESPAÇO OU CLIQUE": "¡EN EL VERDE! ESPACIO O CLIC",
    "ACHE!": "¡BUSCA!",
    "O OVO DIFERENTE": "EL HUEVO DISTINTO",
    "SOPRE!": "¡SOPLA!",
    "APERTE ESPAÇO RÁPIDO!": "¡PULSA ESPACIO RÁPIDO!",
    "GUIE!": "¡GUÍA!",
    "LEVE A ABELHA ATÉ A FLOR": "LLEVA LA ABEJA A LA FLOR",
    "ACORDE!": "¡DESPIERTA!",
    "← → ← →  OU CHACOALHE O MOUSE": "← → ← →  O SACUDE EL MOUSE",
    "CONTE!": "¡CUENTA!",
    "QUANTOS PINTINHOS?": "¿CUÁNTOS POLLITOS?",
    "ENCHA!": "¡LLENA!",
    "SEGURE ESPAÇO E SOLTE NA LINHA": "MANTÉN ESPACIO Y SUELTA EN LA LÍNEA",
    "LINHA": "LÍNEA",
    "LENDA DOS MICROS!": "¡LEYENDA DE LOS MICROS!",
    "MANDOU BEM!": "¡MUY BIEN!",
    "ACABARAM OS OVOS!": "¡SIN HUEVOS!",
    "RODADAS VENCIDAS: {n}": "RONDAS GANADAS: {n}",
    "RODADAS JOGADAS: {n}": "RONDAS JUGADAS: {n}",
    "VELOCIDADE MÁXIMA: {v}": "VELOCIDAD MÁXIMA: {v}",
    "PONTOS: {n}    VELOCIDADE {v}": "PUNTOS: {n}    VELOCIDAD {v}",
    "VELOCIDADE {v}": "VELOCIDAD {v}",
    "RODADA {n}": "RONDA {n}",
    "FALTAM {n}": "FALTAN {n}",
    "NA MOSCA!": "¡EN EL BLANCO!",
    "PARABÉNS!": "¡FELICIDADES!",
    "MEL!": "¡MIEL!",
    "BOM DIA!": "¡BUENOS DÍAS!",
    "NA MEDIDA!": "¡JUSTO!",
    "PASSOU!": "¡TE PASASTE!",
    "POP!": "¡POP!",
    "TOING!": "¡TOING!",
    "AI!": "¡AY!",
    "ERAM {n}!": "¡ERAN {n}!",
    "CLANG!": "¡CLANG!",
    "BOA!": "¡BIEN!",
    "FIM!": "¡FIN!",
    "ACABOU...": "SE ACABÓ...",
    "PREPARE-SE!": "¡PREPÁRATE!",
    "MAIS RÁPIDO!": "¡MÁS RÁPIDO!",

    # --- MINI GOLFE ---
    "MINI GOLFE DO OVO": "MINIGOLF DEL HUEVO",
    "MINI GOLFE": "MINIGOLF",
    "O seu ovo é a bolinha! 9 buracos malucos com moinho, água, areia e portais.":
        "¡Tu huevo es la pelota! 9 hoyos locos con molino, agua, arena y portales.",
    "O seu ovo é a bolinha: acerte os 9 buracos!": "Tu huevo es la pelota: ¡mete los 9 hoyos!",
    "Use poucas tacadas. Água custa +1 tacada.": "Usa pocos golpes. El agua cuesta +1 golpe.",
    "Setas dão velocidade e os portais teletransportam.": "Las flechas dan velocidad y los portales teletransportan.",
    "← → (ou A D) mira, SHIFT = mira fina": "← → (o A D) apunta, SHIFT = mira fina",
    "ESPAÇO: segure e solte • MOUSE: puxe e solte": "ESPACIO: mantén y suelta • MOUSE: tira y suelta",
    "TACADAS": "GOLPES",
    "BURACO": "HOYO",
    "PAR": "PAR",
    "BURACO {n}": "HOYO {n}",
    "PAR {n}": "PAR {n}",
    "BURACO {n}/{total}": "HOYO {n}/{total}",
    "TACADAS: {n}": "GOLPES: {n}",
    "TOTAL: {n}": "TOTAL: {n}",
    "CURSO COMPLETO!": "¡RECORRIDO COMPLETO!",
    "{n} TACADAS": "{n} GOLPES",
    "{n} TACADA": "{n} GOLPE",
    "+1 TACADA": "+1 GOLPE",
    "TOTAL: {n}   (PAR {par})": "TOTAL: {n}   (PAR {par})",
    "RÁPIDO DEMAIS!": "¡DEMASIADO RÁPIDO!",
    "BURACO EM UM!": "¡HOYO EN UNO!",
    "ÁGUIA!": "¡ÁGUILA!",
    "PASSARINHO!": "¡BIRDIE!",
    "NO PAR!": "¡EN PAR!",
    "QUASE!": "¡CASI!",
    "CONSEGUIU!": "¡LO LOGRASTE!",
    "LIMITE DE TACADAS": "LÍMITE DE GOLPES",

    # --- OVO KOMBAT ---
    "OVO KOMBAT": "HUEVO KOMBAT",
    "Luta de fliperama com os ovos da sua rua! Socos, chutes, especiais e um FATALOVO fofo.":
        "¡Peleas arcade con los huevos de tu calle! Puños, patadas, especiales y un FATALHUEVO tierno.",
    "ESCOLHA SEU LUTADOR! MELHOR DE 3 ROUNDS, 60 S CADA.": "¡ELIGE TU LUCHADOR! MEJOR DE 3 RONDAS, 60 S CADA UNA.",
    "J1: WASD, ESPAÇO SOCO, F CHUTE, G BLOQUEIA": "J1: WASD, ESPACIO PUÑO, F PATADA, G BLOQUEA",
    "J2: SETAS, ENTER SOCO, SHIFT DIR. CHUTE, CTRL DIR. BLOQUEIA": "J2: FLECHAS, ENTER PUÑO, SHIFT DER. PATADA, CTRL DER. BLOQUEA",
    "ESPECIAL: BAIXO, FRENTE + SOCO": "ESPECIAL: ABAJO, ADELANTE + PUÑO",
    "FINALIZE-O: FRENTE, FRENTE, BAIXO + CHUTE = FATALOVO!": "ACÁBALO: ADEL., ADEL., ABAJO + PATADA = ¡FATALHUEVO!",
    "WASD + ESPAÇO/F/G": "WASD + ESPACIO/F/G",
    "SETAS + ENTER/SHIFT/CTRL": "FLECHAS + ENTER/SHIFT/CTRL",
    "OVO": "HUEVO",
    "OVO {n}": "HUEVO {n}",
    "VOCÊ": "TÚ",
    "{nome} VENCE!": "¡GANA {nome}!",
    "ESCOLHA SEU LUTADOR": "ELIGE TU LUCHADOR",
    "A/D + ESPAÇO": "A/D + ESPACIO",
    "ROUND DE {nome}": "RONDA DE {nome}",
    "FATALOVO! OMELETE FOFINHO!": "¡FATALHUEVO! ¡TORTILLA ESPONJOSA!",
    "FRENTE, FRENTE, BAIXO + CHUTE": "ADELANTE, ADELANTE, ABAJO + PATADA",
    "ESPECIAL:": "ESPECIAL:",
    "{n} GOLPES!": "¡{n} GOLPES!",
    "VEL": "VEL",
    "FOR": "FUE",
    "PULO": "SAL",
    "LIMÃO DE FOGO": "LIMÓN DE FUEGO",
    "INVESTIDA CASCUDA": "EMBESTIDA CÁSCARA",
    "GANCHO DE GEMA": "GANCHO DE YEMA",
    "TELEPORTE DE CLARA": "TELETRANSPORTE DE CLARA",
    "RASTEIRA ESCORREGADIA": "BARRIDA RESBALOSA",
    "TEMPO!": "¡TIEMPO!",
    "K.O.!": "¡K.O.!",
    "FINALIZE-O!": "¡ACÁBALO!",
    "FATALOVO!": "¡FATALHUEVO!",
    "OMELETE FOFINHO!": "¡TORTILLA ESPONJOSA!",
    "LUTE!": "¡PELEA!",

    # --- SUMÔ ---
    "SUMÔ DE OVOS": "SUMO DE HUEVOS",
    "SUMÔ": "SUMO",
    "Empurre o outro ovo para fora do tatame! Investida, finque o pé e não caia do ringue.":
        "¡Saca al otro huevo del tatami! Embiste, afírmate y no te caigas del ring.",
    "Empurre o outro ovo para fora do ringue! Quem cair perde o round.":
        "¡Empuja al otro huevo fuera del ring! Quien caiga pierde la ronda.",
    "Cada round perdido racha o ovo: 3 rachaduras e acabou!": "Cada ronda perdida agrieta el huevo: ¡3 grietas y se acabó!",
    "INVESTIDA = empurrão forte • FINCAR O PÉ (segure) = fica pesadão":
        "EMBESTIDA = empujón fuerte • AFIRMARSE (mantén) = súper pesado",
    "J1: ESPAÇO/F investe, G finca • J2: ENTER/. investe, SHIFT finca":
        "J1: ESPACIO/F embiste, G se afirma • J2: ENTER/. embiste, SHIFT se afirma",
    "TATAME": "TATAMI",
    "GELO": "HIELO",
    "ENCOLHE": "ENCOGE",
    "WASD + ESPAÇO + G": "WASD + ESPACIO + G",
    "SETAS + ENTER + SHIFT": "FLECHAS + ENTER + SHIFT",
    "HAI!": "¡HAI!",
    "HAKKEYOI!": "¡HAKKEYOI!",
    "MORTE SÚBITA!": "¡MUERTE SÚBITA!",
    "EMPATE! DE NOVO!": "¡EMPATE! ¡OTRA VEZ!",
    "{nome} VENCE A LUTA!": "¡{nome} GANA LA PELEA!",
    "{nome} VENCE O ROUND!": "¡{nome} GANA LA RONDA!",
    "PIMENTA!": "¡CHILE!",
    "BIGORNA!": "¡YUNQUE!",
    "POF!": "¡POF!",
    "O RINGUE ESTÁ ENCOLHENDO!": "¡EL RING SE ENCOGE!",

    # --- ESTOURA-BOLHAS ---
    "ESTOURA-BOLHAS": "REVIENTA-BURBUJAS",
    "BOLHAS": "BURBUJAS",
    "Seu ovo sopra bolhas de chiclete! Junte 3 da mesma cor para estourar e solte os pintinhos.":
        "¡Tu huevo sopla burbujas de chicle! Junta 3 del mismo color para reventarlas y libera a los pollitos.",
    "Sopre bolhas: junte 3 da mesma cor para estourar!": "Sopla burbujas: ¡junta 3 del mismo color para reventar!",
    "Bolhas soltas do teto caem e valem o dobro.": "Las burbujas sueltas del techo caen y valen el doble.",
    "Solte todos os PINTINHOS para passar de fase.": "Libera a todos los POLLITOS para pasar de fase.",
    "Errou 6 vezes seguidas? O teto desce!": "¿Fallaste 6 veces seguidas? ¡El techo baja!",
    "←→/A D ou MOUSE mira • ESPAÇO sopra • ↓/S troca": "←→/A D o MOUSE apunta • ESPACIO sopla • ↓/S cambia",
    "FÁCIL (4 CORES)": "FÁCIL (4 COLORES)",
    "MÉDIO (5)": "MEDIO (5)",
    "DIFÍCIL (6)": "DIFÍCIL (6)",
    "piu!": "¡pío!",
    "O TETO DESCEU!": "¡EL TECHO BAJÓ!",
    "FASE LIMPA!": "¡FASE LIMPIA!",
    "AS BOLHAS CHEGARAM!": "¡LLEGARON LAS BURBUJAS!",
    "PRÓXIMA": "SIGUIENTE",
    "TETO": "TECHO",
    "FASE {n}": "FASE {n}",
    "FASE: {n}": "FASE: {n}",
    "PINTINHOS SALVOS: {n}": "POLLITOS SALVADOS: {n}",

    # --- OVO NA ESTRADA ---
    "OVO NA ESTRADA": "HUEVO EN LA RUTA",
    "ESTRADA": "RUTA",
    "Pilote o buggy-casca pelos morros, cuide da gasolina e dê cambalhotas. Não capote!":
        "Maneja el buggy-cáscara por las colinas, cuida la gasolina y da volteretas. ¡No vuelques!",
    "Pilote o buggy-casca pelos morros!": "¡Maneja el buggy-cáscara por las colinas!",
    "Pegue os GALÕES antes da gasolina acabar.": "Toma los BIDONES antes de quedarte sin gasolina.",
    "Cada moeda da pista vale 1 OVOEDA de verdade!": "¡Cada moneda de la pista vale 1 HUEVONEDA de verdad!",
    "No ar ← e → giram: cambalhota vale +50. Não capote!": "En el aire ← y → giran: voltereta vale +50. ¡No vuelques!",
    "→/D acelera • ←/A freia e dá ré (mouse: dir./esq.)": "→/D acelera • ←/A frena y retrocede (mouse: der./izq.)",
    "CAMBALHOTA!": "¡VOLTERETA!",
    "{n}× CAMBALHOTA!": "¡{n}× VOLTERETA!",
    "CRACK!": "¡CRAC!",
    "DISTÂNCIA: {n} m": "DISTANCIA: {n} m",
    "CAMBALHOTAS: {n}": "VOLTERETAS: {n}",
    "MOEDAS DA PISTA: {n}": "MONEDAS DE PISTA: {n}",
    "GASOLINA!": "¡GASOLINA!",
    "SEGURE → PARA ACELERAR!": "¡MANTÉN → PARA ACELERAR!",
    "SEM GASOLINA!": "¡SIN GASOLINA!",

    # --- SALTO NO LAGO ---
    "SALTO NO LAGO": "SALTO EN EL LAGO",
    "LAGO": "LAGO",
    "Segure para carregar e solte para pular de vitória-régia em vitória-régia. Acerte o centro!":
        "Mantén para cargar y suelta para saltar de nenúfar en nenúfar. ¡Apunta al centro!",
    "SEGURE para carregar o pulo e SOLTE para saltar!": "¡MANTÉN para cargar el salto y SUELTA para saltar!",
    "Cair no meio da folha é PERFEITO (+2 e combo).": "Caer en medio de la hoja es PERFECTO (+2 y combo).",
    "Cuidado: folha seca afunda e a tartaruga mergulha.": "Cuidado: la hoja seca se hunde y la tortuga se sumerge.",
    "A BOIA salva você de uma queda na água.": "El SALVAVIDAS te salva de una caída al agua.",
    "ESPAÇO, ↑, W ou CLIQUE: segurar e soltar": "ESPACIO, ↑, W o CLIC: mantener y soltar",
    "SALTOS {n}": "SALTOS {n}",
    "BOIA!": "¡SALVAVIDAS!",
    "SALVO PELA BOIA!": "¡TE SALVÓ EL SALVAVIDAS!",
    "SEGURE E SOLTE!": "¡MANTÉN Y SUELTA!",
    "BOIA": "BOYA",
    "PERFEITO!": "¡PERFECTO!",
    "PERFEITO x{n}!": "¡PERFECTO x{n}!",
    "MOLA! +3": "¡RESORTE! +3",
    "SALTOS: {n}  PERFEITOS: {p}": "SALTOS: {n}  PERFECTOS: {p}",

    # --- LIGA-OVOS ---
    "LIGA-OVOS": "UNE-HUEVOS",
    "Ache dois parentes iguais do seu ovo e ligue-os com até 2 curvas antes do tempo acabar!":
        "¡Encuentra dos parientes iguales de tu huevo y únelos con hasta 2 curvas antes de que acabe el tiempo!",
    "Clique em dois ovos IGUAIS da família.": "Haz clic en dos huevos IGUALES de la familia.",
    "Se uma linha com até 2 curvas ligar os dois, eles somem!": "¡Si una línea con hasta 2 curvas los une, desaparecen!",
    "O SEU ovo vale o dobro. Pares rápidos fazem COMBO!": "TU huevo vale el doble. ¡Pares rápidos hacen COMBO!",
    "Limpe tudo antes do tempo acabar. H = DICA.": "Limpia todo antes de que acabe el tiempo. H = PISTA.",
    "MOUSE ou SETAS/WASD + ESPAÇO • H dica": "MOUSE o FLECHAS/WASD + ESPACIO • H pista",
    "NÍVEL {n} COMPLETO!": "¡NIVEL {n} COMPLETO!",
    "BÔNUS DE TEMPO: +{n}": "BONO DE TIEMPO: +{n}",
    "NÍVEL {n}: {modo}": "NIVEL {n}: {modo}",
    "TEMPO: {v}": "TIEMPO: {v}",
    "NÍVEL": "NIVEL",
    "DICA (H)": "PISTA (H)",
    "EMBARALHANDO!": "¡MEZCLANDO!",
    "SEM CAMINHO!": "¡SIN CAMINO!",
    "VOCÊ! +{n}": "¡TÚ! +{n}",
    "NÍVEL: {n}  •  PARES: {p}": "NIVEL: {n}  •  PARES: {p}",
    "AS PEÇAS FICAM PARADAS": "LAS FICHAS NO SE MUEVEN",
    "AS PEÇAS CAEM!": "¡LAS FICHAS CAEN!",
    "AS PEÇAS VÃO PARA A ESQUERDA!": "¡LAS FICHAS VAN A LA IZQUIERDA!",
    "AS PEÇAS VÃO PARA O CENTRO!": "¡LAS FICHAS VAN AL CENTRO!",

    # --- CHUVA DE COMIDA ---
    "CHUVA DE COMIDA": "LLUVIA DE COMIDA",
    "CHUVA": "LLUVIA",
    "Está chovendo comida na cozinha! Pegue tudo de boca aberta e fuja da pimenta e da bomba.":
        "¡Llueve comida en la cocina! Atrapa todo con la boca abierta y huye del chile y la bomba.",
    "Pegue as comidas com a boca do seu ovo!": "¡Atrapa la comida con la boca de tu huevo!",
    "Pegar várias seguidas faz COMBO (x2 e x3).": "Atrapar varias seguidas hace COMBO (x2 y x3).",
    "A ESTRELA vale 5! PIMENTA e BOMBA tiram vida.": "¡La ESTRELLA vale 5! CHILE y BOMBA quitan vida.",
    "SETAS, A D ou o MOUSE para mover": "FLECHAS, A D o el MOUSE para moverte",
    "ARDEU!": "¡PICA!",
    "COMBO PERDIDO": "COMBO PERDIDO",

    # --- REI DO QUINTAL ---
    "REI DO QUINTAL": "REY DEL PATIO",
    "REI QUINTAL": "REY PATIO",
    "Fique sozinho na zona da coroa para somar pontos! Empurre, escorregue e arremesse o rival.":
        "¡Quédate solo en la zona de la corona para sumar puntos! Empuja, resbala y lanza al rival.",
    "Fique SOZINHO na zona da COROA para somar pontos. Ela muda a cada 20 s!":
        "Quédate SOLO en la zona de la CORONA para sumar. ¡Cambia cada 20 s!",
    "INVESTIDA empurra e atordoa. Pegue itens: BANANA (escorrega) e MOLA (arremessa).":
        "La EMBESTIDA empuja y aturde. Toma objetos: PLÁTANO (resbala) y RESORTE (lanza).",
    "J1: WASD, ESPAÇO investida, F item • J2: SETAS, ENTER investida, SHIFT DIR. item":
        "J1: WASD, ESPACIO embiste, F objeto • J2: FLECHAS, ENTER embiste, SHIFT DER. objeto",
    "Primeiro a 30 pontos ou mais pontos em 90 s.": "El primero a 30 puntos o más puntos en 90 s.",
    "WASD + ESPAÇO/F": "WASD + ESPACIO/F",
    "SETAS + ENTER/SHIFT": "FLECHAS + ENTER/SHIFT",
    "PONTOS  {a} × {b}": "PUNTOS  {a} × {b}",
    "EMPURRÕES  {a} × {b}": "EMPUJONES  {a} × {b}",
    "META {n}": "META {n}",
    "COROA COM {n} PONTOS!": "¡CORONA CON {n} PUNTOS!",
    "A COROA MUDOU!": "¡LA CORONA SE MOVIÓ!",
    "POW!": "¡POW!",
    "DISPUTA!": "¡DISPUTA!",
    "ESCORREGOU!": "¡RESBALÓ!",

    # --- EGG FIGHTER ---
    "EGG FIGHTER": "EGG FIGHTER",
    "Luta de dedão com ovos! Prenda o ovo do outro por 3 segundos para vencer.":
        "¡Lucha de pulgares con huevos! Atrapa el huevo del otro por 3 segundos para ganar.",
    "INCLINE (ESQ/DIR), ESTIQUE (CIMA) E ESQUIVE (BAIXO).": "INCLINA (IZQ/DER), ESTIRA (ARRIBA) Y ESQUIVA (ABAJO).",
    "ATAQUE (J1 ESPAÇO / J2 ENTER) E CAIA POR CIMA DO OUTRO OVO!": "¡ATACA (J1 ESPACIO / J2 ENTER) Y CAE SOBRE EL OTRO HUEVO!",
    "SEGURE A TECLA 3 S PARA VENCER O ROUND. PRESO? APERTE TUDO PARA FUGIR!":
        "MANTÉN LA TECLA 3 S PARA GANAR LA RONDA. ¿ATRAPADO? ¡PULSA TODO PARA HUIR!",
    "MELHOR DE 3.": "MEJOR DE 3.",
    "UM,": "UNO,",
    "DOIS,": "DOS,",
    "TRÊS,": "TRES,",
    "QUATRO...": "CUATRO...",
    "GUERRA DE DEDÃO!": "¡GUERRA DE PULGARES!",
    "SOLTOU!": "¡SOLTÓ!",
    "PRESO!": "¡ATRAPADO!",
    "ESCAPOU!": "¡ESCAPÓ!",
    "PEGOU!": "¡TE TENGO!",
    "PONTO DE {nome}": "PUNTO DE {nome}",
    "ESQUIVOU!": "¡ESQUIVÓ!",
    "NINGUÉM PONTUA": "NADIE PUNTÚA",
    "BATEU!": "¡CHOCARON!",
    "APERTE TUDO!": "¡PULSA TODO!",
}
