# Traducoes (ver o guia em core/idioma.py). Chave = texto ORIGINAL em portugues.
# Arquivos: jogos/base.py (base de todos os minijogos), ovo_sobrevivente, ninho_arrumado,
# ovo_corredor, ovo_man, ovo_ritmo, ovo_bomba, ovotris, boliche, xadegg, dardos, quatro_linha.

EN = {
    # ---------------- jogos/base.py (todos os minijogos) ----------------
    "MINI JOGO": "MINI GAME",
    "PONTOS": "POINTS",
    "JOGAR!": "PLAY!",
    "VOLTAR": "BACK",
    "CONTINUAR": "RESUME",
    "REINICIAR": "RESTART",
    "JOGAR DE NOVO": "PLAY AGAIN",
    "DIFICULDADE": "DIFFICULTY",
    "MENU DE JOGOS": "GAMES MENU",
    "VOCÊ VENCEU!": "YOU WON!",
    "FIM DE JOGO": "GAME OVER",
    "NINGUÉM JOGOU: SEM OVOEDAS": "NOBODY PLAYED: NO EGGCOINS",
    "PARTIDA CURTA: +{n}": "SHORT MATCH: +{n}",
    "JOGUE MAIS DE {n} s": "PLAY OVER {n} s",
    "PARTIDA +{n}": "MATCH +{n}",
    "1ª DO DIA +{n}": "1ST OF DAY +{n}",
    "RECORDE +{n}": "RECORD +{n}",
    "BÔNUS ×{n}": "BONUS ×{n}",
    "BRONZE": "BRONZE",
    "PRATA": "SILVER",
    "OURO": "GOLD",
    "{nome}: FAÇA {n} OU MENOS": "{nome}: GET {n} OR LESS",
    "FALTAM {n} PARA O {nome}!": "{n} MORE FOR {nome}!",
    "RECORDE: {n}": "RECORD: {n}",
    "★ RECORDE: {n} ★": "★ RECORD: {n} ★",
    "★ SEM RECORDE AINDA ★": "★ NO RECORD YET ★",
    "ESCOLHA A DIFICULDADE": "CHOOSE THE DIFFICULTY",
    "VENCER {op}": "BEAT {op}",
    "{n} PARTIDA": "{n} MATCH",
    "{n} PARTIDAS": "{n} MATCHES",
    "{n} OU MENOS": "{n} OR LESS",
    "PREPARE-SE!": "GET READY!",
    "VAI!": "GO!",
    "PAUSADO": "PAUSED",
    "NÍVEL {n}": "LEVEL {n}",
    "MEDALHA NOVA!": "NEW MEDAL!",
    "MOEDAS": "COINS",
    "★ NOVO RECORDE! ★": "★ NEW RECORD! ★",

    # ---------------- Comuns a vários jogos ----------------
    "FÁCIL": "EASY",
    "NORMAL": "NORMAL",
    "MÉDIO": "MEDIUM",
    "DIFÍCIL": "HARD",
    "PONTOS: {n}": "POINTS: {n}",
    "NÍVEL: {n}": "LEVEL: {n}",
    "NÍVEL {n}!": "LEVEL {n}!",
    "2 JOGADORES": "2 PLAYERS",
    "VS {nome}": "VS {nome}",
    "ESCOLHA O MODO": "CHOOSE THE MODE",
    "FORÇA": "POWER",
    "EFEITO": "SPIN",
    "TOTAL": "TOTAL",

    # ---------------- Ovo Sobrevivente ----------------
    "OVO SOBREVIVENTE": "SURVIVOR EGG",
    "SOBREVIVENTE": "SURVIVOR",
    "Sobreviva 3 minutos contra a cozinha rebelde! O ovo joga limões sozinho; escolha melhorias.":
        "Survive 3 minutes against the rebel kitchen! The egg throws lemons on its own; pick upgrades.",
    "Colheres, frigideiras e batedores querem o seu ovo!": "Spoons, pans and whisks are after your egg!",
    "O ovo joga LIMÕES sozinho. Você só ANDA e pega os CRISTAIS.":
        "The egg throws LEMONS by itself. You just WALK and grab CRYSTALS.",
    "Subiu de nível? Escolha 1 de 3 melhorias.": "Leveled up? Pick 1 of 3 upgrades.",
    "Sobreviva 3:00! Aos 2:00 chega o LIQUIDIFICADOR.": "Survive 3:00! At 2:00 the BLENDER arrives.",
    "SETAS/WASD andam • MOUSE segurado • 1 2 3 escolhem": "ARROWS/WASD walk • HOLD MOUSE • 1 2 3 pick",
    "LIMÃO AZEDO": "SOUR LEMON",
    "+30% DE DANO NOS LIMÕES E NA ÓRBITA": "+30% DAMAGE FOR LEMONS AND ORBIT",
    "TIRO RÁPIDO": "QUICK SHOT",
    "JOGA LIMÕES 15% MAIS RÁPIDO": "THROWS LEMONS 15% FASTER",
    "LIMÃO PERFURANTE": "PIERCING LEMON",
    "CADA LIMÃO ATRAVESSA +1 INIMIGO": "EACH LEMON PIERCES +1 ENEMY",
    "MAIS LIMÕES": "MORE LEMONS",
    "+1 LIMÃO EM CADA ARREMESSO": "+1 LEMON PER THROW",
    "LIMÕES EM ÓRBITA": "ORBITING LEMONS",
    "+1 LIMÃO GIRANDO EM VOLTA DO OVO": "+1 LEMON SPINNING AROUND THE EGG",
    "AURA DE SAL": "SALT AURA",
    "SAL EM VOLTA DO OVO: MACHUCA E DEIXA LENTO": "SALT AROUND THE EGG: HURTS AND SLOWS",
    "CASCA GROSSA": "THICK SHELL",
    "+1 CORAÇÃO NO MÁXIMO (E CURA 1)": "+1 MAX HEART (AND HEALS 1)",
    "ÍMÃ DE XP": "XP MAGNET",
    "PEGA CRISTAIS DE BEM MAIS LONGE": "GRABS CRYSTALS FROM WAY FARTHER",
    "PÉS LIGEIROS": "SWIFT FEET",
    "O OVO ANDA 12% MAIS RÁPIDO": "THE EGG WALKS 12% FASTER",
    "LANCHINHO": "SNACK",
    "CURA 2 CORAÇÕES": "HEALS 2 HEARTS",
    "ONDA!": "WAVE!",
    "CUIDADO: O CHEFE VEM AÍ!": "WATCH OUT: BOSS INCOMING!",
    "LIQUIDIFICADOR!": "BLENDER!",
    "LIQUIDIFICADOR": "BLENDER",
    "CHEFE DERROTADO!": "BOSS DEFEATED!",
    "AI!": "OUCH!",
    "+1 CORAÇÃO": "+1 HEART",
    "ÍMÃ!": "MAGNET!",
    "VOCÊ SOBREVIVEU!": "YOU SURVIVED!",
    "O OVO FOI BATIDO!": "THE EGG GOT WHISKED!",
    "TEMPO: {tempo} • NÍVEL {n}": "TIME: {tempo} • LEVEL {n}",
    "INIMIGOS DERROTADOS: {n}": "ENEMIES DEFEATED: {n}",
    "{n} PTS": "{n} PTS",
    "REC {n}": "REC {n}",
    "NV {n}": "LV {n}",
    "SUBIU DE NÍVEL!": "LEVEL UP!",
    "ESCOLHA UMA MELHORIA": "PICK AN UPGRADE",
    "CURA!": "HEAL!",
    "NOVO!": "NEW!",
    "1 2 3 • ← → + ENTER • MOUSE": "1 2 3 • ← → + ENTER • MOUSE",

    # ---------------- Ninho Arrumado ----------------
    "NINHO ARRUMADO": "TIDY NEST",
    "NINHO": "NEST",
    "Os ovinhos bebês se perderam no celeiro! Empurre cada um até um ninho, sem prender no canto.":
        "The baby eggs got lost in the barn! Push each one to a nest without trapping it in a corner.",
    "Empurre cada BEBÊ-OVO até um NINHO!": "Push every BABY EGG into a NEST!",
    "Você só empurra (não puxa): cuidado com os cantos.": "You can only push (not pull): mind the corners.",
    "Menos passos = mais ★. No GELO o bebê desliza!": "Fewer steps = more ★. On ICE the baby slides!",
    "SETAS/WASD/clique • Z desfaz • R reinicia": "ARROWS/WASD/click • Z undo • R restart",
    "ESTRELAS": "STARS",
    "PRIMEIRO EMPURRÃO": "FIRST PUSH",
    "DOIS SONINHOS": "TWO SLEEPYHEADS",
    "LADO A LADO": "SIDE BY SIDE",
    "VIRANDO A ESQUINA": "AROUND THE CORNER",
    "O PORTÃO": "THE GATE",
    "TRÊS IRMÃOS": "THREE SIBLINGS",
    "CORREDOR DO FENO": "HAY HALLWAY",
    "A COLUNA": "THE PILLAR",
    "A PORTINHA": "THE LITTLE DOOR",
    "VOLTA LONGA": "THE LONG WAY",
    "ESCONDE-ESCONDE": "HIDE-AND-SEEK",
    "CANTINHO": "COZY CORNER",
    "QUATRO CANTOS": "FOUR CORNERS",
    "O NINHO GRANDE": "THE BIG NEST",
    "PALHEIRO": "HAYSTACK",
    "LABIRINTO DE CAIXOTES": "CRATE MAZE",
    "ESCORREGA!": "SLIPPERY!",
    "LAGO CONGELADO": "FROZEN POND",
    "PISTA DE GELO": "ICE RINK",
    "O GRANDE INVERNO": "THE BIG WINTER",
    "TODOS NO NINHO!": "ALL IN THE NEST!",
    "NÍVEL {n} COMPLETO!": "LEVEL {n} CLEAR!",
    "PASSOS: {n}  •  PAR: {par}": "STEPS: {n}  •  PAR: {par}",
    "PRÓXIMO NÍVEL": "NEXT LEVEL",
    "ESCOLHER NÍVEL": "PICK LEVEL",
    "Z  DESFAZER": "Z  UNDO",
    "R  REINICIAR": "R  RESTART",
    "Parece que travou! Aperte R ou Z": "Looks stuck! Press R or Z",
    "NÍVEL {n}/{total}": "LEVEL {n}/{total}",
    "PASSOS: {n}": "STEPS: {n}",
    "PAR: {n}": "PAR: {n}",
    "NÍVEL {n} DE {total}": "LEVEL {n} OF {total}",
    "★ TOTAL: {n} DE {total} ★": "★ TOTAL: {n} OF {total} ★",

    # ---------------- Corrida do Ovo ----------------
    "CORRIDA DO OVO": "EGG RUN",
    "CORRIDA": "RUN",
    "O ovo sai rolando pela rua com o TOTÓ atrás! Pule, abaixe e pegue os limões.":
        "The egg rolls down the street with SPOT on its tail! Jump, duck and grab lemons.",
    "Seu ovo rola pela rua e o TOTÓ vem atrás!": "Your egg rolls down the street with SPOT behind!",
    "Pule hidrantes, cones, caixas e buracos.": "Jump hydrants, cones, boxes and holes.",
    "Abaixe dos passarinhos. Pegue LIMÕES (+10)!": "Duck the birdies. Grab LEMONS (+10)!",
    "Bolhas: CASCA (escudo), ÍMÃ e TURBO.": "Bubbles: SHELL (shield), MAGNET and TURBO.",
    "ESPAÇO/W/↑ ou CLIQUE pula • S/↓ abaixa": "SPACE/W/↑ or CLICK jumps • S/↓ ducks",
    "UFA! CASCA!": "PHEW! SHELL!",
    "CAIU NO BURACO!": "FELL IN A HOLE!",
    "POW!": "POW!",
    "CASCA!": "SHELL!",
    "TROMBOU!": "CRASHED!",
    "UFA! +5": "PHEW! +5",
    "CASCA EXTRA!": "EXTRA SHELL!",
    "TURBO!": "TURBO!",
    "DISTÂNCIA: {n} m": "DISTANCE: {n} m",
    "LIMÕES: {n}": "LEMONS: {n}",

    # ---------------- Ovo-Man ----------------
    "OVO-MAN": "EGG-MAN",
    "Coma todas as sementes da horta fugindo dos utensílios de cozinha. A PIMENTA vira o jogo!":
        "Eat every seed in the garden while fleeing kitchen tools. The PEPPER turns the tables!",
    "Coma todas as SEMENTES da horta!": "Eat all the SEEDS in the garden!",
    "Fuja da frigideira, da batedeira, do ralador e da espátula.": "Run from the pan, the mixer, the grater and the spatula.",
    "Pegue a PIMENTA: eles fogem e você pode comê-los!": "Grab the PEPPER: they flee and you can eat them!",
    "Aperte antes da esquina que o ovo vira sozinho.": "Press before a corner and the egg turns by itself.",
    "SETAS ou WASD para mover": "ARROWS or WASD to move",
    "FRIGIDEIRA": "PAN",
    "BATEDEIRA": "MIXER",
    "RALADOR": "GRATER",
    "ESPÁTULA": "SPATULA",
    "+1 VIDA!": "+1 LIFE!",
    "HORTA LIMPA!": "GARDEN CLEARED!",
    "OVO MEXIDO!": "SCRAMBLED!",
    "PRONTO!": "READY!",
    "PIMENTA!": "PEPPER!",

    # ---------------- Ovo no Ritmo ----------------
    "OVO NO RITMO": "EGG GROOVE",
    "RITMO": "GROOVE",
    "Ovinhos caem no ritmo da música: aperte a seta certa na hora certa e dance na pista!":
        "Little eggs fall to the beat: hit the right arrow at the right time and dance!",
    "Aperte a seta quando o ovinho chegar no": "Press the arrow when the little egg reaches",
    "receptor lá embaixo, no ritmo da música!": "the receiver down below, right on the beat!",
    "Acertos seguidos multiplicam os pontos.": "Hit streaks multiply your points.",
    "Errou muito? A energia acaba e a música para.": "Missed a lot? Energy runs out and the music stops.",
    "SETAS, WASD ou D F J K": "ARROWS, WASD or D F J K",
    "PERFEITO!": "PERFECT!",
    "ÓTIMO!": "GREAT!",
    "BOM": "GOOD",
    "ERROU": "MISS",
    "SEGUROU!": "HELD!",
    "SOLTOU!": "LET GO!",
    "COMBO PERDIDO": "COMBO LOST",
    "   NOTA: {n}": "   GRADE: {n}",
    "PRECISÃO: {p}%   COMBO: {c}": "ACCURACY: {p}%   COMBO: {c}",
    "ACERTOS: {n}/{total}": "HITS: {n}/{total}",
    "SHOW COMPLETO!": "SHOW COMPLETE!",
    "A MÚSICA PAROU!": "THE MUSIC STOPPED!",
    "{n} COMBO": "{n} COMBO",

    # ---------------- Ovo-Bomba ----------------
    "OVO-BOMBA": "EGG-BOMB",
    "Solte ovos de páscoa com pavio no labirinto, estoure as caixas e cubra o rival de chocolate!":
        "Drop fuse Easter eggs in the maze, blast the crates and coat your rival in chocolate!",
    "Solte OVOS DE PÁSCOA com pavio e fuja da explosão!": "Drop fuse EASTER EGGS and run from the blast!",
    "Estoure as caixas de ovos para achar itens.": "Blast the egg crates to find items.",
    "Quem virar OVO DE CHOCOLATE perde o round.": "Whoever turns into a CHOCOLATE EGG loses the round.",
    "J1: WASD + ESPAÇO/F    J2: SETAS + ENTER/CTRL": "P1: WASD + SPACE/F    P2: ARROWS + ENTER/CTRL",
    "MELHOR DE 3": "BEST OF 3",
    "MELHOR DE 5": "BEST OF 5",
    "CAOS (MUITOS ITENS)": "CHAOS (LOTS OF ITEMS)",
    "WASD + ESPAÇO": "WASD + SPACE",
    "SETAS + ENTER": "ARROWS + ENTER",
    "+BOMBA": "+BOMB",
    "+FOGO": "+FIRE",
    "TÊNIS!": "SNEAKERS!",
    "CHUTE!": "KICK!",
    "OVO DE CHOCOLATE!": "CHOCOLATE EGG!",
    "ROUNDS: {a} × {b}": "ROUNDS: {a} × {b}",
    "ROUND {n}!": "ROUND {n}!",
    "ROUND {n}": "ROUND {n}",
    "QUEM FIZER {n} VENCE": "FIRST TO {n} WINS",
    "EMPATE! DE NOVO!": "TIE! AGAIN!",
    "{nome} VENCEU O ROUND!": "{nome} WINS THE ROUND!",
    "MORTE SÚBITA!": "SUDDEN DEATH!",
    "MORTE": "SUDDEN",
    "SÚBITA!": "DEATH!",

    # ---------------- Ovotris ----------------
    "OVOTRIS": "EGGTRIS",
    "OVOTRIS!": "EGGTRIS!",
    "Peças de ovinhos caem no galinheiro! Complete linhas e os ovos chocam em pintinhos.":
        "Egg pieces fall in the coop! Complete lines and the eggs hatch into chicks.",
    "Encaixe as peças de ovinhos e complete LINHAS!": "Fit the egg pieces and complete LINES!",
    "Linha cheia: os ovos chocam e os pintinhos voam.": "Full line: the eggs hatch and the chicks fly off.",
    "4 linhas de uma vez = OVOTRIS! Guarde peças com C.": "4 lines at once = EGGTRIS! Hold pieces with C.",
    "Não deixe a pilha chegar lá em cima!": "Don't let the stack reach the top!",
    "←→ mover • ↑ girar • ↓ descer • ESPAÇO cair": "←→ move • ↑ rotate • ↓ down • SPACE drop",
    "FÁCIL (NÍVEL 1)": "EASY (LEVEL 1)",
    "MÉDIO (NÍVEL 5)": "MEDIUM (LEVEL 5)",
    "DIFÍCIL (NÍVEL 10)": "HARD (LEVEL 10)",
    "MOVER": "MOVE",
    "GIRAR": "ROTATE",
    "GIRAR AO CONTRÁRIO": "ROTATE BACK",
    "DESCER": "SOFT DROP",
    "ESPAÇO": "SPACE",
    "CAIR DE VEZ": "HARD DROP",
    "GUARDAR": "HOLD",
    "GUARDADA": "HOLD",
    "PRÓXIMAS": "NEXT",
    "LINHAS: {n}": "LINES: {n}",
    "FIM DA PILHA!": "STACKED OUT!",
    "NÍVEL": "LEVEL",
    "LINHAS": "LINES",
    "RECORDE": "RECORD",

    # ---------------- Boliche ----------------
    "BOLICHE": "BOWLING",
    "Seu ovo vira a bola! Mire, dose a força e capriche no efeito para fazer STRIKE.":
        "Your egg is the ball! Aim, set the power and add spin to bowl a STRIKE.",
    "3 TOQUES: MIRA (seta) -> FORÇA (barra) -> EFEITO (curva).": "3 TAPS: AIM (arrow) -> POWER (bar) -> SPIN (curve).",
    "A/D ou SETAS movem o ovo antes de mirar. 10 frames, placar oficial.":
        "A/D or ARROWS move the egg before aiming. 10 frames, official scoring.",
    "STRIKE = 10 + 2 bolas • SPARE = 10 + 1 bola. Revezam a cada frame.":
        "STRIKE = 10 + 2 balls • SPARE = 10 + 1 ball. Players swap each frame.",
    "ESPAÇO / CLIQUE": "SPACE / CLICK",
    "ENTER / CLIQUE": "ENTER / CLICK",
    "COMPUTADOR": "COMPUTER",
    "VITÓRIAS  J1 {a} × {b} J2": "WINS  P1 {a} × {b} P2",
    "STRIKE!": "STRIKE!",
    "SPARE!": "SPARE!",
    "CANALETA!": "GUTTER!",
    "ZERO!": "ZERO!",
    "{n} PINO": "{n} PIN",
    "{n} PINOS": "{n} PINS",
    "STRIKES: {a} × {b}": "STRIKES: {a} × {b}",
    "VEZ DE": "TURN",
    "FRAME {f}  BOLA {b}": "FRAME {f}  BALL {b}",
    "PENSANDO...": "THINKING...",
    "A/D: POSIÇÃO": "A/D: POSITION",
    "ESPAÇO: MIRA": "SPACE: AIM",
    "ESPAÇO: FORÇA": "SPACE: POWER",
    "ESPAÇO: EFEITO": "SPACE: SPIN",
    "PINOS EM PÉ: {n}": "PINS STANDING: {n}",
    "<- CURVA ->": "<- CURVE ->",
    "MIRA {n:+.1f}": "AIM {n:+.1f}",

    # ---------------- Xadegg ----------------
    "XADEGG": "CHEGGS",
    "Xadrez de ovinhos! Rei de coroa, rainha de tiara, torre, bispo e cavalo de crina.":
        "Chess with little eggs! Crowned king, tiara queen, rook, bishop and maned knight.",
    "Xadrez com regras completas: roque, en passant, promoção (vira rainha).":
        "Full chess rules: castling, en passant, promotion (becomes a queen).",
    "Dê XEQUE-MATE no rei rival! Afogamento é empate.": "CHECKMATE the rival king! Stalemate is a draw.",
    "MOUSE: clique na peça e no destino  •  TECLADO: SETAS + ENTER":
        "MOUSE: click piece then target  •  KEYBOARD: ARROWS + ENTER",
    "PEÃO": "PAWN",
    "CAVALO": "KNIGHT",
    "BISPO": "BISHOP",
    "TORRE": "ROOK",
    "RAINHA": "QUEEN",
    "REI": "KING",
    "XEQUE-MATE!": "CHECKMATE!",
    "AFOGADO!": "STALEMATE!",
    "XEQUE!": "CHECK!",
    "LANCES: {n}": "MOVES: {n}",
    "AFOGAMENTO: EMPATE": "STALEMATE: DRAW",
    "50 LANCES SEM CAPTURA": "50 MOVES, NO CAPTURE",
    "MATERIAL INSUFICIENTE": "NOT ENOUGH MATERIAL",
    "REPETIÇÃO TRIPLA": "THREEFOLD REPETITION",
    "PROMOÇÃO: RAINHA!": "PROMOTED: QUEEN!",
    "BRANCAS": "WHITE",
    "PRETAS": "BLACK",
    "LANCE {n}": "MOVE {n}",

    # ---------------- Dardos ----------------
    "DARDOS": "DARTS",
    "301 no alvo do galinheiro! Segure para firmar a mão e solte com a força certa.":
        "301 on the coop dartboard! Hold to steady your hand and release with the right power.",
    "MIRE com WASD/SETAS ou o MOUSE. A mão treme (o círculo)!": "AIM with WASD/ARROWS or the MOUSE. Your hand shakes (the circle)!",
    "SEGURE ESPAÇO/CLIQUE para firmar e carregar; SOLTE para lançar.":
        "HOLD SPACE/CLICK to steady and charge; RELEASE to throw.",
    "Força ideal: faixa verde (fraco cai, forte sobe). Segurar demais cansa.":
        "Ideal power: green zone (weak drops, strong rises). Holding too long tires you.",
    "301: 3 dardos por vez, ZERE EXATO. Passou? ESTOUROU e volta!":
        "301: 3 darts per turn, hit ZERO EXACTLY. Went over? BUST, back you go!",
    "ESPAÇO / MOUSE": "SPACE / MOUSE",
    "ENTER / MOUSE": "ENTER / MOUSE",
    "FORA!": "MISS!",
    "ESTOUROU!": "BUST!",
    "ZEROU!": "CHECKOUT!",
    "RESTAM  {a} × {b}": "LEFT  {a} × {b}",
    "MÉDIA POR TURNO  {a} × {b}": "AVG PER TURN  {a} × {b}",
    "{nome} ZEROU NA RODADA {n}!": "{nome} CHECKED OUT IN ROUND {n}!",
    "TURNO: {n}": "TURN: {n}",
    "RODADA {n}/{total}": "ROUND {n}/{total}",
    "ÚLTIMO: {x}": "LAST: {x}",
    "DARDOS DO TURNO": "DARTS THIS TURN",
    "SAÍDA: {x}": "OUT: {x}",
    "FIRMEZA DA MÃO": "HAND STEADINESS",
    "BRAÇO CANSANDO!": "ARM GETTING TIRED!",
    "BOT MIRANDO...": "BOT AIMING...",
    "SEGURE E SOLTE": "HOLD AND RELEASE",

    # ---------------- 4 em Linha ----------------
    "4 EM LINHA": "4 IN A ROW",
    "Solte seus ovinhos na coluna e faça 4 em linha antes do rival!":
        "Drop your little eggs in a column and get 4 in a row before your rival!",
    "Solte um ovinho por vez: ele cai até o fundo da coluna.": "Drop one egg at a time: it falls to the bottom of the column.",
    "Faça 4 EM LINHA: deitado, em pé ou na diagonal!": "Make 4 IN A ROW: across, up or diagonal!",
    "MOUSE: clique na coluna  •  TECLADO: ← → + ENTER": "MOUSE: click a column  •  KEYBOARD: ← → + ENTER",
    "4 EM LINHA EM {n} JOGADAS": "4 IN A ROW IN {n} MOVES",
    "TABULEIRO CHEIO!": "BOARD FULL!",
    "JOGADAS: {n}": "MOVES: {n}",
}

ES = {
    # ---------------- jogos/base.py (todos os minijogos) ----------------
    "MINI JOGO": "MINIJUEGO",
    "PONTOS": "PUNTOS",
    "JOGAR!": "¡JUGAR!",
    "VOLTAR": "VOLVER",
    "CONTINUAR": "CONTINUAR",
    "REINICIAR": "REINICIAR",
    "JOGAR DE NOVO": "JUGAR OTRA VEZ",
    "DIFICULDADE": "DIFICULTAD",
    "MENU DE JOGOS": "MENÚ DE JUEGOS",
    "VOCÊ VENCEU!": "¡GANASTE!",
    "FIM DE JOGO": "FIN DEL JUEGO",
    "NINGUÉM JOGOU: SEM OVOEDAS": "NADIE JUGÓ: SIN HUEVONEDAS",
    "PARTIDA CURTA: +{n}": "PARTIDA CORTA: +{n}",
    "JOGUE MAIS DE {n} s": "JUEGA MÁS DE {n} s",
    "PARTIDA +{n}": "PARTIDA +{n}",
    "1ª DO DIA +{n}": "1ª DEL DÍA +{n}",
    "RECORDE +{n}": "RÉCORD +{n}",
    "BÔNUS ×{n}": "BONO ×{n}",
    "BRONZE": "BRONCE",
    "PRATA": "PLATA",
    "OURO": "ORO",
    "{nome}: FAÇA {n} OU MENOS": "{nome}: HAZ {n} O MENOS",
    "FALTAM {n} PARA O {nome}!": "¡FALTAN {n} PARA {nome}!",
    "RECORDE: {n}": "RÉCORD: {n}",
    "★ RECORDE: {n} ★": "★ RÉCORD: {n} ★",
    "★ SEM RECORDE AINDA ★": "★ AÚN SIN RÉCORD ★",
    "ESCOLHA A DIFICULDADE": "ELIGE LA DIFICULTAD",
    "VENCER {op}": "GANAR {op}",
    "{n} PARTIDA": "{n} PARTIDA",
    "{n} PARTIDAS": "{n} PARTIDAS",
    "{n} OU MENOS": "{n} O MENOS",
    "PREPARE-SE!": "¡PREPÁRATE!",
    "VAI!": "¡YA!",
    "PAUSADO": "EN PAUSA",
    "NÍVEL {n}": "NIVEL {n}",
    "MEDALHA NOVA!": "¡MEDALLA NUEVA!",
    "MOEDAS": "MONEDAS",
    "★ NOVO RECORDE! ★": "★ ¡NUEVO RÉCORD! ★",

    # ---------------- Comuns a vários jogos ----------------
    "FÁCIL": "FÁCIL",
    "NORMAL": "NORMAL",
    "MÉDIO": "MEDIO",
    "DIFÍCIL": "DIFÍCIL",
    "PONTOS: {n}": "PUNTOS: {n}",
    "NÍVEL: {n}": "NIVEL: {n}",
    "NÍVEL {n}!": "¡NIVEL {n}!",
    "2 JOGADORES": "2 JUGADORES",
    "VS {nome}": "VS {nome}",
    "ESCOLHA O MODO": "ELIGE EL MODO",
    "FORÇA": "FUERZA",
    "EFEITO": "EFECTO",
    "TOTAL": "TOTAL",

    # ---------------- Ovo Sobrevivente ----------------
    "OVO SOBREVIVENTE": "HUEVO SUPERVIVIENTE",
    "SOBREVIVENTE": "SUPERVIVIENTE",
    "Sobreviva 3 minutos contra a cozinha rebelde! O ovo joga limões sozinho; escolha melhorias.":
        "¡Sobrevive 3 minutos a la cocina rebelde! El huevo lanza limones solo; elige mejoras.",
    "Colheres, frigideiras e batedores querem o seu ovo!": "¡Cucharas, sartenes y batidores quieren tu huevo!",
    "O ovo joga LIMÕES sozinho. Você só ANDA e pega os CRISTAIS.":
        "El huevo lanza LIMONES solo. Tú solo CAMINAS y tomas los CRISTALES.",
    "Subiu de nível? Escolha 1 de 3 melhorias.": "¿Subiste de nivel? Elige 1 de 3 mejoras.",
    "Sobreviva 3:00! Aos 2:00 chega o LIQUIDIFICADOR.": "¡Sobrevive 3:00! A los 2:00 llega la LICUADORA.",
    "SETAS/WASD andam • MOUSE segurado • 1 2 3 escolhem": "FLECHAS/WASD caminan • MANTÉN MOUSE • 1 2 3 eligen",
    "LIMÃO AZEDO": "LIMÓN ÁCIDO",
    "+30% DE DANO NOS LIMÕES E NA ÓRBITA": "+30% DE DAÑO EN LIMONES Y ÓRBITA",
    "TIRO RÁPIDO": "TIRO RÁPIDO",
    "JOGA LIMÕES 15% MAIS RÁPIDO": "LANZA LIMONES 15% MÁS RÁPIDO",
    "LIMÃO PERFURANTE": "LIMÓN PERFORANTE",
    "CADA LIMÃO ATRAVESSA +1 INIMIGO": "CADA LIMÓN ATRAVIESA +1 ENEMIGO",
    "MAIS LIMÕES": "MÁS LIMONES",
    "+1 LIMÃO EM CADA ARREMESSO": "+1 LIMÓN EN CADA LANZAMIENTO",
    "LIMÕES EM ÓRBITA": "LIMONES EN ÓRBITA",
    "+1 LIMÃO GIRANDO EM VOLTA DO OVO": "+1 LIMÓN GIRANDO ALREDEDOR DEL HUEVO",
    "AURA DE SAL": "AURA DE SAL",
    "SAL EM VOLTA DO OVO: MACHUCA E DEIXA LENTO": "SAL ALREDEDOR DEL HUEVO: DAÑA Y FRENA",
    "CASCA GROSSA": "CÁSCARA GRUESA",
    "+1 CORAÇÃO NO MÁXIMO (E CURA 1)": "+1 CORAZÓN MÁXIMO (Y CURA 1)",
    "ÍMÃ DE XP": "IMÁN DE XP",
    "PEGA CRISTAIS DE BEM MAIS LONGE": "ATRAE CRISTALES DESDE MUY LEJOS",
    "PÉS LIGEIROS": "PIES LIGEROS",
    "O OVO ANDA 12% MAIS RÁPIDO": "EL HUEVO CAMINA 12% MÁS RÁPIDO",
    "LANCHINHO": "BOCADILLO",
    "CURA 2 CORAÇÕES": "CURA 2 CORAZONES",
    "ONDA!": "¡OLEADA!",
    "CUIDADO: O CHEFE VEM AÍ!": "¡CUIDADO: VIENE EL JEFE!",
    "LIQUIDIFICADOR!": "¡LICUADORA!",
    "LIQUIDIFICADOR": "LICUADORA",
    "CHEFE DERROTADO!": "¡JEFE DERROTADO!",
    "AI!": "¡AY!",
    "+1 CORAÇÃO": "+1 CORAZÓN",
    "ÍMÃ!": "¡IMÁN!",
    "VOCÊ SOBREVIVEU!": "¡SOBREVIVISTE!",
    "O OVO FOI BATIDO!": "¡EL HUEVO FUE BATIDO!",
    "TEMPO: {tempo} • NÍVEL {n}": "TIEMPO: {tempo} • NIVEL {n}",
    "INIMIGOS DERROTADOS: {n}": "ENEMIGOS DERROTADOS: {n}",
    "{n} PTS": "{n} PTS",
    "REC {n}": "REC {n}",
    "NV {n}": "NV {n}",
    "SUBIU DE NÍVEL!": "¡SUBISTE DE NIVEL!",
    "ESCOLHA UMA MELHORIA": "ELIGE UNA MEJORA",
    "CURA!": "¡CURA!",
    "NOVO!": "¡NUEVO!",
    "1 2 3 • ← → + ENTER • MOUSE": "1 2 3 • ← → + ENTER • MOUSE",

    # ---------------- Ninho Arrumado ----------------
    "NINHO ARRUMADO": "NIDO ORDENADO",
    "NINHO": "NIDO",
    "Os ovinhos bebês se perderam no celeiro! Empurre cada um até um ninho, sem prender no canto.":
        "¡Los huevitos bebés se perdieron en el granero! Empuja cada uno a un nido sin atorarlo en una esquina.",
    "Empurre cada BEBÊ-OVO até um NINHO!": "¡Empuja cada HUEVO BEBÉ a un NIDO!",
    "Você só empurra (não puxa): cuidado com os cantos.": "Solo empujas (no jalas): cuidado con las esquinas.",
    "Menos passos = mais ★. No GELO o bebê desliza!": "Menos pasos = más ★. ¡En el HIELO el bebé resbala!",
    "SETAS/WASD/clique • Z desfaz • R reinicia": "FLECHAS/WASD/clic • Z deshace • R reinicia",
    "ESTRELAS": "ESTRELLAS",
    "PRIMEIRO EMPURRÃO": "PRIMER EMPUJÓN",
    "DOIS SONINHOS": "DOS DORMILONES",
    "LADO A LADO": "LADO A LADO",
    "VIRANDO A ESQUINA": "DOBLANDO LA ESQUINA",
    "O PORTÃO": "EL PORTÓN",
    "TRÊS IRMÃOS": "TRES HERMANOS",
    "CORREDOR DO FENO": "PASILLO DE HENO",
    "A COLUNA": "LA COLUMNA",
    "A PORTINHA": "LA PUERTITA",
    "VOLTA LONGA": "VUELTA LARGA",
    "ESCONDE-ESCONDE": "ESCONDIDILLAS",
    "CANTINHO": "RINCONCITO",
    "QUATRO CANTOS": "CUATRO ESQUINAS",
    "O NINHO GRANDE": "EL GRAN NIDO",
    "PALHEIRO": "PAJAR",
    "LABIRINTO DE CAIXOTES": "LABERINTO DE CAJAS",
    "ESCORREGA!": "¡RESBALA!",
    "LAGO CONGELADO": "LAGO CONGELADO",
    "PISTA DE GELO": "PISTA DE HIELO",
    "O GRANDE INVERNO": "EL GRAN INVIERNO",
    "TODOS NO NINHO!": "¡TODOS EN EL NIDO!",
    "NÍVEL {n} COMPLETO!": "¡NIVEL {n} COMPLETO!",
    "PASSOS: {n}  •  PAR: {par}": "PASOS: {n}  •  PAR: {par}",
    "PRÓXIMO NÍVEL": "SIGUIENTE NIVEL",
    "ESCOLHER NÍVEL": "ELEGIR NIVEL",
    "Z  DESFAZER": "Z  DESHACER",
    "R  REINICIAR": "R  REINICIAR",
    "Parece que travou! Aperte R ou Z": "¡Parece atorado! Pulsa R o Z",
    "NÍVEL {n}/{total}": "NIVEL {n}/{total}",
    "PASSOS: {n}": "PASOS: {n}",
    "PAR: {n}": "PAR: {n}",
    "NÍVEL {n} DE {total}": "NIVEL {n} DE {total}",
    "★ TOTAL: {n} DE {total} ★": "★ TOTAL: {n} DE {total} ★",

    # ---------------- Corrida do Ovo ----------------
    "CORRIDA DO OVO": "CARRERA DEL HUEVO",
    "CORRIDA": "CARRERA",
    "O ovo sai rolando pela rua com o TOTÓ atrás! Pule, abaixe e pegue os limões.":
        "¡El huevo rueda por la calle con FIRULAIS detrás! Salta, agáchate y toma limones.",
    "Seu ovo rola pela rua e o TOTÓ vem atrás!": "¡Tu huevo rueda por la calle y FIRULAIS lo sigue!",
    "Pule hidrantes, cones, caixas e buracos.": "Salta hidrantes, conos, cajas y hoyos.",
    "Abaixe dos passarinhos. Pegue LIMÕES (+10)!": "Agáchate ante los pajaritos. ¡Toma LIMONES (+10)!",
    "Bolhas: CASCA (escudo), ÍMÃ e TURBO.": "Burbujas: CÁSCARA (escudo), IMÁN y TURBO.",
    "ESPAÇO/W/↑ ou CLIQUE pula • S/↓ abaixa": "ESPACIO/W/↑ o CLIC salta • S/↓ agacha",
    "UFA! CASCA!": "¡UF! ¡CÁSCARA!",
    "CAIU NO BURACO!": "¡CAYÓ EN UN HOYO!",
    "POW!": "¡PUM!",
    "CASCA!": "¡CÁSCARA!",
    "TROMBOU!": "¡CHOCASTE!",
    "UFA! +5": "¡UF! +5",
    "CASCA EXTRA!": "¡CÁSCARA EXTRA!",
    "TURBO!": "¡TURBO!",
    "DISTÂNCIA: {n} m": "DISTANCIA: {n} m",
    "LIMÕES: {n}": "LIMONES: {n}",

    # ---------------- Ovo-Man ----------------
    "OVO-MAN": "HUEVO-MAN",
    "Coma todas as sementes da horta fugindo dos utensílios de cozinha. A PIMENTA vira o jogo!":
        "Come todas las semillas del huerto huyendo de los utensilios. ¡El CHILE cambia el juego!",
    "Coma todas as SEMENTES da horta!": "¡Come todas las SEMILLAS del huerto!",
    "Fuja da frigideira, da batedeira, do ralador e da espátula.": "Huye del sartén, la batidora, el rallador y la espátula.",
    "Pegue a PIMENTA: eles fogem e você pode comê-los!": "¡Toma el CHILE: huyen y puedes comértelos!",
    "Aperte antes da esquina que o ovo vira sozinho.": "Pulsa antes de la esquina y el huevo gira solo.",
    "SETAS ou WASD para mover": "FLECHAS o WASD para moverte",
    "FRIGIDEIRA": "SARTÉN",
    "BATEDEIRA": "BATIDORA",
    "RALADOR": "RALLADOR",
    "ESPÁTULA": "ESPÁTULA",
    "+1 VIDA!": "¡+1 VIDA!",
    "HORTA LIMPA!": "¡HUERTO LIMPIO!",
    "OVO MEXIDO!": "¡HUEVO REVUELTO!",
    "PRONTO!": "¡LISTO!",
    "PIMENTA!": "¡CHILE!",

    # ---------------- Ovo no Ritmo ----------------
    "OVO NO RITMO": "HUEVO AL RITMO",
    "RITMO": "RITMO",
    "Ovinhos caem no ritmo da música: aperte a seta certa na hora certa e dance na pista!":
        "Huevitos caen al ritmo de la música: ¡pulsa la flecha correcta a tiempo y baila!",
    "Aperte a seta quando o ovinho chegar no": "Pulsa la flecha cuando el huevito llegue al",
    "receptor lá embaixo, no ritmo da música!": "receptor de abajo, ¡al ritmo de la música!",
    "Acertos seguidos multiplicam os pontos.": "Los aciertos seguidos multiplican los puntos.",
    "Errou muito? A energia acaba e a música para.": "¿Fallaste mucho? La energía se acaba y la música para.",
    "SETAS, WASD ou D F J K": "FLECHAS, WASD o D F J K",
    "PERFEITO!": "¡PERFECTO!",
    "ÓTIMO!": "¡GENIAL!",
    "BOM": "BIEN",
    "ERROU": "FALLO",
    "SEGUROU!": "¡AGUANTÓ!",
    "SOLTOU!": "¡SOLTÓ!",
    "COMBO PERDIDO": "COMBO PERDIDO",
    "   NOTA: {n}": "   NOTA: {n}",
    "PRECISÃO: {p}%   COMBO: {c}": "PRECISIÓN: {p}%   COMBO: {c}",
    "ACERTOS: {n}/{total}": "ACIERTOS: {n}/{total}",
    "SHOW COMPLETO!": "¡SHOW COMPLETO!",
    "A MÚSICA PAROU!": "¡LA MÚSICA PARÓ!",
    "{n} COMBO": "{n} COMBO",

    # ---------------- Ovo-Bomba ----------------
    "OVO-BOMBA": "HUEVO-BOMBA",
    "Solte ovos de páscoa com pavio no labirinto, estoure as caixas e cubra o rival de chocolate!":
        "¡Suelta huevos de pascua con mecha, revienta las cajas y cubre al rival de chocolate!",
    "Solte OVOS DE PÁSCOA com pavio e fuja da explosão!": "¡Suelta HUEVOS DE PASCUA con mecha y huye de la explosión!",
    "Estoure as caixas de ovos para achar itens.": "Revienta las cajas de huevos para hallar objetos.",
    "Quem virar OVO DE CHOCOLATE perde o round.": "Quien quede como HUEVO DE CHOCOLATE pierde la ronda.",
    "J1: WASD + ESPAÇO/F    J2: SETAS + ENTER/CTRL": "J1: WASD + ESPACIO/F    J2: FLECHAS + ENTER/CTRL",
    "MELHOR DE 3": "AL MEJOR DE 3",
    "MELHOR DE 5": "AL MEJOR DE 5",
    "CAOS (MUITOS ITENS)": "CAOS (MUCHOS OBJETOS)",
    "WASD + ESPAÇO": "WASD + ESPACIO",
    "SETAS + ENTER": "FLECHAS + ENTER",
    "+BOMBA": "+BOMBA",
    "+FOGO": "+FUEGO",
    "TÊNIS!": "¡TENIS!",
    "CHUTE!": "¡PATADA!",
    "OVO DE CHOCOLATE!": "¡HUEVO DE CHOCOLATE!",
    "ROUNDS: {a} × {b}": "RONDAS: {a} × {b}",
    "ROUND {n}!": "¡RONDA {n}!",
    "ROUND {n}": "RONDA {n}",
    "QUEM FIZER {n} VENCE": "QUIEN HAGA {n} GANA",
    "EMPATE! DE NOVO!": "¡EMPATE! ¡OTRA VEZ!",
    "{nome} VENCEU O ROUND!": "¡{nome} GANÓ LA RONDA!",
    "MORTE SÚBITA!": "¡MUERTE SÚBITA!",
    "MORTE": "MUERTE",
    "SÚBITA!": "¡SÚBITA!",

    # ---------------- Ovotris ----------------
    "OVOTRIS": "HUEVOTRIS",
    "OVOTRIS!": "¡HUEVOTRIS!",
    "Peças de ovinhos caem no galinheiro! Complete linhas e os ovos chocam em pintinhos.":
        "¡Piezas de huevitos caen en el gallinero! Completa líneas y los huevos se vuelven pollitos.",
    "Encaixe as peças de ovinhos e complete LINHAS!": "¡Encaja las piezas de huevitos y completa LÍNEAS!",
    "Linha cheia: os ovos chocam e os pintinhos voam.": "Línea llena: los huevos eclosionan y los pollitos vuelan.",
    "4 linhas de uma vez = OVOTRIS! Guarde peças com C.": "¡4 líneas a la vez = HUEVOTRIS! Guarda piezas con C.",
    "Não deixe a pilha chegar lá em cima!": "¡No dejes que la pila llegue arriba!",
    "←→ mover • ↑ girar • ↓ descer • ESPAÇO cair": "←→ mover • ↑ girar • ↓ bajar • ESPACIO caer",
    "FÁCIL (NÍVEL 1)": "FÁCIL (NIVEL 1)",
    "MÉDIO (NÍVEL 5)": "MEDIO (NIVEL 5)",
    "DIFÍCIL (NÍVEL 10)": "DIFÍCIL (NIVEL 10)",
    "MOVER": "MOVER",
    "GIRAR": "GIRAR",
    "GIRAR AO CONTRÁRIO": "GIRAR AL REVÉS",
    "DESCER": "BAJAR",
    "ESPAÇO": "ESPACIO",
    "CAIR DE VEZ": "CAER YA",
    "GUARDAR": "GUARDAR",
    "GUARDADA": "GUARDADA",
    "PRÓXIMAS": "SIGUIENTES",
    "LINHAS: {n}": "LÍNEAS: {n}",
    "FIM DA PILHA!": "¡SE LLENÓ LA PILA!",
    "NÍVEL": "NIVEL",
    "LINHAS": "LÍNEAS",
    "RECORDE": "RÉCORD",

    # ---------------- Boliche ----------------
    "BOLICHE": "BOLICHE",
    "Seu ovo vira a bola! Mire, dose a força e capriche no efeito para fazer STRIKE.":
        "¡Tu huevo es la bola! Apunta, mide la fuerza y dale efecto para hacer STRIKE.",
    "3 TOQUES: MIRA (seta) -> FORÇA (barra) -> EFEITO (curva).": "3 TOQUES: MIRA (flecha) -> FUERZA (barra) -> EFECTO (curva).",
    "A/D ou SETAS movem o ovo antes de mirar. 10 frames, placar oficial.":
        "A/D o FLECHAS mueven el huevo antes de apuntar. 10 frames, marcador oficial.",
    "STRIKE = 10 + 2 bolas • SPARE = 10 + 1 bola. Revezam a cada frame.":
        "STRIKE = 10 + 2 bolas • SPARE = 10 + 1 bola. Se turnan cada frame.",
    "ESPAÇO / CLIQUE": "ESPACIO / CLIC",
    "ENTER / CLIQUE": "ENTER / CLIC",
    "COMPUTADOR": "COMPUTADORA",
    "VITÓRIAS  J1 {a} × {b} J2": "VICTORIAS  J1 {a} × {b} J2",
    "STRIKE!": "¡STRIKE!",
    "SPARE!": "¡SPARE!",
    "CANALETA!": "¡CANAL!",
    "ZERO!": "¡CERO!",
    "{n} PINO": "{n} PINO",
    "{n} PINOS": "{n} PINOS",
    "STRIKES: {a} × {b}": "STRIKES: {a} × {b}",
    "VEZ DE": "TURNO DE",
    "FRAME {f}  BOLA {b}": "FRAME {f}  BOLA {b}",
    "PENSANDO...": "PENSANDO...",
    "A/D: POSIÇÃO": "A/D: POSICIÓN",
    "ESPAÇO: MIRA": "ESPACIO: MIRA",
    "ESPAÇO: FORÇA": "ESPACIO: FUERZA",
    "ESPAÇO: EFEITO": "ESPACIO: EFECTO",
    "PINOS EM PÉ: {n}": "PINOS EN PIE: {n}",
    "<- CURVA ->": "<- CURVA ->",
    "MIRA {n:+.1f}": "MIRA {n:+.1f}",

    # ---------------- Xadegg ----------------
    "XADEGG": "AJEDREGG",
    "Xadrez de ovinhos! Rei de coroa, rainha de tiara, torre, bispo e cavalo de crina.":
        "¡Ajedrez de huevitos! Rey con corona, reina con tiara, torre, alfil y caballo con crin.",
    "Xadrez com regras completas: roque, en passant, promoção (vira rainha).":
        "Ajedrez con reglas completas: enroque, al paso, promoción (se vuelve reina).",
    "Dê XEQUE-MATE no rei rival! Afogamento é empate.": "¡Dale JAQUE MATE al rey rival! Ahogado es empate.",
    "MOUSE: clique na peça e no destino  •  TECLADO: SETAS + ENTER":
        "MOUSE: clic en pieza y destino  •  TECLADO: FLECHAS + ENTER",
    "PEÃO": "PEÓN",
    "CAVALO": "CABALLO",
    "BISPO": "ALFIL",
    "TORRE": "TORRE",
    "RAINHA": "REINA",
    "REI": "REY",
    "XEQUE-MATE!": "¡JAQUE MATE!",
    "AFOGADO!": "¡AHOGADO!",
    "XEQUE!": "¡JAQUE!",
    "LANCES: {n}": "JUGADAS: {n}",
    "AFOGAMENTO: EMPATE": "AHOGADO: EMPATE",
    "50 LANCES SEM CAPTURA": "50 JUGADAS SIN CAPTURA",
    "MATERIAL INSUFICIENTE": "MATERIAL INSUFICIENTE",
    "REPETIÇÃO TRIPLA": "TRIPLE REPETICIÓN",
    "PROMOÇÃO: RAINHA!": "¡CORONACIÓN: REINA!",
    "BRANCAS": "BLANCAS",
    "PRETAS": "NEGRAS",
    "LANCE {n}": "JUGADA {n}",

    # ---------------- Dardos ----------------
    "DARDOS": "DARDOS",
    "301 no alvo do galinheiro! Segure para firmar a mão e solte com a força certa.":
        "¡301 en la diana del gallinero! Mantén para afirmar la mano y suelta con la fuerza justa.",
    "MIRE com WASD/SETAS ou o MOUSE. A mão treme (o círculo)!": "APUNTA con WASD/FLECHAS o el MOUSE. ¡La mano tiembla (el círculo)!",
    "SEGURE ESPAÇO/CLIQUE para firmar e carregar; SOLTE para lançar.":
        "MANTÉN ESPACIO/CLIC para afirmar y cargar; SUELTA para lanzar.",
    "Força ideal: faixa verde (fraco cai, forte sobe). Segurar demais cansa.":
        "Fuerza ideal: franja verde (débil cae, fuerte sube). Aguantar mucho cansa.",
    "301: 3 dardos por vez, ZERE EXATO. Passou? ESTOUROU e volta!":
        "301: 3 dardos por turno, llega a CERO EXACTO. ¿Te pasaste? ¡TE PASASTE y vuelves!",
    "ESPAÇO / MOUSE": "ESPACIO / MOUSE",
    "ENTER / MOUSE": "ENTER / MOUSE",
    "FORA!": "¡FUERA!",
    "ESTOUROU!": "¡TE PASASTE!",
    "ZEROU!": "¡A CERO!",
    "RESTAM  {a} × {b}": "QUEDAN  {a} × {b}",
    "MÉDIA POR TURNO  {a} × {b}": "MEDIA POR TURNO  {a} × {b}",
    "{nome} ZEROU NA RODADA {n}!": "¡{nome} LLEGÓ A CERO EN LA RONDA {n}!",
    "TURNO: {n}": "TURNO: {n}",
    "RODADA {n}/{total}": "RONDA {n}/{total}",
    "ÚLTIMO: {x}": "ÚLTIMO: {x}",
    "DARDOS DO TURNO": "DARDOS DEL TURNO",
    "SAÍDA: {x}": "SALIDA: {x}",
    "FIRMEZA DA MÃO": "FIRMEZA DE LA MANO",
    "BRAÇO CANSANDO!": "¡BRAZO CANSADO!",
    "BOT MIRANDO...": "BOT APUNTANDO...",
    "SEGURE E SOLTE": "MANTÉN Y SUELTA",

    # ---------------- 4 em Linha ----------------
    "4 EM LINHA": "4 EN LÍNEA",
    "Solte seus ovinhos na coluna e faça 4 em linha antes do rival!":
        "¡Suelta tus huevitos en la columna y haz 4 en línea antes que el rival!",
    "Solte um ovinho por vez: ele cai até o fundo da coluna.": "Suelta un huevito a la vez: cae hasta el fondo de la columna.",
    "Faça 4 EM LINHA: deitado, em pé ou na diagonal!": "¡Haz 4 EN LÍNEA: horizontal, vertical o diagonal!",
    "MOUSE: clique na coluna  •  TECLADO: ← → + ENTER": "MOUSE: clic en la columna  •  TECLADO: ← → + ENTER",
    "4 EM LINHA EM {n} JOGADAS": "4 EN LÍNEA EN {n} JUGADAS",
    "TABULEIRO CHEIO!": "¡TABLERO LLENO!",
    "JOGADAS: {n}": "JUGADAS: {n}",
}
