# Traducoes (ver o guia em core/idioma.py). Chave = texto ORIGINAL em portugues.
# jogos: corrida_rua, pinball_ovo, lanchonete, ovo_2048, pescaria, atravessa,
# hoquei_ovo, toupeiras, coral_ovos, memoria, voador, pontinhos, base_hibrido

EN = {
    # --- Comum a vários ---
    "PONTOS": "POINTS",
    "PONTOS: {n}": "POINTS: {n}",
    "RECORDE": "RECORD",
    "RECORDE: {n}": "RECORD: {n}",
    "JOGADAS": "MOVES",
    "JOGADAS: {n}": "MOVES: {n}",
    "FÁCIL": "EASY",
    "MÉDIO": "MEDIUM",
    "NORMAL": "NORMAL",
    "DIFÍCIL": "HARD",
    "2 JOGADORES": "2 PLAYERS",
    "VS": "VS",
    "VITÓRIAS  J1 {a} × {b} J2": "WINS  P1 {a} × {b} P2",
    "LIMÃO": "LEMON",
    "LIMÕES": "LEMONS",
    "TURBO": "TURBO",
    "OVO": "EGG",

    # --- base_hibrido ---
    "BOT FÁCIL": "EASY BOT",
    "BOT MÉDIO": "MEDIUM BOT",
    "BOT DIFÍCIL": "HARD BOT",
    "VS BOT FÁCIL": "VS EASY BOT",
    "VS BOT MÉDIO": "VS MEDIUM BOT",
    "VS BOT DIFÍCIL": "VS HARD BOT",
    "SETAS + ENTER": "ARROWS + ENTER",

    # --- Corrida na Rua ---
    "CORRIDA NA RUA": "STREET RACE",
    "CORRIDA": "RACE",
    "Kart na Rua dos Ovos! Pegue caixas, jogue bananas e limões e cruze a linha primeiro.":
        "Karts on Egg Street! Grab boxes, toss bananas and lemons, and cross the line first.",
    "Complete as voltas na RUA DOS OVOS antes do amigo! Grama e calçada deixam lento.":
        "Finish the laps on EGG STREET before your pal! Grass and sidewalk slow you down.",
    "Caixa ? = BANANA (fica atrás), LIMÃO-FOGUETE (persegue o outro) ou TURBO.":
        "? box = BANANA (drops behind), LEMON ROCKET (chases the other) or TURBO.",
    "J1: WASD dirige • ESPAÇO turbo • F item": "P1: WASD drive • SPACE turbo • F item",
    "J2: SETAS dirige • ENTER turbo • SHIFT DIREITO item": "P2: ARROWS drive • ENTER turbo • RIGHT SHIFT item",
    "3 VOLTAS": "3 LAPS",
    "5 VOLTAS": "5 LAPS",
    "WASD + ESPAÇO + F": "WASD + SPACE + F",
    "SETAS + ENTER + SHIFT": "ARROWS + ENTER + SHIFT",
    "RUA DOS OVOS": "EGG STREET",
    "TURBO!": "TURBO!",
    "{nome}: ÚLTIMA VOLTA!": "{nome}: FINAL LAP!",
    "VOLTA {n}": "LAP {n}",
    "VOLTA {n}/{total}": "LAP {n}/{total}",
    "BANDEIRADA!": "CHECKERED FLAG!",
    "ESCORREGOU!": "SLIPPED!",
    "LIMONADA!": "LEMONADE!",
    "VOLTAS: {n}   TEMPO: {tempo}": "LAPS: {n}   TIME: {tempo}",
    "VOLTA MAIS RÁPIDA: J{j} {s} s": "FASTEST LAP: P{j} {s} s",
    "VOLTE!": "TURN BACK!",
    "CONTRAMÃO!": "WRONG WAY!",
    "VAI!": "GO!",
    "BANANA": "BANANA",
    "ESCOLHA O NÚMERO DE VOLTAS": "CHOOSE THE NUMBER OF LAPS",

    # --- Pinball Ovo ---
    "PINBALL OVO": "EGG PINBALL",
    "PINBALL": "PINBALL",
    "Pinball onde a bola é o SEU OVO! Panelas, limões, rampa e ninho valem muitos pontos.":
        "Pinball where the ball is YOUR EGG! Pans, lemons, ramp and nest score big.",
    "A bola é o SEU OVO! Não deixe ela cair.": "The ball is YOUR EGG! Don't let it drop.",
    "PANELAS quicam • 4 LIMÕES acesos = MULTIPLICADOR": "PANS bounce • 4 LEMONS lit = MULTIPLIER",
    "Acenda L-I-M-A-O • suba a RAMPA • ache o NINHO": "Light L-I-M-A-O • ride the RAMP • find the NEST",
    "← → ou A D flippers • SEGURE ESPAÇO e solte": "← → or A D flippers • HOLD SPACE and release",
    "3 BOLAS": "3 BALLS",
    "5 BOLAS": "5 BALLS",
    "RAMPA": "RAMP",
    "NINHO": "NEST",
    "BOLA": "BALL",
    "MULTIPLICADOR": "MULTIPLIER",
    "BÔNUS": "BONUS",
    "LUZES": "LIGHTS",
    "FLIPPER ESQ.": "LEFT FLIPPER",
    "FLIPPER DIR.": "RIGHT FLIPPER",
    "MOLA (SEGURE)": "PLUNGER (HOLD)",
    "ESPAÇO ↓": "SPACE ↓",
    "PANELA": "PAN",
    "SACODE!": "TILT!",
    "MULTIPLICADOR ×{n}!": "MULTIPLIER ×{n}!",
    "LIMÃO COMPLETO!": "LEMON COMPLETE!",
    "COMBO DE RAMPA!": "RAMP COMBO!",
    "RAMPA!": "RAMP!",
    "NINHO!": "NEST!",
    "SALVA-OVO!": "EGG SAVER!",
    "SALVA-OVO": "EGG SAVER",
    "BÔNUS {pts} ×{n}": "BONUS {pts} ×{n}",
    "CRACK!": "CRACK!",
    "MELHOR BOLA: {n}": "BEST BALL: {n}",
    "BOLA {n}": "BALL {n}",
    "SEGURE ESPAÇO!": "HOLD SPACE!",
    "4 LIMÕES = ×MULT": "4 LEMONS = ×MULT",
    "SUBA A RAMPA!": "RIDE THE RAMP!",
    "ACHE O NINHO": "FIND THE NEST",
    "ACENDA L-I-M-A-O": "LIGHT L-I-M-A-O",
    "O FLIPPER TROCA AS LUZES": "FLIPPERS SWAP THE LIGHTS",

    # --- Lanchonete ---
    "LANCHONETE DO OVO": "EGG DINER",
    "LANCHONETE": "DINER",
    "Seu ovo abriu uma lanchonete! Monte os lanches na ordem certa antes que a paciência acabe.":
        "Your egg opened a diner! Stack the burgers in the right order before patience runs out.",
    "Monte de baixo p/ cima: PÃO, recheios, PÃO!": "Build bottom to top: BUN, fillings, BUN!",
    "Errou? Jogue no lixo (↑) e comece de novo.": "Oops? Toss it (↑) and start over.",
    "Cliente bravo leva uma das 3 estrelas!": "An angry customer takes 1 of 3 stars!",
    "Depois de 60 s: SUCO DE LIMÃO (tecla 7).": "After 60 s: LEMON JUICE (key 7).",
    "←→ escolhe • ESPAÇO põe • 1-7 • ↑ lixo": "←→ pick • SPACE add • 1-7 • ↑ trash",
    "CAFÉ DA MANHÃ": "BREAKFAST",
    "ALMOÇO": "LUNCH",
    "HORA DO RUSH": "RUSH HOUR",
    "PÃO": "BUN",
    "CARNE": "PATTY",
    "QUEIJO": "CHEESE",
    "ALFACE": "LETTUCE",
    "TOMATE": "TOMATO",
    "CEBOLA": "ONION",
    "SUCO": "JUICE",
    "CARDÁPIO": "MENU",
    "X-OVO": "EGG BURGER",
    "X-SALADA": "SALAD BURGER",
    "SUCO LIMÃO": "LEMON JUICE",
    "ESPERE O CLIENTE!": "WAIT FOR A CUSTOMER!",
    "JOGUE FORA! (↑)": "TOSS IT! (↑)",
    "ERROU! JOGUE FORA (↑)": "WRONG! TOSS IT (↑)",
    "NÃO PEDIU SUCO!": "NO JUICE ORDERED!",
    "FALTA O SUCO! (7)": "JUICE MISSING! (7)",
    "+{n} RÁPIDO!": "+{n} SPEEDY!",
    "HMPF!": "HMPH!",
    "FIM DO EXPEDIENTE!": "CLOSING TIME!",
    "CLIENTES: {n}  •  ESTRELAS: {e}/{total}": "CUSTOMERS: {n}  •  STARS: {e}/{total}",
    "LANCHONETE FECHADA!": "DINER CLOSED!",
    "EXPEDIENTE PERFEITO!": "PERFECT SHIFT!",
    "LANCHONETE DO {nome}": "{nome}'S DINER",
    "PEDIDO": "ORDER",

    # --- Evolução 2048 ---
    "EVOLUÇÃO 2048": "EVOLUTION 2048",
    "Junte ovos iguais para evoluir: do ovinho de codorna até o SEU OVO de coroa!":
        "Merge matching eggs to evolve: from tiny quail egg to YOUR EGG with a crown!",
    "Deslize os ovos: dois iguais se juntam e EVOLUEM!": "Slide the eggs: two alike merge and EVOLVE!",
    "Codorna, pintinho, ovo de ouro... até VOCÊ!": "Quail, chick, golden egg... all the way to YOU!",
    "Chegue ao 2048 para virar o REI OVO.": "Reach 2048 to become the EGG KING.",
    "Errou? Você pode DESFAZER 3 vezes.": "Oops? You can UNDO 3 times.",
    "SETAS/WASD ou arraste o mouse • Z desfaz": "ARROWS/WASD or drag the mouse • Z undo",
    "4x4": "4x4",
    "5x5 FÁCIL": "5x5 EASY",
    "3x3 DESAFIO": "3x3 CHALLENGE",
    "OVO DE CODORNA": "QUAIL EGG",
    "OVO BRANCO": "WHITE EGG",
    "OVO CAIPIRA": "FARM EGG",
    "OVO COM LAÇO": "BOW EGG",
    "OVO RACHADO": "CRACKED EGG",
    "PINTINHO": "CHICK",
    "OVO DE PÁSCOA": "EASTER EGG",
    "OVO DE OURO": "GOLDEN EGG",
    "QUASE VOCÊ": "ALMOST YOU",
    "SEU OVO": "YOUR EGG",
    "REI OVO": "EGG KING",
    "OVO LENDÁRIO": "LEGENDARY EGG",
    "NOVO: {nome}!": "NEW: {nome}!",
    "DESFAZER (Z)": "UNDO (Z)",
    "ENCERRAR": "END GAME",
    "CONTINUAR": "CONTINUE",
    "MAIOR: {nome} ({n})": "BEST: {nome} ({n})",
    "VOCÊ EVOLUIU!": "YOU EVOLVED!",
    "SEM JOGADAS!": "NO MOVES LEFT!",
    "DESFAZER": "UNDO",
    "MAIOR OVO": "BEST EGG",
    "EVOLUÇÃO": "EVOLUTION",
    "DESFAZER RESTANTES: {n}": "UNDOS LEFT: {n}",

    # --- Pescaria ---
    "PESCARIA DO OVO": "EGG FISHING",
    "PESCARIA": "FISHING",
    "No barquinho-casca, fisgue peixes, fuja das águas-vivas e ache o baú do tesouro em 90 s!":
        "In your eggshell boat, hook fish, dodge jellyfish and find the treasure chest in 90 s!",
    "Desça o anzol e fisgue peixes! Repetir: x1.5": "Drop the hook and catch fish! Repeat: x1.5",
    "Água-viva dá choque na linha: o peixe foge!": "Jellyfish zap the line: the fish escapes!",
    "Baiacu incha com anzol rápido. DOURADO: +5 s": "Pufferfish puff at fast hooks. GOLDFISH: +5 s",
    "Tem um BAÚ no fundo... mas ele é pesado!": "There's a CHEST at the bottom... but it's heavy!",
    "←→ barco • ↓ desce • ↑ sobe • mouse": "←→ boat • ↓ down • ↑ up • mouse",
    "SARDINHA": "SARDINE",
    "PALHAÇO": "CLOWNFISH",
    "BAIACU": "PUFFER",
    "POLVO": "OCTOPUS",
    "DOURADO": "GOLDFISH",
    "BOTA": "BOOT",
    "BAÚ": "CHEST",
    "PUFF!": "PUFF!",
    "ECA!": "EWW!",
    "O BAÚ!": "THE CHEST!",
    "SEGURA!": "HOLD ON!",
    "FISGOU!": "HOOKED!",
    "CHOQUE! FUGIU!": "ZAP! IT GOT AWAY!",
    "CHOQUE!": "ZAP!",
    "ECA! +0": "EWW! +0",
    "TESOURO! +{n}": "TREASURE! +{n}",
    "PEIXES: {n}  •  COMBO: {c}": "FISH: {n}  •  COMBO: {c}",
    "★ ACHOU O BAÚ! ★": "★ FOUND THE CHEST! ★",
    "FIM DA PESCARIA!": "FISHING'S OVER!",
    "COMBO {nome} x1.5!": "{nome} COMBO x1.5!",
    "ÚLTIMO: {nome}": "LAST: {nome}",

    # --- Atravessa a Rua ---
    "ATRAVESSA A RUA": "CROSS THE ROAD",
    "ATRAVESSA": "CROSSING",
    "Leve o seu ovo pela rua e pelo rio até os ninhos da família. Cuidado com o ônibus vermelho!":
        "Guide your egg across the road and river to the family nests. Watch out for the red bus!",
    "Atravesse a RUA e o RIO até os 5 ninhos lá em cima!": "Cross the ROAD and RIVER to the 5 nests up top!",
    "Carro frita o ovo! No rio, pule nos troncos.": "Cars fry eggs! In the river, hop on the logs.",
    "Vitórias-régias afundam de vez em quando!": "Lily pads sink every now and then!",
    "Leve o PINTINHO PERDIDO ao ninho: +300!": "Bring the LOST CHICK to a nest: +300!",
    "SETAS ou WASD (ou clique) para pular": "ARROWS or WASD (or click) to hop",
    "BI-BI!": "BEEP BEEP!",
    "PINTINHO!": "CHICK!",
    "PINTINHO SALVO! +300": "CHICK SAVED! +300",
    "NÍVEL {n}!  +1000": "LEVEL {n}!  +1000",
    "OVO FRITO!": "FRIED EGG!",
    "GLUB!": "GLUB!",
    "ACABOU O TEMPO!": "TIME'S UP!",
    "PIU!": "PEEP!",
    "NÍVEL: {n}   NINHOS: {ninhos}": "LEVEL: {n}   NESTS: {ninhos}",
    "PINTINHOS SALVOS: {n}": "CHICKS SAVED: {n}",
    "NÍVEL {n}": "LEVEL {n}",

    # --- Hóquei de Ovos ---
    "HÓQUEI DE OVOS": "EGG HOCKEY",
    "HÓQUEI": "HOCKEY",
    "Air hockey no gelo! Seu ovo é o rebatedor e o disco é um limão. Faça gol no amigo!":
        "Air hockey on ice! Your egg is the paddle and the puck is a lemon. Score on your pal!",
    "Rebata o LIMÃO e faça gol do outro lado! Cada um na sua metade.":
        "Hit the LEMON into the other goal! Each player stays on their half.",
    "TACADA FORTE: aperte na hora da batida e o limão pega fogo!":
        "POWER SHOT: press right as you hit and the lemon catches fire!",
    "30 segundos sem gol? Entra um SEGUNDO LIMÃO!": "30 seconds without a goal? A SECOND LEMON drops in!",
    "J1: WASD + ESPAÇO/F tacada • J2: SETAS + ENTER/. tacada": "P1: WASD + SPACE/F shot • P2: ARROWS + ENTER/. shot",
    "ATÉ 5": "FIRST TO 5",
    "ATÉ 7": "FIRST TO 7",
    "ATÉ 10": "FIRST TO 10",
    "WASD + ESPAÇO": "WASD + SPACE",
    "OVAL": "OVAL",
    "LIMÕES & CIA": "LEMONS & CO",
    "PLACAR  {a} × {b}": "SCORE  {a} × {b}",
    "DOIS LIMÕES!": "TWO LEMONS!",
    "LIMÃO QUENTE!": "HOT LEMON!",
    "MATCH POINT!": "MATCH POINT!",
    "GOL!": "GOAL!",
    "2 LIMÕES!": "2 LEMONS!",
    "LIMÃO EXTRA EM {n}": "EXTRA LEMON IN {n}",
    "ATÉ {n}": "FIRST TO {n}",
    "ESCOLHA O MODO": "CHOOSE THE MODE",

    # --- Toupeiras ---
    "TOUPEIRAS NA HORTA": "GARDEN MOLES",
    "TOUPEIRAS": "MOLES",
    "Toupeiras de óculos roubam a horta! Dê BOINGs nelas, mas não acerte os ovinhos bebês.":
        "Moles in glasses raid the garden! BOING them, but don't bonk the baby eggs.",
    "Bata nas toupeiras com o seu ovo-martelo!": "Bonk the moles with your egg hammer!",
    "CAPACETE: 2 batidas. DOURADA: +50 e +3s.": "HELMET: 2 hits. GOLDEN: +50 and +3s.",
    "NÃO bata nos ovinhos bebês da família!": "DON'T bonk the family's baby eggs!",
    "Acertos seguidos multiplicam os pontos.": "Hits in a row multiply your points.",
    "MOUSE, Q W E/A S D/Z X C ou SETAS+ESPAÇO": "MOUSE, Q W E/A S D/Z X C or ARROWS+SPACE",
    "COMBO PERDIDO": "COMBO LOST",
    "AI! -20": "OUCH! -20",
    "PLÉC!": "CLANK!",
    "VALEU, OVO!": "THANKS, EGG!",
    "COMBO ×{n}!": "COMBO ×{n}!",
    "TEMPO!": "TIME!",
    "PONTOS: {n}  (META {meta})": "POINTS: {n}  (GOAL {meta})",
    "ACERTOS: {n}   MAIOR COMBO: {c}": "HITS: {n}   BEST COMBO: {c}",
    "BEBÊS ASSUSTADOS: {n}": "BABIES SPOOKED: {n}",
    "HORTA SALVA!": "GARDEN SAVED!",
    "TEMPO ESGOTADO!": "TIME'S UP!",
    "BOING!": "BOING!",
    "COMBO {n}": "COMBO {n}",
    "META: {n}": "GOAL: {n}",

    # --- Coral dos Ovos ---
    "CORAL DOS OVOS": "EGG CHOIR",
    "CORAL": "CHOIR",
    "Você é o maestro! Repita a melodia dos quatro ovos cantores sem desafinar.":
        "You're the conductor! Repeat the four singing eggs' tune without going off-key.",
    "Você é o MAESTRO do coral da família!": "You're the CONDUCTOR of the family choir!",
    "Ouça os cantores e repita a sequência.": "Listen to the singers and repeat the sequence.",
    "A cada rodada a melodia ganha uma nota.": "Each round the tune gains one note.",
    "MALUCO: os cantores trocam de lugar!": "CRAZY: the singers swap places!",
    "SETAS/WASD (a posição) ou MOUSE": "ARROWS/WASD (the position) or MOUSE",
    "MALUCO": "CRAZY",
    "SEQUÊNCIA": "SEQUENCE",
    "DE CIMA": "ON TOP",
    "DA ESQUERDA": "ON THE LEFT",
    "DA DIREITA": "ON THE RIGHT",
    "DE BAIXO": "AT THE BOTTOM",
    "DEMOROU!": "TOO SLOW!",
    "DE NOVO!": "AGAIN!",
    "SEQUÊNCIA: {n} NOTAS": "SEQUENCE: {n} NOTES",
    "BIS! BIS! A PLATEIA AMOU!": "ENCORE! THE CROWD LOVED IT!",
    "ERA O OVO {pos}": "IT WAS THE EGG {pos}",
    "CONCERTO COMPLETO!": "CONCERT COMPLETE!",
    "FIM DO SHOW": "SHOW'S OVER",
    "OUÇA O CORAL...": "LISTEN TO THE CHOIR...",
    "SUA VEZ!  {n}/{total}": "YOUR TURN!  {n}/{total}",
    "MUITO BEM!": "WELL DONE!",
    "TROCA-TROCA!": "SWAP TIME!",
    "DESAFINOU!": "OFF-KEY!",
    "BRAVO!": "BRAVO!",
    "SEQUÊNCIA: {n}": "SEQUENCE: {n}",

    # --- Memória ---
    "MEMÓRIA DO OVO": "EGG MEMORY",
    "MEMÓRIA": "MEMORY",
    "A família do seu ovo virou cartas! Ache os pares de primos, tias e... você mesmo!":
        "Your egg's family turned into cards! Match cousins, aunts and... yourself!",
    "Vire duas cartas: se forem iguais, é um par!": "Flip two cards: if they match, it's a pair!",
    "Cada carta é um parente do seu ovo.": "Each card is one of your egg's relatives.",
    "Um dos pares é VOCÊ! Ache todos os pares": "One of the pairs is YOU! Find every pair",
    "com o menor número de jogadas.": "in as few moves as you can.",
    "MOUSE ou SETAS + ESPAÇO para virar": "MOUSE or ARROWS + SPACE to flip",
    "VOCÊ": "YOU",
    "É VOCÊ!": "IT'S YOU!",
    "PAR!": "PAIR!",
    "TEMPO: {n}": "TIME: {n}",
    "PARES: {n}/{total}": "PAIRS: {n}/{total}",

    # --- Ovo Voador ---
    "OVO VOADOR": "FLYING EGG",
    "Seu ovo ganhou asinhas! Voe entre as colunas de doce no pôr do sol.":
        "Your egg grew little wings! Fly between candy columns at sunset.",
    "O seu ovo ganhou ASINHAS!": "Your egg grew LITTLE WINGS!",
    "Bata as asas para passar entre os doces.": "Flap to squeeze between the candies.",
    "Cada doce vale 1 ponto. LIMÃO vale 3!": "Each candy is 1 point. LEMON is worth 3!",
    "Não bata nos doces nem no chão.": "Don't hit the candies or the ground.",
    "ESPAÇO, ↑, W ou CLIQUE para bater as asas": "SPACE, ↑, W or CLICK to flap",
    "LIMÕES: {n}": "LEMONS: {n}",
    "APERTE ESPAÇO!": "PRESS SPACE!",
    "ou clique para voar": "or click to fly",

    # --- Pontinhos ---
    "PONTINHOS": "DOTS & BOXES",
    "Ligue os pontinhos e feche caixinhas. Quem fecha uma caixa joga de novo!":
        "Connect the dots and close boxes. Close a box and you go again!",
    "Na sua vez, ligue dois pontinhos vizinhos.": "On your turn, connect two neighboring dots.",
    "Fechou uma caixa? Ela é sua e você JOGA DE NOVO! Quem tiver mais caixas vence.":
        "Closed a box? It's yours and you GO AGAIN! Most boxes wins.",
    "MOUSE: clique entre dois pontos  •  TECLADO: SETAS + ENTER":
        "MOUSE: click between two dots  •  KEYBOARD: ARROWS + ENTER",
    "CAIXAS  {a} × {b}": "BOXES  {a} × {b}",
}

ES = {
    # --- Comum a vários ---
    "PONTOS": "PUNTOS",
    "PONTOS: {n}": "PUNTOS: {n}",
    "RECORDE": "RÉCORD",
    "RECORDE: {n}": "RÉCORD: {n}",
    "JOGADAS": "JUGADAS",
    "JOGADAS: {n}": "JUGADAS: {n}",
    "FÁCIL": "FÁCIL",
    "MÉDIO": "MEDIO",
    "NORMAL": "NORMAL",
    "DIFÍCIL": "DIFÍCIL",
    "2 JOGADORES": "2 JUGADORES",
    "VS": "VS",
    "VITÓRIAS  J1 {a} × {b} J2": "VICTORIAS  J1 {a} × {b} J2",
    "LIMÃO": "LIMÓN",
    "LIMÕES": "LIMONES",
    "TURBO": "TURBO",
    "OVO": "HUEVO",

    # --- base_hibrido ---
    "BOT FÁCIL": "BOT FÁCIL",
    "BOT MÉDIO": "BOT MEDIO",
    "BOT DIFÍCIL": "BOT DIFÍCIL",
    "VS BOT FÁCIL": "VS BOT FÁCIL",
    "VS BOT MÉDIO": "VS BOT MEDIO",
    "VS BOT DIFÍCIL": "VS BOT DIFÍCIL",
    "SETAS + ENTER": "FLECHAS + ENTER",

    # --- Corrida na Rua ---
    "CORRIDA NA RUA": "CARRERA CALLEJERA",
    "CORRIDA": "CARRERA",
    "Kart na Rua dos Ovos! Pegue caixas, jogue bananas e limões e cruze a linha primeiro.":
        "¡Karts en la Calle de los Huevos! Toma cajas, lanza plátanos y limones y llega primero.",
    "Complete as voltas na RUA DOS OVOS antes do amigo! Grama e calçada deixam lento.":
        "¡Completa las vueltas en la CALLE HUEVO antes que tu amigo! El pasto y la acera frenan.",
    "Caixa ? = BANANA (fica atrás), LIMÃO-FOGUETE (persegue o outro) ou TURBO.":
        "Caja ? = PLÁTANO (queda atrás), LIMÓN-COHETE (persigue al otro) o TURBO.",
    "J1: WASD dirige • ESPAÇO turbo • F item": "J1: WASD maneja • ESPACIO turbo • F objeto",
    "J2: SETAS dirige • ENTER turbo • SHIFT DIREITO item": "J2: FLECHAS maneja • ENTER turbo • SHIFT DER. objeto",
    "3 VOLTAS": "3 VUELTAS",
    "5 VOLTAS": "5 VUELTAS",
    "WASD + ESPAÇO + F": "WASD + ESPACIO + F",
    "SETAS + ENTER + SHIFT": "FLECHAS + ENTER + SHIFT",
    "RUA DOS OVOS": "CALLE HUEVOS",
    "TURBO!": "¡TURBO!",
    "{nome}: ÚLTIMA VOLTA!": "{nome}: ¡ÚLTIMA VUELTA!",
    "VOLTA {n}": "VUELTA {n}",
    "VOLTA {n}/{total}": "VUELTA {n}/{total}",
    "BANDEIRADA!": "¡BANDERA A CUADROS!",
    "ESCORREGOU!": "¡RESBALÓ!",
    "LIMONADA!": "¡LIMONADA!",
    "VOLTAS: {n}   TEMPO: {tempo}": "VUELTAS: {n}   TIEMPO: {tempo}",
    "VOLTA MAIS RÁPIDA: J{j} {s} s": "VUELTA MÁS RÁPIDA: J{j} {s} s",
    "VOLTE!": "¡VUELVE!",
    "CONTRAMÃO!": "¡CONTRAMANO!",
    "VAI!": "¡YA!",
    "BANANA": "PLÁTANO",
    "ESCOLHA O NÚMERO DE VOLTAS": "ELIGE EL NÚMERO DE VUELTAS",

    # --- Pinball Ovo ---
    "PINBALL OVO": "PINBALL HUEVO",
    "PINBALL": "PINBALL",
    "Pinball onde a bola é o SEU OVO! Panelas, limões, rampa e ninho valem muitos pontos.":
        "¡Pinball donde la bola es TU HUEVO! Ollas, limones, rampa y nido dan muchos puntos.",
    "A bola é o SEU OVO! Não deixe ela cair.": "¡La bola es TU HUEVO! No la dejes caer.",
    "PANELAS quicam • 4 LIMÕES acesos = MULTIPLICADOR": "OLLAS rebotan • 4 LIMONES = MULTIPLICADOR",
    "Acenda L-I-M-A-O • suba a RAMPA • ache o NINHO": "Enciende L-I-M-A-O • sube la RAMPA • halla el NIDO",
    "← → ou A D flippers • SEGURE ESPAÇO e solte": "← → o A D flippers • MANTÉN ESPACIO y suelta",
    "3 BOLAS": "3 BOLAS",
    "5 BOLAS": "5 BOLAS",
    "RAMPA": "RAMPA",
    "NINHO": "NIDO",
    "BOLA": "BOLA",
    "MULTIPLICADOR": "MULTIPLICADOR",
    "BÔNUS": "BONO",
    "LUZES": "LUCES",
    "FLIPPER ESQ.": "FLIPPER IZQ.",
    "FLIPPER DIR.": "FLIPPER DER.",
    "MOLA (SEGURE)": "RESORTE (MANTÉN)",
    "ESPAÇO ↓": "ESPACIO ↓",
    "PANELA": "OLLA",
    "SACODE!": "¡SACUDE!",
    "MULTIPLICADOR ×{n}!": "¡MULTIPLICADOR ×{n}!",
    "LIMÃO COMPLETO!": "¡LIMÓN COMPLETO!",
    "COMBO DE RAMPA!": "¡COMBO DE RAMPA!",
    "RAMPA!": "¡RAMPA!",
    "NINHO!": "¡NIDO!",
    "SALVA-OVO!": "¡SALVAHUEVO!",
    "SALVA-OVO": "SALVAHUEVO",
    "BÔNUS {pts} ×{n}": "BONO {pts} ×{n}",
    "CRACK!": "¡CRAC!",
    "MELHOR BOLA: {n}": "MEJOR BOLA: {n}",
    "BOLA {n}": "BOLA {n}",
    "SEGURE ESPAÇO!": "¡MANTÉN ESPACIO!",
    "4 LIMÕES = ×MULT": "4 LIMONES = ×MULT",
    "SUBA A RAMPA!": "¡SUBE LA RAMPA!",
    "ACHE O NINHO": "HALLA EL NIDO",
    "ACENDA L-I-M-A-O": "ENCIENDE L-I-M-A-O",
    "O FLIPPER TROCA AS LUZES": "EL FLIPPER CAMBIA LUCES",

    # --- Lanchonete ---
    "LANCHONETE DO OVO": "CAFETÍN DEL HUEVO",
    "LANCHONETE": "CAFETÍN",
    "Seu ovo abriu uma lanchonete! Monte os lanches na ordem certa antes que a paciência acabe.":
        "¡Tu huevo abrió un cafetín! Arma las hamburguesas en orden antes de que se acabe la paciencia.",
    "Monte de baixo p/ cima: PÃO, recheios, PÃO!": "Arma de abajo arriba: ¡PAN, relleno, PAN!",
    "Errou? Jogue no lixo (↑) e comece de novo.": "¿Fallaste? A la basura (↑) y empieza otra vez.",
    "Cliente bravo leva uma das 3 estrelas!": "¡Un cliente enojado se lleva 1 de 3 estrellas!",
    "Depois de 60 s: SUCO DE LIMÃO (tecla 7).": "Tras 60 s: JUGO DE LIMÓN (tecla 7).",
    "←→ escolhe • ESPAÇO põe • 1-7 • ↑ lixo": "←→ elige • ESPACIO pone • 1-7 • ↑ basura",
    "CAFÉ DA MANHÃ": "DESAYUNO",
    "ALMOÇO": "ALMUERZO",
    "HORA DO RUSH": "HORA PICO",
    "PÃO": "PAN",
    "CARNE": "CARNE",
    "QUEIJO": "QUESO",
    "ALFACE": "LECHUGA",
    "TOMATE": "TOMATE",
    "CEBOLA": "CEBOLLA",
    "SUCO": "JUGO",
    "CARDÁPIO": "MENÚ",
    "X-OVO": "HAMB. HUEVO",
    "X-SALADA": "HAMB. VERDE",
    "SUCO LIMÃO": "JUGO LIMÓN",
    "ESPERE O CLIENTE!": "¡ESPERA AL CLIENTE!",
    "JOGUE FORA! (↑)": "¡A LA BASURA! (↑)",
    "ERROU! JOGUE FORA (↑)": "¡MAL! A LA BASURA (↑)",
    "NÃO PEDIU SUCO!": "¡NO PIDIÓ JUGO!",
    "FALTA O SUCO! (7)": "¡FALTA EL JUGO! (7)",
    "+{n} RÁPIDO!": "+{n} ¡RÁPIDO!",
    "HMPF!": "¡HMPF!",
    "FIM DO EXPEDIENTE!": "¡FIN DEL TURNO!",
    "CLIENTES: {n}  •  ESTRELAS: {e}/{total}": "CLIENTES: {n}  •  ESTRELLAS: {e}/{total}",
    "LANCHONETE FECHADA!": "¡CAFETÍN CERRADO!",
    "EXPEDIENTE PERFEITO!": "¡TURNO PERFECTO!",
    "LANCHONETE DO {nome}": "CAFETÍN DE {nome}",
    "PEDIDO": "PEDIDO",

    # --- Evolução 2048 ---
    "EVOLUÇÃO 2048": "EVOLUCIÓN 2048",
    "Junte ovos iguais para evoluir: do ovinho de codorna até o SEU OVO de coroa!":
        "Junta huevos iguales para evolucionar: ¡del huevito de codorniz a TU HUEVO con corona!",
    "Deslize os ovos: dois iguais se juntam e EVOLUEM!": "Desliza los huevos: ¡dos iguales se unen y EVOLUCIONAN!",
    "Codorna, pintinho, ovo de ouro... até VOCÊ!": "Codorniz, pollito, huevo de oro... ¡hasta TI!",
    "Chegue ao 2048 para virar o REI OVO.": "Llega a 2048 para ser el REY HUEVO.",
    "Errou? Você pode DESFAZER 3 vezes.": "¿Fallaste? Puedes DESHACER 3 veces.",
    "SETAS/WASD ou arraste o mouse • Z desfaz": "FLECHAS/WASD o arrastra el mouse • Z deshace",
    "4x4": "4x4",
    "5x5 FÁCIL": "5x5 FÁCIL",
    "3x3 DESAFIO": "3x3 DESAFÍO",
    "OVO DE CODORNA": "HUEVO DE CODORNIZ",
    "OVO BRANCO": "HUEVO BLANCO",
    "OVO CAIPIRA": "HUEVO DE GRANJA",
    "OVO COM LAÇO": "HUEVO CON MOÑO",
    "OVO RACHADO": "HUEVO RAJADO",
    "PINTINHO": "POLLITO",
    "OVO DE PÁSCOA": "HUEVO DE PASCUA",
    "OVO DE OURO": "HUEVO DE ORO",
    "QUASE VOCÊ": "CASI TÚ",
    "SEU OVO": "TU HUEVO",
    "REI OVO": "REY HUEVO",
    "OVO LENDÁRIO": "HUEVO LEGENDARIO",
    "NOVO: {nome}!": "¡NUEVO: {nome}!",
    "DESFAZER (Z)": "DESHACER (Z)",
    "ENCERRAR": "TERMINAR",
    "CONTINUAR": "CONTINUAR",
    "MAIOR: {nome} ({n})": "MAYOR: {nome} ({n})",
    "VOCÊ EVOLUIU!": "¡EVOLUCIONASTE!",
    "SEM JOGADAS!": "¡SIN JUGADAS!",
    "DESFAZER": "DESHACER",
    "MAIOR OVO": "MAYOR HUEVO",
    "EVOLUÇÃO": "EVOLUCIÓN",
    "DESFAZER RESTANTES: {n}": "DESHACER RESTANTES: {n}",

    # --- Pescaria ---
    "PESCARIA DO OVO": "PESCA DEL HUEVO",
    "PESCARIA": "PESCA",
    "No barquinho-casca, fisgue peixes, fuja das águas-vivas e ache o baú do tesouro em 90 s!":
        "¡En tu barquito-cáscara, pesca peces, esquiva medusas y halla el cofre del tesoro en 90 s!",
    "Desça o anzol e fisgue peixes! Repetir: x1.5": "¡Baja el anzuelo y pesca! Repetir: x1.5",
    "Água-viva dá choque na linha: o peixe foge!": "La medusa electrocuta el sedal: ¡el pez huye!",
    "Baiacu incha com anzol rápido. DOURADO: +5 s": "El globo se infla si vas rápido. DORADO: +5 s",
    "Tem um BAÚ no fundo... mas ele é pesado!": "Hay un COFRE en el fondo... ¡pero pesa mucho!",
    "←→ barco • ↓ desce • ↑ sobe • mouse": "←→ barco • ↓ baja • ↑ sube • mouse",
    "SARDINHA": "SARDINA",
    "PALHAÇO": "PAYASO",
    "BAIACU": "PEZ GLOBO",
    "POLVO": "PULPO",
    "DOURADO": "DORADO",
    "BOTA": "BOTA",
    "BAÚ": "COFRE",
    "PUFF!": "¡PUF!",
    "ECA!": "¡PUAJ!",
    "O BAÚ!": "¡EL COFRE!",
    "SEGURA!": "¡AGUANTA!",
    "FISGOU!": "¡PICÓ!",
    "CHOQUE! FUGIU!": "¡ZAS! ¡SE ESCAPÓ!",
    "CHOQUE!": "¡ZAS!",
    "ECA! +0": "¡PUAJ! +0",
    "TESOURO! +{n}": "¡TESORO! +{n}",
    "PEIXES: {n}  •  COMBO: {c}": "PECES: {n}  •  COMBO: {c}",
    "★ ACHOU O BAÚ! ★": "★ ¡HALLASTE EL COFRE! ★",
    "FIM DA PESCARIA!": "¡FIN DE LA PESCA!",
    "COMBO {nome} x1.5!": "¡COMBO {nome} x1.5!",
    "ÚLTIMO: {nome}": "ÚLTIMO: {nome}",

    # --- Atravessa a Rua ---
    "ATRAVESSA A RUA": "CRUZA LA CALLE",
    "ATRAVESSA": "CRUZA",
    "Leve o seu ovo pela rua e pelo rio até os ninhos da família. Cuidado com o ônibus vermelho!":
        "Lleva tu huevo por la calle y el río hasta los nidos de la familia. ¡Ojo con el autobús rojo!",
    "Atravesse a RUA e o RIO até os 5 ninhos lá em cima!": "¡Cruza la CALLE y el RÍO hasta los 5 nidos de arriba!",
    "Carro frita o ovo! No rio, pule nos troncos.": "¡Los autos fríen huevos! En el río, salta a los troncos.",
    "Vitórias-régias afundam de vez em quando!": "¡Los nenúfares se hunden de vez en cuando!",
    "Leve o PINTINHO PERDIDO ao ninho: +300!": "Lleva al POLLITO PERDIDO al nido: ¡+300!",
    "SETAS ou WASD (ou clique) para pular": "FLECHAS o WASD (o clic) para saltar",
    "BI-BI!": "¡PII-PII!",
    "PINTINHO!": "¡POLLITO!",
    "PINTINHO SALVO! +300": "¡POLLITO A SALVO! +300",
    "NÍVEL {n}!  +1000": "¡NIVEL {n}!  +1000",
    "OVO FRITO!": "¡HUEVO FRITO!",
    "GLUB!": "¡GLUB!",
    "ACABOU O TEMPO!": "¡SE ACABÓ EL TIEMPO!",
    "PIU!": "¡PÍO!",
    "NÍVEL: {n}   NINHOS: {ninhos}": "NIVEL: {n}   NIDOS: {ninhos}",
    "PINTINHOS SALVOS: {n}": "POLLITOS A SALVO: {n}",
    "NÍVEL {n}": "NIVEL {n}",

    # --- Hóquei de Ovos ---
    "HÓQUEI DE OVOS": "HOCKEY DE HUEVOS",
    "HÓQUEI": "HOCKEY",
    "Air hockey no gelo! Seu ovo é o rebatedor e o disco é um limão. Faça gol no amigo!":
        "¡Hockey de mesa en hielo! Tu huevo es el mazo y el disco es un limón. ¡Mételes gol!",
    "Rebata o LIMÃO e faça gol do outro lado! Cada um na sua metade.":
        "¡Golpea el LIMÓN y anota del otro lado! Cada uno en su mitad.",
    "TACADA FORTE: aperte na hora da batida e o limão pega fogo!":
        "GOLPE FUERTE: ¡presiona al golpear y el limón se prende fuego!",
    "30 segundos sem gol? Entra um SEGUNDO LIMÃO!": "¿30 segundos sin gol? ¡Entra un SEGUNDO LIMÓN!",
    "J1: WASD + ESPAÇO/F tacada • J2: SETAS + ENTER/. tacada": "J1: WASD + ESPACIO/F golpe • J2: FLECHAS + ENTER/. golpe",
    "ATÉ 5": "A 5",
    "ATÉ 7": "A 7",
    "ATÉ 10": "A 10",
    "WASD + ESPAÇO": "WASD + ESPACIO",
    "OVAL": "OVAL",
    "LIMÕES & CIA": "LIMONES & CÍA",
    "PLACAR  {a} × {b}": "MARCADOR  {a} × {b}",
    "DOIS LIMÕES!": "¡DOS LIMONES!",
    "LIMÃO QUENTE!": "¡LIMÓN CALIENTE!",
    "MATCH POINT!": "¡PUNTO DE PARTIDO!",
    "GOL!": "¡GOL!",
    "2 LIMÕES!": "¡2 LIMONES!",
    "LIMÃO EXTRA EM {n}": "LIMÓN EXTRA EN {n}",
    "ATÉ {n}": "A {n}",
    "ESCOLHA O MODO": "ELIGE EL MODO",

    # --- Toupeiras ---
    "TOUPEIRAS NA HORTA": "TOPOS EN LA HUERTA",
    "TOUPEIRAS": "TOPOS",
    "Toupeiras de óculos roubam a horta! Dê BOINGs nelas, mas não acerte os ovinhos bebês.":
        "¡Topos con lentes asaltan la huerta! Dales BOINGs, pero no a los huevitos bebés.",
    "Bata nas toupeiras com o seu ovo-martelo!": "¡Golpea a los topos con tu huevo-martillo!",
    "CAPACETE: 2 batidas. DOURADA: +50 e +3s.": "CASCO: 2 golpes. DORADO: +50 y +3s.",
    "NÃO bata nos ovinhos bebês da família!": "¡NO golpees a los huevitos bebés!",
    "Acertos seguidos multiplicam os pontos.": "Aciertos seguidos multiplican los puntos.",
    "MOUSE, Q W E/A S D/Z X C ou SETAS+ESPAÇO": "MOUSE, Q W E/A S D/Z X C o FLECHAS+ESPACIO",
    "COMBO PERDIDO": "COMBO PERDIDO",
    "AI! -20": "¡AY! -20",
    "PLÉC!": "¡CLANC!",
    "VALEU, OVO!": "¡GRACIAS, HUEVO!",
    "COMBO ×{n}!": "¡COMBO ×{n}!",
    "TEMPO!": "¡TIEMPO!",
    "PONTOS: {n}  (META {meta})": "PUNTOS: {n}  (META {meta})",
    "ACERTOS: {n}   MAIOR COMBO: {c}": "ACIERTOS: {n}   MEJOR COMBO: {c}",
    "BEBÊS ASSUSTADOS: {n}": "BEBÉS ASUSTADOS: {n}",
    "HORTA SALVA!": "¡HUERTA A SALVO!",
    "TEMPO ESGOTADO!": "¡SE ACABÓ EL TIEMPO!",
    "BOING!": "¡BOING!",
    "COMBO {n}": "COMBO {n}",
    "META: {n}": "META: {n}",

    # --- Coral dos Ovos ---
    "CORAL DOS OVOS": "CORO DE HUEVOS",
    "CORAL": "CORO",
    "Você é o maestro! Repita a melodia dos quatro ovos cantores sem desafinar.":
        "¡Eres el director! Repite la melodía de los cuatro huevos cantores sin desafinar.",
    "Você é o MAESTRO do coral da família!": "¡Eres el DIRECTOR del coro familiar!",
    "Ouça os cantores e repita a sequência.": "Escucha a los cantores y repite la secuencia.",
    "A cada rodada a melodia ganha uma nota.": "Cada ronda la melodía suma una nota.",
    "MALUCO: os cantores trocam de lugar!": "LOCO: ¡los cantores cambian de lugar!",
    "SETAS/WASD (a posição) ou MOUSE": "FLECHAS/WASD (la posición) o MOUSE",
    "MALUCO": "LOCO",
    "SEQUÊNCIA": "SECUENCIA",
    "DE CIMA": "DE ARRIBA",
    "DA ESQUERDA": "DE LA IZQUIERDA",
    "DA DIREITA": "DE LA DERECHA",
    "DE BAIXO": "DE ABAJO",
    "DEMOROU!": "¡MUY LENTO!",
    "DE NOVO!": "¡OTRA VEZ!",
    "SEQUÊNCIA: {n} NOTAS": "SECUENCIA: {n} NOTAS",
    "BIS! BIS! A PLATEIA AMOU!": "¡OTRA! ¡EL PÚBLICO LO AMÓ!",
    "ERA O OVO {pos}": "ERA EL HUEVO {pos}",
    "CONCERTO COMPLETO!": "¡CONCIERTO COMPLETO!",
    "FIM DO SHOW": "FIN DEL SHOW",
    "OUÇA O CORAL...": "ESCUCHA EL CORO...",
    "SUA VEZ!  {n}/{total}": "¡TU TURNO!  {n}/{total}",
    "MUITO BEM!": "¡MUY BIEN!",
    "TROCA-TROCA!": "¡CAMBIO!",
    "DESAFINOU!": "¡DESAFINASTE!",
    "BRAVO!": "¡BRAVO!",
    "SEQUÊNCIA: {n}": "SECUENCIA: {n}",

    # --- Memória ---
    "MEMÓRIA DO OVO": "MEMORIA DEL HUEVO",
    "MEMÓRIA": "MEMORIA",
    "A família do seu ovo virou cartas! Ache os pares de primos, tias e... você mesmo!":
        "¡La familia de tu huevo se volvió cartas! Halla pares de primos, tías y... ¡tú mismo!",
    "Vire duas cartas: se forem iguais, é um par!": "Voltea dos cartas: ¡si son iguales, es un par!",
    "Cada carta é um parente do seu ovo.": "Cada carta es un pariente de tu huevo.",
    "Um dos pares é VOCÊ! Ache todos os pares": "¡Uno de los pares eres TÚ! Halla todos",
    "com o menor número de jogadas.": "con la menor cantidad de jugadas.",
    "MOUSE ou SETAS + ESPAÇO para virar": "MOUSE o FLECHAS + ESPACIO para voltear",
    "VOCÊ": "TÚ",
    "É VOCÊ!": "¡ERES TÚ!",
    "PAR!": "¡PAR!",
    "TEMPO: {n}": "TIEMPO: {n}",
    "PARES: {n}/{total}": "PARES: {n}/{total}",

    # --- Ovo Voador ---
    "OVO VOADOR": "HUEVO VOLADOR",
    "Seu ovo ganhou asinhas! Voe entre as colunas de doce no pôr do sol.":
        "¡A tu huevo le salieron alitas! Vuela entre columnas de dulce al atardecer.",
    "O seu ovo ganhou ASINHAS!": "¡A tu huevo le salieron ALITAS!",
    "Bata as asas para passar entre os doces.": "Aletea para pasar entre los dulces.",
    "Cada doce vale 1 ponto. LIMÃO vale 3!": "Cada dulce vale 1 punto. ¡El LIMÓN vale 3!",
    "Não bata nos doces nem no chão.": "No choques con los dulces ni con el suelo.",
    "ESPAÇO, ↑, W ou CLIQUE para bater as asas": "ESPACIO, ↑, W o CLIC para aletear",
    "LIMÕES: {n}": "LIMONES: {n}",
    "APERTE ESPAÇO!": "¡PULSA ESPACIO!",
    "ou clique para voar": "o haz clic para volar",

    # --- Pontinhos ---
    "PONTINHOS": "PUNTITOS",
    "Ligue os pontinhos e feche caixinhas. Quem fecha uma caixa joga de novo!":
        "Une los puntitos y cierra cajitas. ¡Quien cierra una caja juega otra vez!",
    "Na sua vez, ligue dois pontinhos vizinhos.": "En tu turno, une dos puntitos vecinos.",
    "Fechou uma caixa? Ela é sua e você JOGA DE NOVO! Quem tiver mais caixas vence.":
        "¿Cerraste una caja? ¡Es tuya y JUEGAS OTRA VEZ! Gana quien tenga más cajas.",
    "MOUSE: clique entre dois pontos  •  TECLADO: SETAS + ENTER":
        "MOUSE: clic entre dos puntos  •  TECLADO: FLECHAS + ENTER",
    "CAIXAS  {a} × {b}": "CAJAS  {a} × {b}",
}
