# Traducoes (ver o guia em core/idioma.py). Chave = texto ORIGINAL em portugues.
# Jogos: futebol_ovo, ovo_cozinheiro, ovo_colher, ovonoide, invasores,
# guerra_tinta, descida_neve, volei, campo_minado, pulo, jogo_velha, cobrinha.

EN = {
    # --- Comuns a vários jogos ---
    "PONTOS": "POINTS",
    "TEMPO": "TIME",
    "PONTOS: {n}": "POINTS: {n}",
    "RECORDE: {n}": "BEST: {n}",
    "FÁCIL": "EASY",
    "NORMAL": "NORMAL",
    "DIFÍCIL": "HARD",
    "MÉDIO": "MEDIUM",
    "2 JOGADORES": "2 PLAYERS",
    "ESCOLHA O MODO": "CHOOSE A MODE",
    "VITÓRIAS  J1 {a} × {b} J2": "WINS  P1 {a} × {b} P2",
    "PLACAR  {a} × {b}": "SCORE  {a} × {b}",
    "{nome} VENCEU!": "{nome} WINS!",
    "CRACK!": "CRACK!",
    "DISTÂNCIA: {n} m": "DISTANCE: {n} m",
    "LIMÕES: {n}": "LEMONS: {n}",

    # --- Futebol de ovos ---
    "FUTEBOL DE OVOS": "EGG SOCCER",
    "FUTEBOL": "SOCCER",
    "Um contra um no estádio lotado! Cabeceie, chute e solte o SUPER-CHUTE DE FOGO.":
        "One-on-one in a packed stadium! Head it, kick it and unleash the SUPER FIRE KICK.",
    "Faça gol no outro lado! Cabeceie e chute a bola.": "Score on the other side! Head and kick the ball.",
    "Cada toque enche o SUPER. Cheio? Solte o SUPER-CHUTE DE FOGO!":
        "Every touch fills SUPER. Full? Unleash the SUPER FIRE KICK!",
    "Pegue os presentes que caem do céu (GIGANTE, GELO, PRAIA).":
        "Grab the gifts falling from the sky (GIANT, ICE, BEACH).",
    "J1: A D W, ESPAÇO chuta, G super • J2: ← → ↑, ENTER chuta, SHIFT super":
        "P1: A D W, SPACE kicks, G super • P2: ← → ↑, ENTER kicks, SHIFT super",
    "2 MINUTOS": "2 MINUTES",
    "ATÉ 5 GOLS": "FIRST TO 5",
    "1 MIN MALUCO": "1 MIN CRAZY",
    "A D W + ESPAÇO + G": "A D W + SPACE + G",
    "← → ↑ + ENTER + SHIFT": "← → ↑ + ENTER + SHIFT",
    "SUPER!": "SUPER!",
    "SUPER": "SUPER",
    "10 SEGUNDOS!": "10 SECONDS!",
    "GOL DE OURO!": "GOLDEN GOAL!",
    "GOL DE OURO": "GOLDEN GOAL",
    "FIM DE JOGO!": "GAME OVER!",
    "DECIDIDO NO GOL DE OURO!": "WON BY GOLDEN GOAL!",
    "OVO GIGANTE!": "GIANT EGG!",
    "CONGELOU!": "FROZEN!",
    "BOLA DE PRAIA!": "BEACH BALL!",
    "TOMA!": "TAKE THAT!",
    "SUPER PRONTO!": "SUPER READY!",
    "SUPER-CHUTE!": "SUPER KICK!",
    "GOOOOL!": "GOOOAL!",
    "ATÉ {n}": "TO {n}",

    # --- Ovo cozinheiro ---
    "OVO COZINHEIRO": "EGG CHEF",
    "COZINHEIRO": "CHEF",
    "Siga o livro de receitas: ingredientes na ordem certa, mexa a panela e sirva!":
        "Follow the recipe book: ingredients in the right order, stir the pot and serve!",
    "Siga o LIVRO DE RECEITAS: pegue os ingredientes NA ORDEM.":
        "Follow the RECIPE BOOK: grab the ingredients IN ORDER.",
    "Clique no pote ou aperte 1 a 8.": "Click a jar or press 1 to 8.",
    "Depois MEXA: gire o mouse em volta da panela ou alterne ← →.":
        "Then STIR: circle the mouse around the pot or alternate ← →.",
    "Barra cheia? CLIQUE ou ESPAÇO para servir!": "Bar full? CLICK or SPACE to serve!",
    "Errou o ingrediente? Fumaça preta e menos tempo!": "Wrong ingredient? Black smoke and less time!",
    "CHEF": "CHEF",
    "LIVRO DE RECEITAS": "RECIPE BOOK",
    "ENTREGA": "DELIVERY",
    "MEXA A PANELA!": "STIR THE POT!",
    "ECA! -{n}s": "YUCK! -{n}s",
    "RAPIDINHO!": "SPEEDY!",
    "PERFEITA!": "PERFECT!",
    "QUEIMOU!": "BURNT!",
    "TEMPO!": "TIME!",
    "PONTOS: {n}  (META {meta})": "POINTS: {n}  (GOAL {meta})",
    "RECEITAS: {a}   PERFEITAS: {b}": "RECIPES: {a}   PERFECT: {b}",
    "DESCOBERTAS: {a}/{b}": "DISCOVERED: {a}/{b}",
    "QUEIMADAS: {n}": "BURNT: {n}",
    "CHEF ESTRELADO!": "STAR CHEF!",
    "FIM DO EXPEDIENTE!": "SHIFT'S OVER!",
    "RECEITA {n}": "RECIPE {n}",
    "NOVA!": "NEW!",
    "PEGUE: {nome}": "GRAB: {nome}",
    "SIRVA O PRATO!": "SERVE THE DISH!",
    "QUEIMOU... PRÓXIMA!": "BURNT... NEXT!",
    "DELÍCIA!": "YUMMY!",
    "MEXA!": "STIR!",
    "PRONTO!": "READY!",
    "ESPERE A FUMAÇA...": "WAIT FOR THE SMOKE...",
    "RECEITA NOVA!": "NEW RECIPE!",
    "CLIQUE OU ESPAÇO PARA SERVIR!": "CLICK OR SPACE TO SERVE!",
    "META: {n}": "GOAL: {n}",
    "SEQUÊNCIA {n}": "STREAK {n}",
    "ABÓBORA": "PUMPKIN",
    "PÃO QUEIJO": "CHEESE BREAD",
    "SUCO": "JUICE",
    "SUPER LIMONADA": "SUPER LEMONADE",
    "BANANA SPLIT": "BANANA SPLIT",
    "MAÇÃ DO AMOR": "CANDY APPLE",
    "PÃO DE QUEIJO PICANTE": "SPICY CHEESE BREAD",
    "VITAMINA DE MORANGO": "STRAWBERRY SMOOTHIE",
    "PIZZA DE LIMÃO": "LEMON PIZZA",
    "SORVETE NUVEM": "CLOUD ICE CREAM",
    "TORTA DE MAÇÃ": "APPLE PIE",
    "SUCO ARCO-ÍRIS": "RAINBOW JUICE",
    "SOPA DE ABÓBORA": "PUMPKIN SOUP",
    "SANDUÍCHE TURBO": "TURBO SANDWICH",
    "BOLO DE ABÓBORA": "PUMPKIN CAKE",
    "MILK-SHAKE POLAR": "POLAR MILKSHAKE",
    "SALADA DE FRUTAS": "FRUIT SALAD",
    "PIZZA DOCE": "SWEET PIZZA",
    "BOLO DE FESTA": "PARTY CAKE",
    "LANCHE DO REI": "KING'S SNACK",
    "PIZZA VULCÃO": "VOLCANO PIZZA",
    "SOBREMESA MALUCA": "WACKY DESSERT",

    # --- Ovo na colher ---
    "OVO NA COLHER": "EGG AND SPOON",
    "COLHER": "SPOON",
    "A corrida da festa junina! Ande o mais longe que puder equilibrando o seu ovo na colher.":
        "The village fair race! Walk as far as you can balancing your egg on a spoon.",
    "Equilibre o ovo na colher e ande o mais longe!": "Balance the egg on the spoon and go far!",
    "Incline a colher para o ovo voltar ao meio.": "Tilt the spoon to bring the egg back to center.",
    "Mais rápido = mais metros, mas sacode mais!": "Faster = more meters, but more wobble!",
    "Cuidado: pedras, poças, vento e bichinhos!": "Watch out: rocks, puddles, wind and critters!",
    "←→/AD inclina • ↑↓/WS anda • mouse": "←→/AD tilt • ↑↓/WS walk • mouse",
    "{m} m! +{b}": "{m} m! +{b}",
    "ESCORREGOU!": "SLIPPED!",
    "HIHI!": "HEHE!",
    "PIU!": "TWEET!",
    "NÃÃÃO!": "NOOOO!",
    "CHECKPOINTS: {a}  •  PONTOS: {b}": "CHECKPOINTS: {a}  •  POINTS: {b}",
    "OOOH!": "OOOH!",
    "VENTO": "WIND",
    "VEL": "SPD",

    # --- Ovonoide ---
    "OVONOIDE": "EGGANOID",
    "A bola é o SEU OVO! Rebata-o na cama elástica e quebre os blocos de doce do fliperama.":
        "The ball is YOUR EGG! Bounce it on the trampoline and smash the arcade candy blocks.",
    "A bola é o seu ovo! Não deixe ele cair.": "The ball is your egg! Don't let it fall.",
    "Quebre todos os blocos (o METAL não quebra).": "Break every block (METAL won't break).",
    "O bloco com o seu ovo sempre solta um PODER!": "The block with your egg always drops a POWER!",
    "Onde o ovo bate na cama muda o ângulo.": "Where the egg hits the bed changes the angle.",
    "← → A/D ou MOUSE move • ESPAÇO/CLIQUE lança": "← → A/D or MOUSE move • SPACE/CLICK launch",
    "CAMA GRANDE!": "BIG BED!",
    "GRUDE!": "STICKY!",
    "IRMÃOS!": "SIBLINGS!",
    "DEVAGAR...": "SLOW...",
    "OVO DE FOGO!": "FIRE EGG!",
    "+1 VIDA!": "+1 LIFE!",
    "CORAÇÃO": "HEART",
    "OVO": "EGG",
    "CARINHA": "SMILEY",
    "BONÉ DO ROBERT": "ROBERT'S CAP",
    "CASINHA": "LITTLE HOUSE",
    "SOL DE ÓCULOS": "COOL SUN",
    "LIMÃO": "LEMON",
    "OVO ESCRITO": "EGG LETTERS",
    "XADREZ": "CHECKERS",
    "PIRÂMIDE": "PYRAMID",
    "SURPRESA": "SURPRISE",
    "FASE: {n}": "LEVEL: {n}",
    "FASE LIMPA! +{n}": "LEVEL CLEAR! +{n}",
    "FASE {n}": "LEVEL {n}",
    "ESPAÇO ou CLIQUE para lançar": "SPACE or CLICK to launch",

    # --- Invasores ---
    "INVASORES DA COZINHA": "KITCHEN INVADERS",
    "INVASORES": "INVADERS",
    "Garfos, batedores e panelas marcham para cozinhar o ovo! Defenda-se atirando PIPOCA.":
        "Forks, whisks and pots march in to cook the egg! Fight back by shooting POPCORN.",
    "Os talheres querem cozinhar o seu ovo!": "The utensils want to cook your egg!",
    "Atire PIPOCA: GARFO 30, BATEDOR 20, PANELA 10.": "Shoot POPCORN: FORK 30, WHISK 20, POT 10.",
    "Os NINHOS de palha seguram as gotas de óleo.": "Straw NESTS block the oil drops.",
    "Acerte a FRIGIDEIRA VOADORA: ela solta presentes!": "Hit the FLYING PAN: it drops gifts!",
    "SETAS/A D movem • ESPAÇO/W/↑ atira • MOUSE": "ARROWS/A D move • SPACE/W/↑ shoot • MOUSE",
    "ONDA: {n}": "WAVE: {n}",
    "FIM DO TIRO TRIPLO": "TRIPLE SHOT OVER",
    "ONDA LIMPA!": "WAVE CLEAR!",
    "A COZINHA FOI INVADIDA!": "THE KITCHEN WAS INVADED!",
    "ESCUDO!": "SHIELD!",
    "O OVO FOI FRITO!": "THE EGG GOT FRIED!",
    "ENGORDUROU!": "GREASED!",
    "TIRO TRIPLO!": "TRIPLE SHOT!",
    "ONDA {n}!": "WAVE {n}!",
    "TRIPLO": "TRIPLE",
    "ONDA {n}": "WAVE {n}",

    # --- Guerra de tinta ---
    "GUERRA DE TINTA": "PAINT WAR",
    "TINTA": "PAINT",
    "Os ovos rolam pintando o chão com a própria cor. Quem pintar mais até o fim do tempo ganha!":
        "The eggs roll around painting the floor their color. Whoever paints the most wins!",
    "Role pelo chão pintando com a cor do seu ovo!": "Roll around painting with your egg's color!",
    "Jogue BALÕES DE TINTA e pegue ROLO, TÊNIS e BOMBA.": "Throw PAINT BALLOONS and grab ROLLER, SNEAKERS, BOMB.",
    "Quando o tempo acabar, quem pintou mais vence!": "When time runs out, whoever painted most wins!",
    "J1: WASD + ESPAÇO/F    J2: SETAS + ENTER/CTRL": "P1: WASD + SPACE/F    P2: ARROWS + ENTER/CTRL",
    "60 SEGUNDOS": "60 SECONDS",
    "MELHOR DE 3": "BEST OF 3",
    "SUPER 120s": "SUPER 120s",
    "WASD + ESPAÇO": "WASD + SPACE",
    "SETAS + ENTER": "ARROWS + ENTER",
    "ROLO!": "ROLLER!",
    "TÊNIS!": "SNEAKERS!",
    "BOMBA DE TINTA!": "PAINT BOMB!",
    "SPLASH!": "SPLASH!",
    "PINTADO: {a}% × {b}%": "PAINTED: {a}% × {b}%",
    "ROUNDS: {a} × {b}": "ROUNDS: {a} × {b}",
    "ROUND {n}!": "ROUND {n}!",
    "ROUND {n}": "ROUND {n}",
    "QUEM FIZER {n} VENCE": "FIRST TO {n} WINS",
    "ÚLTIMOS SEGUNDOS!": "FINAL SECONDS!",
    "QUEM PINTOU MAIS?": "WHO PAINTED MORE?",
    "EMPATE!": "TIE!",
    "SPLAT!": "SPLAT!",

    # --- Descida na neve ---
    "DESCIDA NA NEVE": "SNOW SLIDE",
    "NEVE": "SNOW",
    "O ovo desce a montanha de trenó! Passe nas bandeiras, salte rampas e fuja do boneco gigante.":
        "The egg sleds down the mountain! Pass the flags, jump ramps and flee the giant snowman.",
    "Desça de trenó e desvie das árvores e pedras!": "Sled down and dodge the trees and rocks!",
    "Passe ENTRE as bandeiras: +1.5s. Errar: -3s.": "Go BETWEEN the flags: +1.5s. Miss: -3s.",
    "Nas RAMPAS, aperte ← → no ar: MANOBRA +100!": "On RAMPS, press ← → midair: TRICK +100!",
    "Depois de 2000 m... cuidado com o BONECO!": "After 2000 m... beware the SNOWMAN!",
    "← → virar • ↓ acelerar • ↑ frear • ESPAÇO pula": "← → steer • ↓ speed up • ↑ brake • SPACE jump",
    "VERDE (FÁCIL)": "GREEN (EASY)",
    "AZUL": "BLUE",
    "PRETA (DIFÍCIL)": "BLACK (HARD)",
    "3 TOMBOS!": "3 WIPEOUTS!",
    "ACABOU O TEMPO!": "TIME'S UP!",
    "MANOBRA!": "TRICK!",
    "MANOBRA x{n}!": "TRICK x{n}!",
    "BANDEIRA +{n}s": "FLAG +{n}s",
    "TOMBOU!": "WIPEOUT!",
    "AI!": "OUCH!",
    "O BONECO GIGANTE!": "THE GIANT SNOWMAN!",
    "ABRAÇO GELADO!": "FROSTY HUG!",
    "BANDEIRAS: {a}  MANOBRAS: {b}": "FLAGS: {a}  TRICKS: {b}",
    "PULO": "JUMP",

    # --- Vôlei de praia ---
    "VÔLEI DE PRAIA": "BEACH VOLLEYBALL",
    "VÔLEI": "VOLLEY",
    "Vôlei de praia contra o ROBERT! Rebata a bola com a cabeça do seu ovo.":
        "Beach volleyball against ROBERT! Bounce the ball off your egg's head.",
    "Rebata a bola com a cabeça do seu ovo!": "Bounce the ball off your egg's head!",
    "Se a bola cair na areia do ROBERT, ponto seu.": "If the ball lands on ROBERT's sand, you score.",
    "Onde a bola bate no ovo muda o rumo dela.": "Where the ball hits the egg changes its path.",
    "Quem fizer 7 pontos primeiro vence!": "First to 7 points wins!",
    "← → ou A D para mover, ↑ W ou ESPAÇO pula": "← → or A D to move, ↑ W or SPACE jumps",
    "CORTADA!": "SPIKE!",
    "PLACAR: {a} x {b}": "SCORE: {a} x {b}",
    "PONTO!": "POINT!",
    "VOCÊ": "YOU",
    "PONTO DECISIVO!": "MATCH POINT!",

    # --- Campo minado ---
    "CAMPO MINADO": "MINESWEEPER",
    "MINADO": "MINES",
    "Ovos-bomba escondidos na grama! Use os números para abrir o campo sem explodir.":
        "Egg-bombs hidden in the grass! Use the numbers to clear the field without exploding.",
    "Abra a grama sem achar um OVO-BOMBA!": "Clear the grass without finding an EGG-BOMB!",
    "O número conta os ovos-bomba encostados nele.": "The number counts the egg-bombs touching it.",
    "Marque os ovos-bomba com a sua bandeirinha.": "Mark the egg-bombs with your little flag.",
    "Número com as bandeiras certas? Clique: abre tudo!": "Number with the right flags? Click: opens all!",
    "MOUSE esq./dir. ou SETAS + ESPAÇO + F": "MOUSE left/right or ARROWS + SPACE + F",
    "TEMPO: {n}": "TIME: {n}",
    "CASAS ABERTAS: {a}/{b}": "TILES OPENED: {a}/{b}",
    "NÍVEL: {n}": "LEVEL: {n}",
    "KABUM!": "KABOOM!",
    "ERA UM OVO-BOMBA!": "IT WAS AN EGG-BOMB!",

    # --- Pulo nas nuvens ---
    "PULO NAS NUVENS": "CLOUD HOP",
    "PULO NUVENS": "CLOUD HOP",
    "Seu ovo quica de nuvem em nuvem! Suba pelo céu até chegar no espaço.":
        "Your egg bounces from cloud to cloud! Climb the sky all the way to space.",
    "O seu ovo quica sozinho nas nuvens!": "Your egg bounces on the clouds by itself!",
    "Nuvem cinza de chuva se desfaz: cuidado!": "Gray rain clouds fall apart: careful!",
    "A MOLA dá um SUPER PULO. Pegue os LIMÕES!": "The SPRING gives a SUPER JUMP. Grab the LEMONS!",
    "Não caia lá embaixo!": "Don't fall down there!",
    "← → ou A/D (ou o MOUSE) para ir de lado": "← → or A/D (or the MOUSE) to move sideways",
    "ALTURA: {n} m": "HEIGHT: {n} m",

    # --- Jogo da velha ---
    "JOGO DA VELHA": "TIC-TAC-TOE",
    "VELHA": "TIC-TAC",
    "O clássico! Seu ovinho é o X, o rival é o O. Melhor de 5: quem fizer 3 vitórias leva!":
        "The classic! Your little egg is X, the rival is O. Best of 5: first to 3 wins!",
    "Faça 3 ovinhos em linha: reta ou diagonal!": "Get 3 little eggs in a row: straight or diagonal!",
    "MELHOR DE 5: quem vencer 3 rodadas leva. Quem começa alterna.":
        "BEST OF 5: win 3 rounds to take it. Who starts alternates.",
    "MOUSE: clique na casa  •  TECLADO: SETAS + ENTER": "MOUSE: click a square  •  KEYBOARD: ARROWS + ENTER",
    "MOUSE OU SETAS + ENTER": "MOUSE OR ARROWS + ENTER",
    "PENSANDO": "THINKING",
    "SUA VEZ!": "YOUR TURN!",
    "VS BOT OU 2 JOGADORES NO MESMO PC": "VS BOT OR 2 PLAYERS ON ONE PC",
    "BOT": "BOT",
    "MOUSE OU SETAS": "MOUSE OR ARROWS",
    "PONTO DE {nome}!": "POINT FOR {nome}!",
    "RODADAS JOGADAS: {n}": "ROUNDS PLAYED: {n}",
    "RODADA {n}  •  MELHOR DE 5": "ROUND {n}  •  BEST OF 5",

    # --- Cobrinha ---
    "COBRINHA DO OVO": "EGG SNAKE",
    "COBRINHA": "SNAKE",
    "Seu ovo virou cobra! Coma limões para a cauda crescer com a sua cor.":
        "Your egg turned into a snake! Eat lemons to grow a tail in your color.",
    "Guie o seu ovo e coma os LIMÕES!": "Guide your egg and eat the LEMONS!",
    "Cada limão faz a cauda crescer com a sua cor.": "Each lemon grows your tail in your color.",
    "O LIMÃO DOURADO vale 5, mas some rápido!": "The GOLDEN LEMON is worth 5, but vanishes fast!",
    "Não bata na cerca nem na própria cauda.": "Don't hit the fence or your own tail.",
    "SETAS ou WASD para mover": "ARROWS or WASD to move",
    "TAMANHO: {n}": "LENGTH: {n}",
    "TABULEIRO CHEIO!": "BOARD FULL!",
    "LIMÃO DOURADO: {n}s": "GOLDEN LEMON: {n}s",
}

ES = {
    # --- Comuns a vários jogos ---
    "PONTOS": "PUNTOS",
    "TEMPO": "TIEMPO",
    "PONTOS: {n}": "PUNTOS: {n}",
    "RECORDE: {n}": "RÉCORD: {n}",
    "FÁCIL": "FÁCIL",
    "NORMAL": "NORMAL",
    "DIFÍCIL": "DIFÍCIL",
    "MÉDIO": "MEDIO",
    "2 JOGADORES": "2 JUGADORES",
    "ESCOLHA O MODO": "ELIGE EL MODO",
    "VITÓRIAS  J1 {a} × {b} J2": "VICTORIAS  J1 {a} × {b} J2",
    "PLACAR  {a} × {b}": "MARCADOR  {a} × {b}",
    "{nome} VENCEU!": "¡{nome} GANÓ!",
    "CRACK!": "¡CRACK!",
    "DISTÂNCIA: {n} m": "DISTANCIA: {n} m",
    "LIMÕES: {n}": "LIMONES: {n}",

    # --- Futebol de ovos ---
    "FUTEBOL DE OVOS": "FÚTBOL DE HUEVOS",
    "FUTEBOL": "FÚTBOL",
    "Um contra um no estádio lotado! Cabeceie, chute e solte o SUPER-CHUTE DE FOGO.":
        "¡Uno contra uno en el estadio lleno! Cabecea, patea y suelta la SUPERPATADA DE FUEGO.",
    "Faça gol no outro lado! Cabeceie e chute a bola.": "¡Anota en el otro lado! Cabecea y patea la pelota.",
    "Cada toque enche o SUPER. Cheio? Solte o SUPER-CHUTE DE FOGO!":
        "Cada toque llena el SÚPER. ¿Lleno? ¡Suelta la SUPERPATADA DE FUEGO!",
    "Pegue os presentes que caem do céu (GIGANTE, GELO, PRAIA).":
        "Atrapa los regalos que caen del cielo (GIGANTE, HIELO, PLAYA).",
    "J1: A D W, ESPAÇO chuta, G super • J2: ← → ↑, ENTER chuta, SHIFT super":
        "J1: A D W, ESPACIO patea, G súper • J2: ← → ↑, ENTER patea, SHIFT súper",
    "2 MINUTOS": "2 MINUTOS",
    "ATÉ 5 GOLS": "HASTA 5 GOLES",
    "1 MIN MALUCO": "1 MIN LOCO",
    "A D W + ESPAÇO + G": "A D W + ESPACIO + G",
    "← → ↑ + ENTER + SHIFT": "← → ↑ + ENTER + SHIFT",
    "SUPER!": "¡SÚPER!",
    "SUPER": "SÚPER",
    "10 SEGUNDOS!": "¡10 SEGUNDOS!",
    "GOL DE OURO!": "¡GOL DE ORO!",
    "GOL DE OURO": "GOL DE ORO",
    "FIM DE JOGO!": "¡FIN DEL JUEGO!",
    "DECIDIDO NO GOL DE OURO!": "¡DECIDIDO CON GOL DE ORO!",
    "OVO GIGANTE!": "¡HUEVO GIGANTE!",
    "CONGELOU!": "¡CONGELADO!",
    "BOLA DE PRAIA!": "¡PELOTA DE PLAYA!",
    "TOMA!": "¡TOMA!",
    "SUPER PRONTO!": "¡SÚPER LISTO!",
    "SUPER-CHUTE!": "¡SUPERPATADA!",
    "GOOOOL!": "¡GOOOOL!",
    "ATÉ {n}": "HASTA {n}",

    # --- Ovo cozinheiro ---
    "OVO COZINHEIRO": "HUEVO COCINERO",
    "COZINHEIRO": "COCINERO",
    "Siga o livro de receitas: ingredientes na ordem certa, mexa a panela e sirva!":
        "Sigue el libro de recetas: ingredientes en orden, revuelve la olla y ¡sirve!",
    "Siga o LIVRO DE RECEITAS: pegue os ingredientes NA ORDEM.":
        "Sigue el LIBRO DE RECETAS: toma los ingredientes EN ORDEN.",
    "Clique no pote ou aperte 1 a 8.": "Haz clic en el frasco o pulsa 1 a 8.",
    "Depois MEXA: gire o mouse em volta da panela ou alterne ← →.":
        "Luego REVUELVE: gira el mouse alrededor de la olla o alterna ← →.",
    "Barra cheia? CLIQUE ou ESPAÇO para servir!": "¿Barra llena? ¡CLIC o ESPACIO para servir!",
    "Errou o ingrediente? Fumaça preta e menos tempo!": "¿Ingrediente equivocado? ¡Humo negro y menos tiempo!",
    "CHEF": "CHEF",
    "LIVRO DE RECEITAS": "LIBRO DE RECETAS",
    "ENTREGA": "ENTREGA",
    "MEXA A PANELA!": "¡REVUELVE LA OLLA!",
    "ECA! -{n}s": "¡PUAJ! -{n}s",
    "RAPIDINHO!": "¡RAPIDITO!",
    "PERFEITA!": "¡PERFECTA!",
    "QUEIMOU!": "¡SE QUEMÓ!",
    "TEMPO!": "¡TIEMPO!",
    "PONTOS: {n}  (META {meta})": "PUNTOS: {n}  (META {meta})",
    "RECEITAS: {a}   PERFEITAS: {b}": "RECETAS: {a}   PERFECTAS: {b}",
    "DESCOBERTAS: {a}/{b}": "DESCUBIERTAS: {a}/{b}",
    "QUEIMADAS: {n}": "QUEMADAS: {n}",
    "CHEF ESTRELADO!": "¡CHEF ESTRELLA!",
    "FIM DO EXPEDIENTE!": "¡FIN DEL TURNO!",
    "RECEITA {n}": "RECETA {n}",
    "NOVA!": "¡NUEVA!",
    "PEGUE: {nome}": "TOMA: {nome}",
    "SIRVA O PRATO!": "¡SIRVE EL PLATO!",
    "QUEIMOU... PRÓXIMA!": "SE QUEMÓ... ¡OTRA!",
    "DELÍCIA!": "¡DELICIA!",
    "MEXA!": "¡REVUELVE!",
    "PRONTO!": "¡LISTO!",
    "ESPERE A FUMAÇA...": "ESPERA EL HUMO...",
    "RECEITA NOVA!": "¡RECETA NUEVA!",
    "CLIQUE OU ESPAÇO PARA SERVIR!": "¡CLIC O ESPACIO PARA SERVIR!",
    "META: {n}": "META: {n}",
    "SEQUÊNCIA {n}": "RACHA {n}",
    "ABÓBORA": "CALABAZA",
    "PÃO QUEIJO": "PAN QUESO",
    "SUCO": "JUGO",
    "SUPER LIMONADA": "SÚPER LIMONADA",
    "BANANA SPLIT": "BANANA SPLIT",
    "MAÇÃ DO AMOR": "MANZANA DE AMOR",
    "PÃO DE QUEIJO PICANTE": "PAN DE QUESO PICANTE",
    "VITAMINA DE MORANGO": "BATIDO DE FRESA",
    "PIZZA DE LIMÃO": "PIZZA DE LIMÓN",
    "SORVETE NUVEM": "HELADO NUBE",
    "TORTA DE MAÇÃ": "TARTA DE MANZANA",
    "SUCO ARCO-ÍRIS": "JUGO ARCOÍRIS",
    "SOPA DE ABÓBORA": "SOPA DE CALABAZA",
    "SANDUÍCHE TURBO": "SÁNDWICH TURBO",
    "BOLO DE ABÓBORA": "PASTEL DE CALABAZA",
    "MILK-SHAKE POLAR": "MALTEADA POLAR",
    "SALADA DE FRUTAS": "ENSALADA DE FRUTAS",
    "PIZZA DOCE": "PIZZA DULCE",
    "BOLO DE FESTA": "PASTEL DE FIESTA",
    "LANCHE DO REI": "MERIENDA DEL REY",
    "PIZZA VULCÃO": "PIZZA VOLCÁN",
    "SOBREMESA MALUCA": "POSTRE LOCO",

    # --- Ovo na colher ---
    "OVO NA COLHER": "HUEVO EN CUCHARA",
    "COLHER": "CUCHARA",
    "A corrida da festa junina! Ande o mais longe que puder equilibrando o seu ovo na colher.":
        "¡La carrera de la feria! Avanza lo más lejos que puedas con tu huevo en la cuchara.",
    "Equilibre o ovo na colher e ande o mais longe!": "¡Equilibra el huevo en la cuchara y llega lejos!",
    "Incline a colher para o ovo voltar ao meio.": "Inclina la cuchara para centrar el huevo.",
    "Mais rápido = mais metros, mas sacode mais!": "Más rápido = más metros, ¡pero se sacude más!",
    "Cuidado: pedras, poças, vento e bichinhos!": "¡Cuidado: piedras, charcos, viento y bichitos!",
    "←→/AD inclina • ↑↓/WS anda • mouse": "←→/AD inclina • ↑↓/WS avanza • mouse",
    "{m} m! +{b}": "¡{m} m! +{b}",
    "ESCORREGOU!": "¡RESBALÓ!",
    "HIHI!": "¡JIJI!",
    "PIU!": "¡PÍO!",
    "NÃÃÃO!": "¡NOOOO!",
    "CHECKPOINTS: {a}  •  PONTOS: {b}": "CONTROLES: {a}  •  PUNTOS: {b}",
    "OOOH!": "¡OOOH!",
    "VENTO": "VIENTO",
    "VEL": "VEL",

    # --- Ovonoide ---
    "OVONOIDE": "HUEVONOIDE",
    "A bola é o SEU OVO! Rebata-o na cama elástica e quebre os blocos de doce do fliperama.":
        "¡La pelota es TU HUEVO! Rebótalo en el trampolín y rompe los bloques de dulce.",
    "A bola é o seu ovo! Não deixe ele cair.": "¡La pelota es tu huevo! No dejes que caiga.",
    "Quebre todos os blocos (o METAL não quebra).": "Rompe todos los bloques (el METAL no se rompe).",
    "O bloco com o seu ovo sempre solta um PODER!": "¡El bloque con tu huevo siempre suelta un PODER!",
    "Onde o ovo bate na cama muda o ângulo.": "Donde el huevo toca la cama cambia el ángulo.",
    "← → A/D ou MOUSE move • ESPAÇO/CLIQUE lança": "← → A/D o MOUSE mueve • ESPACIO/CLIC lanza",
    "CAMA GRANDE!": "¡CAMA GRANDE!",
    "GRUDE!": "¡PEGAJOSO!",
    "IRMÃOS!": "¡HERMANOS!",
    "DEVAGAR...": "DESPACIO...",
    "OVO DE FOGO!": "¡HUEVO DE FUEGO!",
    "+1 VIDA!": "¡+1 VIDA!",
    "CORAÇÃO": "CORAZÓN",
    "OVO": "HUEVO",
    "CARINHA": "CARITA",
    "BONÉ DO ROBERT": "GORRA DE ROBERT",
    "CASINHA": "CASITA",
    "SOL DE ÓCULOS": "SOL CON LENTES",
    "LIMÃO": "LIMÓN",
    "OVO ESCRITO": "HUEVO ESCRITO",
    "XADREZ": "AJEDREZ",
    "PIRÂMIDE": "PIRÁMIDE",
    "SURPRESA": "SORPRESA",
    "FASE: {n}": "NIVEL: {n}",
    "FASE LIMPA! +{n}": "¡NIVEL LIMPIO! +{n}",
    "FASE {n}": "NIVEL {n}",
    "ESPAÇO ou CLIQUE para lançar": "ESPACIO o CLIC para lanzar",

    # --- Invasores ---
    "INVASORES DA COZINHA": "INVASORES DE COCINA",
    "INVASORES": "INVASORES",
    "Garfos, batedores e panelas marcham para cozinhar o ovo! Defenda-se atirando PIPOCA.":
        "¡Tenedores, batidores y ollas marchan para cocinar al huevo! Defiéndete con PALOMITAS.",
    "Os talheres querem cozinhar o seu ovo!": "¡Los cubiertos quieren cocinar tu huevo!",
    "Atire PIPOCA: GARFO 30, BATEDOR 20, PANELA 10.": "Lanza PALOMITAS: TENEDOR 30, BATIDOR 20, OLLA 10.",
    "Os NINHOS de palha seguram as gotas de óleo.": "Los NIDOS de paja frenan las gotas de aceite.",
    "Acerte a FRIGIDEIRA VOADORA: ela solta presentes!": "¡Dale a la SARTÉN VOLADORA: suelta regalos!",
    "SETAS/A D movem • ESPAÇO/W/↑ atira • MOUSE": "FLECHAS/A D mueven • ESPACIO/W/↑ dispara • MOUSE",
    "ONDA: {n}": "OLEADA: {n}",
    "FIM DO TIRO TRIPLO": "FIN DEL TIRO TRIPLE",
    "ONDA LIMPA!": "¡OLEADA LIMPIA!",
    "A COZINHA FOI INVADIDA!": "¡INVADIERON LA COCINA!",
    "ESCUDO!": "¡ESCUDO!",
    "O OVO FOI FRITO!": "¡EL HUEVO SE FRIÓ!",
    "ENGORDUROU!": "¡ENGRASADO!",
    "TIRO TRIPLO!": "¡TIRO TRIPLE!",
    "ONDA {n}!": "¡OLEADA {n}!",
    "TRIPLO": "TRIPLE",
    "ONDA {n}": "OLEADA {n}",

    # --- Guerra de tinta ---
    "GUERRA DE TINTA": "GUERRA DE PINTURA",
    "TINTA": "PINTURA",
    "Os ovos rolam pintando o chão com a própria cor. Quem pintar mais até o fim do tempo ganha!":
        "Los huevos ruedan pintando el suelo con su color. ¡Quien pinte más al final gana!",
    "Role pelo chão pintando com a cor do seu ovo!": "¡Rueda por el suelo pintando con tu color!",
    "Jogue BALÕES DE TINTA e pegue ROLO, TÊNIS e BOMBA.": "Lanza GLOBOS DE PINTURA y toma RODILLO, TENIS y BOMBA.",
    "Quando o tempo acabar, quem pintou mais vence!": "¡Al acabar el tiempo, quien pintó más gana!",
    "J1: WASD + ESPAÇO/F    J2: SETAS + ENTER/CTRL": "J1: WASD + ESPACIO/F    J2: FLECHAS + ENTER/CTRL",
    "60 SEGUNDOS": "60 SEGUNDOS",
    "MELHOR DE 3": "MEJOR DE 3",
    "SUPER 120s": "SÚPER 120s",
    "WASD + ESPAÇO": "WASD + ESPACIO",
    "SETAS + ENTER": "FLECHAS + ENTER",
    "ROLO!": "¡RODILLO!",
    "TÊNIS!": "¡TENIS!",
    "BOMBA DE TINTA!": "¡BOMBA DE PINTURA!",
    "SPLASH!": "¡SPLASH!",
    "PINTADO: {a}% × {b}%": "PINTADO: {a}% × {b}%",
    "ROUNDS: {a} × {b}": "RONDAS: {a} × {b}",
    "ROUND {n}!": "¡RONDA {n}!",
    "ROUND {n}": "RONDA {n}",
    "QUEM FIZER {n} VENCE": "EL PRIMERO EN {n} GANA",
    "ÚLTIMOS SEGUNDOS!": "¡ÚLTIMOS SEGUNDOS!",
    "QUEM PINTOU MAIS?": "¿QUIÉN PINTÓ MÁS?",
    "EMPATE!": "¡EMPATE!",
    "SPLAT!": "¡SPLAT!",

    # --- Descida na neve ---
    "DESCIDA NA NEVE": "BAJADA EN LA NIEVE",
    "NEVE": "NIEVE",
    "O ovo desce a montanha de trenó! Passe nas bandeiras, salte rampas e fuja do boneco gigante.":
        "¡El huevo baja la montaña en trineo! Pasa banderas, salta rampas y huye del muñeco gigante.",
    "Desça de trenó e desvie das árvores e pedras!": "¡Baja en trineo y esquiva árboles y piedras!",
    "Passe ENTRE as bandeiras: +1.5s. Errar: -3s.": "Pasa ENTRE las banderas: +1.5s. Fallar: -3s.",
    "Nas RAMPAS, aperte ← → no ar: MANOBRA +100!": "En las RAMPAS, pulsa ← → en el aire: ¡TRUCO +100!",
    "Depois de 2000 m... cuidado com o BONECO!": "Tras 2000 m... ¡cuidado con el MUÑECO!",
    "← → virar • ↓ acelerar • ↑ frear • ESPAÇO pula": "← → girar • ↓ acelerar • ↑ frenar • ESPACIO salta",
    "VERDE (FÁCIL)": "VERDE (FÁCIL)",
    "AZUL": "AZUL",
    "PRETA (DIFÍCIL)": "NEGRA (DIFÍCIL)",
    "3 TOMBOS!": "¡3 CAÍDAS!",
    "ACABOU O TEMPO!": "¡SE ACABÓ EL TIEMPO!",
    "MANOBRA!": "¡TRUCO!",
    "MANOBRA x{n}!": "¡TRUCO x{n}!",
    "BANDEIRA +{n}s": "BANDERA +{n}s",
    "TOMBOU!": "¡CAÍDA!",
    "AI!": "¡AY!",
    "O BONECO GIGANTE!": "¡EL MUÑECO GIGANTE!",
    "ABRAÇO GELADO!": "¡ABRAZO HELADO!",
    "BANDEIRAS: {a}  MANOBRAS: {b}": "BANDERAS: {a}  TRUCOS: {b}",
    "PULO": "SALTO",

    # --- Vôlei de praia ---
    "VÔLEI DE PRAIA": "VÓLEI DE PLAYA",
    "VÔLEI": "VÓLEI",
    "Vôlei de praia contra o ROBERT! Rebata a bola com a cabeça do seu ovo.":
        "¡Vóley de playa contra ROBERT! Rebota la pelota con la cabeza de tu huevo.",
    "Rebata a bola com a cabeça do seu ovo!": "¡Rebota la pelota con la cabeza de tu huevo!",
    "Se a bola cair na areia do ROBERT, ponto seu.": "Si la pelota cae en la arena de ROBERT, punto tuyo.",
    "Onde a bola bate no ovo muda o rumo dela.": "Donde la pelota toca el huevo cambia su rumbo.",
    "Quem fizer 7 pontos primeiro vence!": "¡El primero en hacer 7 puntos gana!",
    "← → ou A D para mover, ↑ W ou ESPAÇO pula": "← → o A D para moverte, ↑ W o ESPACIO salta",
    "CORTADA!": "¡REMATE!",
    "PLACAR: {a} x {b}": "MARCADOR: {a} x {b}",
    "PONTO!": "¡PUNTO!",
    "VOCÊ": "TÚ",
    "PONTO DECISIVO!": "¡PUNTO DECISIVO!",

    # --- Campo minado ---
    "CAMPO MINADO": "BUSCAMINAS",
    "MINADO": "MINAS",
    "Ovos-bomba escondidos na grama! Use os números para abrir o campo sem explodir.":
        "¡Huevos-bomba ocultos en el pasto! Usa los números para abrir el campo sin explotar.",
    "Abra a grama sem achar um OVO-BOMBA!": "¡Abre el pasto sin hallar un HUEVO-BOMBA!",
    "O número conta os ovos-bomba encostados nele.": "El número cuenta los huevos-bomba que lo tocan.",
    "Marque os ovos-bomba com a sua bandeirinha.": "Marca los huevos-bomba con tu banderita.",
    "Número com as bandeiras certas? Clique: abre tudo!": "¿Número con las banderas justas? ¡Clic: abre todo!",
    "MOUSE esq./dir. ou SETAS + ESPAÇO + F": "MOUSE izq./der. o FLECHAS + ESPACIO + F",
    "TEMPO: {n}": "TIEMPO: {n}",
    "CASAS ABERTAS: {a}/{b}": "CASILLAS ABIERTAS: {a}/{b}",
    "NÍVEL: {n}": "NIVEL: {n}",
    "KABUM!": "¡KABUM!",
    "ERA UM OVO-BOMBA!": "¡ERA UN HUEVO-BOMBA!",

    # --- Pulo nas nuvens ---
    "PULO NAS NUVENS": "SALTO EN LAS NUBES",
    "PULO NUVENS": "SALTO NUBES",
    "Seu ovo quica de nuvem em nuvem! Suba pelo céu até chegar no espaço.":
        "¡Tu huevo rebota de nube en nube! Sube por el cielo hasta llegar al espacio.",
    "O seu ovo quica sozinho nas nuvens!": "¡Tu huevo rebota solito en las nubes!",
    "Nuvem cinza de chuva se desfaz: cuidado!": "La nube gris de lluvia se deshace: ¡cuidado!",
    "A MOLA dá um SUPER PULO. Pegue os LIMÕES!": "El RESORTE da un SÚPER SALTO. ¡Toma los LIMONES!",
    "Não caia lá embaixo!": "¡No te caigas!",
    "← → ou A/D (ou o MOUSE) para ir de lado": "← → o A/D (o el MOUSE) para ir de lado",
    "ALTURA: {n} m": "ALTURA: {n} m",

    # --- Jogo da velha ---
    "JOGO DA VELHA": "TRES EN RAYA",
    "VELHA": "TRES RAYA",
    "O clássico! Seu ovinho é o X, o rival é o O. Melhor de 5: quem fizer 3 vitórias leva!":
        "¡El clásico! Tu huevito es la X, el rival es la O. Mejor de 5: ¡gana quien logre 3!",
    "Faça 3 ovinhos em linha: reta ou diagonal!": "¡Pon 3 huevitos en línea: recta o diagonal!",
    "MELHOR DE 5: quem vencer 3 rodadas leva. Quem começa alterna.":
        "MEJOR DE 5: quien gane 3 rondas gana. Quien empieza se alterna.",
    "MOUSE: clique na casa  •  TECLADO: SETAS + ENTER": "MOUSE: clic en la casilla  •  TECLADO: FLECHAS + ENTER",
    "MOUSE OU SETAS + ENTER": "MOUSE O FLECHAS + ENTER",
    "PENSANDO": "PENSANDO",
    "SUA VEZ!": "¡TU TURNO!",
    "VS BOT OU 2 JOGADORES NO MESMO PC": "VS BOT O 2 JUGADORES EN LA MISMA PC",
    "BOT": "BOT",
    "MOUSE OU SETAS": "MOUSE O FLECHAS",
    "PONTO DE {nome}!": "¡PUNTO DE {nome}!",
    "RODADAS JOGADAS: {n}": "RONDAS JUGADAS: {n}",
    "RODADA {n}  •  MELHOR DE 5": "RONDA {n}  •  MEJOR DE 5",

    # --- Cobrinha ---
    "COBRINHA DO OVO": "CULEBRITA DEL HUEVO",
    "COBRINHA": "CULEBRITA",
    "Seu ovo virou cobra! Coma limões para a cauda crescer com a sua cor.":
        "¡Tu huevo se volvió serpiente! Come limones para que la cola crezca con tu color.",
    "Guie o seu ovo e coma os LIMÕES!": "¡Guía a tu huevo y come los LIMONES!",
    "Cada limão faz a cauda crescer com a sua cor.": "Cada limón hace crecer la cola con tu color.",
    "O LIMÃO DOURADO vale 5, mas some rápido!": "El LIMÓN DORADO vale 5, ¡pero desaparece rápido!",
    "Não bata na cerca nem na própria cauda.": "No choques con la cerca ni con tu propia cola.",
    "SETAS ou WASD para mover": "FLECHAS o WASD para moverte",
    "TAMANHO: {n}": "TAMAÑO: {n}",
    "TABULEIRO CHEIO!": "¡TABLERO LLENO!",
    "LIMÃO DOURADO: {n}s": "LIMÓN DORADO: {n}s",
}
